<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Comuki.Platform.Database.Runs</RootNamespace>
    <AssemblyName>Comuki.Platform.Database.Runs</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\models\Comuki.Platform.Entity.Core\Comuki.Platform.Entity.Core.csproj" />
  </ItemGroup>

</Project>
