apiVersion: v1
kind: Service
metadata:
  name: {{ include "comuki.fullname" . }}
  labels:
    {{- include "comuki.labels" . | nindent 4 }}
    app.kubernetes.io/component: host
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "comuki.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: host
