/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Scale defaults from ScaleSupervisorOptions.
*/
export type ComputeScaleDefaultsView = {
    /**
     * @description Default worker image (digest-pinned in production).
     * @type string
    */
    workerImage: string;
    /**
     * @description Default pinned profiles git ref.
     * @type string
    */
    profilesGitRef: string;
    /**
     * @description Warm-idle floor per profile.
     * @type integer,string, int32
    */
    minIdle: (number | string);
    /**
     * @description Cap on concurrently running workers per project.
     * @type integer,string, int32
    */
    maxConcurrent: (number | string);
    /**
     * @description Idle TTL before a worker is a reaper candidate, in seconds.
     * @type integer,string, int64
    */
    idleTtlSeconds: (number | string);
    /**
     * @description Delay between supervisor passes, in seconds.
     * @type integer,string, int64
    */
    pollIntervalSeconds: (number | string);
    /**
     * @description Profile keys the supervisor polls per project.
     * @type array
    */
    profileKeys: string[];
};