/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProcedureLiveResponse } from "./ProcedureLiveResponse";

export type GetApiV1ProceduresRunsRunidLivePathParams = {
    /**
     * @description The run whose live projection to read.
     * @type string, uuid
    */
    runId: string;
};

/**
 * @description OK
*/
export type GetApiV1ProceduresRunsRunidLive200 = ProcedureLiveResponse;

export type GetApiV1ProceduresRunsRunidLiveQueryResponse = GetApiV1ProceduresRunsRunidLive200;

export type GetApiV1ProceduresRunsRunidLiveQuery = {
    Response: GetApiV1ProceduresRunsRunidLive200;
    PathParams: GetApiV1ProceduresRunsRunidLivePathParams;
    Errors: any;
};