/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails";
import type { SourceConnectionView } from "./SourceConnectionView";

export type GetApiV1SourcesSourceidPathParams = {
    /**
     * @type string, uuid
    */
    sourceId: string;
};

/**
 * @description OK
*/
export type GetApiV1SourcesSourceid200 = SourceConnectionView;

/**
 * @description Not Found
*/
export type GetApiV1SourcesSourceid404 = ProblemDetails;

export type GetApiV1SourcesSourceidQueryResponse = GetApiV1SourcesSourceid200;

export type GetApiV1SourcesSourceidQuery = {
    Response: GetApiV1SourcesSourceid200;
    PathParams: GetApiV1SourcesSourceidPathParams;
    Errors: GetApiV1SourcesSourceid404;
};