/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectView } from "./ProjectView";

export type GetApiV1ProjectsProjectidPathParams = {
    /**
     * @type string, uuid
    */
    projectId: string;
};

/**
 * @description OK
*/
export type GetApiV1ProjectsProjectid200 = ProjectView;

export type GetApiV1ProjectsProjectidQueryResponse = GetApiV1ProjectsProjectid200;

export type GetApiV1ProjectsProjectidQuery = {
    Response: GetApiV1ProjectsProjectid200;
    PathParams: GetApiV1ProjectsProjectidPathParams;
    Errors: any;
};