/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SourceConnectionView } from "./SourceConnectionView";

export type GetApiV1IntegrationSourcesQueryParams = {
    /**
     * @description Optional project filter.
     * @type string | undefined, uuid
    */
    projectId?: string;
};

/**
 * @description OK
*/
export type GetApiV1IntegrationSources200 = SourceConnectionView[];

export type GetApiV1IntegrationSourcesQueryResponse = GetApiV1IntegrationSources200;

export type GetApiV1IntegrationSourcesQuery = {
    Response: GetApiV1IntegrationSources200;
    QueryParams: GetApiV1IntegrationSourcesQueryParams;
    Errors: any;
};