/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails";
import type { ProcedureVersionResponse } from "./ProcedureVersionResponse";

export type GetApiV1ProceduresVersionsVersionidPathParams = {
    /**
     * @description The content-addressed version id.
     * @type string
    */
    versionId: string;
};

/**
 * @description OK
*/
export type GetApiV1ProceduresVersionsVersionid200 = ProcedureVersionResponse;

/**
 * @description Not Found
*/
export type GetApiV1ProceduresVersionsVersionid404 = ProblemDetails;

export type GetApiV1ProceduresVersionsVersionidQueryResponse = GetApiV1ProceduresVersionsVersionid200;

export type GetApiV1ProceduresVersionsVersionidQuery = {
    Response: GetApiV1ProceduresVersionsVersionid200;
    PathParams: GetApiV1ProceduresVersionsVersionidPathParams;
    Errors: GetApiV1ProceduresVersionsVersionid404;
};