/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdmissionRuleView } from "./AdmissionRuleView";
import type { ProblemDetails } from "./ProblemDetails";

export type GetApiV1IntegrationAdmissionRulesRuleidPathParams = {
    /**
     * @type string, uuid
    */
    ruleId: string;
};

/**
 * @description OK
*/
export type GetApiV1IntegrationAdmissionRulesRuleid200 = AdmissionRuleView;

/**
 * @description Not Found
*/
export type GetApiV1IntegrationAdmissionRulesRuleid404 = ProblemDetails;

export type GetApiV1IntegrationAdmissionRulesRuleidQueryResponse = GetApiV1IntegrationAdmissionRulesRuleid200;

export type GetApiV1IntegrationAdmissionRulesRuleidQuery = {
    Response: GetApiV1IntegrationAdmissionRulesRuleid200;
    PathParams: GetApiV1IntegrationAdmissionRulesRuleidPathParams;
    Errors: GetApiV1IntegrationAdmissionRulesRuleid404;
};