/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProblemDetails } from "./ProblemDetails";
import type { SkillDefinition } from "./SkillDefinition";

export type GetSkillsKeyPathParams = {
    /**
     * @type string
    */
    key: string;
};

/**
 * @description OK
*/
export type GetSkillsKey200 = SkillDefinition;

/**
 * @description Not Found
*/
export type GetSkillsKey404 = ProblemDetails;

export type GetSkillsKeyQueryResponse = GetSkillsKey200;

export type GetSkillsKeyQuery = {
    Response: GetSkillsKey200;
    PathParams: GetSkillsKeyPathParams;
    Errors: GetSkillsKey404;
};