/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SkillDefinition } from "./SkillDefinition";

/**
 * @description OK
*/
export type GetSkills200 = SkillDefinition[];

export type GetSkillsQueryResponse = GetSkills200;

export type GetSkillsQuery = {
    Response: GetSkills200;
    Errors: any;
};