/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateProjectRequest } from "./CreateProjectRequest";
import type { ProjectView } from "./ProjectView";

/**
 * @description Created
*/
export type PostApiV1Projects201 = ProjectView;

export type PostApiV1ProjectsMutationRequest = CreateProjectRequest;

export type PostApiV1ProjectsMutationResponse = PostApiV1Projects201;

export type PostApiV1ProjectsMutation = {
    Response: PostApiV1Projects201;
    Request: PostApiV1ProjectsMutationRequest;
    Errors: any;
};