/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateSourceConnectionRequest } from "./CreateSourceConnectionRequest";
import type { ProblemDetails } from "./ProblemDetails";
import type { SourceConnectionView } from "./SourceConnectionView";

/**
 * @description Created
*/
export type PostApiV1IntegrationSources201 = SourceConnectionView;

/**
 * @description Bad Request
*/
export type PostApiV1IntegrationSources400 = ProblemDetails;

export type PostApiV1IntegrationSourcesMutationRequest = CreateSourceConnectionRequest;

export type PostApiV1IntegrationSourcesMutationResponse = PostApiV1IntegrationSources201;

export type PostApiV1IntegrationSourcesMutation = {
    Response: PostApiV1IntegrationSources201;
    Request: PostApiV1IntegrationSourcesMutationRequest;
    Errors: PostApiV1IntegrationSources400;
};