/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FailWorkItemRequest } from "./FailWorkItemRequest";

export type PostWorkersWorkitemidFailPathParams = {
    /**
     * @type string, uuid
    */
    workItemId: string;
};

/**
 * @description OK
*/
export type PostWorkersWorkitemidFail200 = any;

export type PostWorkersWorkitemidFailMutationRequest = FailWorkItemRequest;

export type PostWorkersWorkitemidFailMutationResponse = PostWorkersWorkitemidFail200;

export type PostWorkersWorkitemidFailMutation = {
    Response: PostWorkersWorkitemidFail200;
    Request: PostWorkersWorkitemidFailMutationRequest;
    PathParams: PostWorkersWorkitemidFailPathParams;
    Errors: any;
};