/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetails } from "./ProblemDetails";

export type PostApiV1LearningCandidatesCandidateidApprovePathParams = {
    /**
     * @description Candidate to approve.
     * @type string, uuid
     */
    candidateId: string;
};

/**
 * @description No Content
 */
export type PostApiV1LearningCandidatesCandidateidApprove204 = any;

/**
 * @description Not Found
 */
export type PostApiV1LearningCandidatesCandidateidApprove404 = ProblemDetails;

/**
 * @description Conflict
 */
export type PostApiV1LearningCandidatesCandidateidApprove409 = ProblemDetails;

export type PostApiV1LearningCandidatesCandidateidApproveMutationResponse =
    PostApiV1LearningCandidatesCandidateidApprove204;

export type PostApiV1LearningCandidatesCandidateidApproveMutation = {
    Response: PostApiV1LearningCandidatesCandidateidApprove204;
    PathParams: PostApiV1LearningCandidatesCandidateidApprovePathParams;
    Errors:
        | PostApiV1LearningCandidatesCandidateidApprove404
        | PostApiV1LearningCandidatesCandidateidApprove409;
};
