/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DriftDto } from "./DriftDto";
import type { TraceEventDto } from "./TraceEventDto";

/**
 * @description Response DTO for `GET /api/v1/procedures/runs/{runId}/live` —\nthe dashboard\'s Live run mode reads this to render the pinned-version\nchrome, the path, and the drift verdict. Composed server-side from\nthe run\'s planned-vs-observed trace; the trace carries the pin\nmetadata (version, procedure key, project id, pinned at) seeded at\nadmission, so the projection is a single read. Null fields render\nat an empty state in Studio, not an HTTP error.
*/
export type ProcedureLiveResponse = {
    /**
     * @description The run the projection belongs to.
     * @type string, uuid
    */
    runId: string;
    /**
     * @description The content-addressed version id the run was bound to, or null when the\nrun never admitted against a procedure (unpinned default).
     * @type null,string
    */
    pinnedVersionId: string | null;
    /**
     * @description Stable key of the procedure the run rides, or null when unpinned.
     * @type null,string
    */
    procedureKey: string | null;
    /**
     * @description Project that owns the procedure.
     * @type null,string, uuid
    */
    projectId: string | null;
    /**
     * @description When the pin was recorded (UTC, ISO 8601).
     * @type null,string, date-time
    */
    pinnedAt: string | null;
    /**
     * @description How many events the trace carries.
     * @type integer,string, int32
    */
    eventCount: (number | string);
    /**
     * @description The trace\'s events (chronological) — server-side composed.
     * @type array
    */
    events: TraceEventDto[];
    drift: (null | DriftDto);
};