/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Response DTO for a compiled procedure version\n(`GET /api/v1/procedures/{projectId}/{procedureKey}` and\n`GET /api/v1/procedures/versions/{versionId}`). Carries only the\nidentity + provenance fields the dashboard renders — the compiled\ngraph itself stays server-side.
*/
export type ProcedureVersionResponse = {
    /**
     * @type string
    */
    versionId: string;
    /**
     * @type string, uuid
    */
    projectId: string;
    /**
     * @type string
    */
    procedureKey: string;
    /**
     * @type string
    */
    catalogVersion: string;
    /**
     * @type string
    */
    sourceRef: string;
};