/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectId } from "./ProjectId";

/**
 * @description Read model of a project — everything the operational UI needs, nothing\ninternal. Identity fields arrive display-ready: the colour is lower-case\n`#rrggbb`, tags are trimmed/lower-cased/deduplicated, the icon is an\nopaque string (emoji or URL) to render verbatim.
*/
export type ProjectView = {
    /**
     * @description Strong-typed identifier of a project — the scope unit for runs, work items,\nsettings and role assignments.
     * @type object
    */
    id: ProjectId;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    slug: string;
    /**
     * @type null,string
    */
    description: string | null;
    /**
     * @type null,string
    */
    profilesGitUrl: string | null;
    /**
     * @type null,string
    */
    profilesGitRef: string | null;
    /**
     * @type null,string
    */
    sourceGitUrl: string | null;
    /**
     * @type null,string
    */
    sourceGitRef: string | null;
    /**
     * @type null,string
    */
    icon: string | null;
    /**
     * @type null,string
    */
    color: string | null;
    /**
     * @type array
    */
    tags: string[];
    /**
     * @description Environment-class id the scalar source repository binds to (catalog id, e.g. `\"net10-sdk-bun\"`);\nnull when the project has no confirmed class. Mirrors the\n`Project.EnvClass` stand-in (add-worker-environments task 2.2):\nan empty binding means implement work items for the project are not claimable.
     * @type null,string
    */
    envClass: string | null;
    /**
     * @type boolean
    */
    archived: boolean;
    /**
     * @type null,string, date-time
    */
    archivedAt: string | null;
    /**
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @type string, date-time
    */
    updatedAt: string;
};