/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Request DTO for proposing a patch from chat\n(`POST /api/v1/procedures/{projectId}/{procedureKey}/propose-patch`).\nThe chat surface calls this when an operator asks for a procedure\nchange in chat — the brain drafts a `GraphPatch` via the\nProposePatchFromChatHandler\nand the human publishes it from Studio.
*/
export type ProposePatchRequest = {
    /**
     * @type string
    */
    baseVersionId: string;
    /**
     * @type string
    */
    rationale: string;
    /**
     * @type string
    */
    draftedBy: string;
};