/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdmissionRuleView } from "./AdmissionRuleView";
import type { ProblemDetails } from "./ProblemDetails";
import type { UpdateAdmissionRuleRequest } from "./UpdateAdmissionRuleRequest";

export type PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams = {
    /**
     * @description Source connection id (route context, not used to filter the rule lookup).
     * @type string, uuid
    */
    sourceId: string;
    /**
     * @description The admission rule id.
     * @type string, uuid
    */
    ruleId: string;
};

/**
 * @description OK
*/
export type PutApiV1IntegrationSourcesSourceidRulesRuleid200 = AdmissionRuleView;

/**
 * @description Not Found
*/
export type PutApiV1IntegrationSourcesSourceidRulesRuleid404 = ProblemDetails;

export type PutApiV1IntegrationSourcesSourceidRulesRuleidMutationRequest = UpdateAdmissionRuleRequest;

export type PutApiV1IntegrationSourcesSourceidRulesRuleidMutationResponse = PutApiV1IntegrationSourcesSourceidRulesRuleid200;

export type PutApiV1IntegrationSourcesSourceidRulesRuleidMutation = {
    Response: PutApiV1IntegrationSourcesSourceidRulesRuleid200;
    Request: PutApiV1IntegrationSourcesSourceidRulesRuleidMutationRequest;
    PathParams: PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams;
    Errors: PutApiV1IntegrationSourcesSourceidRulesRuleid404;
};