/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdmissionRuleView } from "./AdmissionRuleView";
import type { ProblemDetails } from "./ProblemDetails";
import type { UpdateAdmissionRuleRequest } from "./UpdateAdmissionRuleRequest";

export type PutApiV1AdmissionRulesRuleidPathParams = {
    /**
     * @type string, uuid
    */
    ruleId: string;
};

/**
 * @description OK
*/
export type PutApiV1AdmissionRulesRuleid200 = AdmissionRuleView;

/**
 * @description Not Found
*/
export type PutApiV1AdmissionRulesRuleid404 = ProblemDetails;

export type PutApiV1AdmissionRulesRuleidMutationRequest = UpdateAdmissionRuleRequest;

export type PutApiV1AdmissionRulesRuleidMutationResponse = PutApiV1AdmissionRulesRuleid200;

export type PutApiV1AdmissionRulesRuleidMutation = {
    Response: PutApiV1AdmissionRulesRuleid200;
    Request: PutApiV1AdmissionRulesRuleidMutationRequest;
    PathParams: PutApiV1AdmissionRulesRuleidPathParams;
    Errors: PutApiV1AdmissionRulesRuleid404;
};