/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EdgeRefDto } from "./EdgeRefDto";

/**
 * @description One rewired edge — before (removed) and after (inserted).
*/
export type RewiredEdgeDto = {
    /**
     * @description Reference to an edge in the diff.
     * @type object
    */
    before: EdgeRefDto;
    /**
     * @description Reference to an edge in the diff.
     * @type object
    */
    after: EdgeRefDto;
};