/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ComputeSettingsView } from "./ComputeSettingsView";
import type { OrchestrationSettingsView } from "./OrchestrationSettingsView";
import type { ProxySettingsView } from "./ProxySettingsView";

/**
 * @description Wire shape of `GET /api/v1/settings` — a read-only snapshot of the\r\nplatform-level settings that already exist as bound options. Every value\r\nis `IOptions`-backed (fixed at startup); there is deliberately no\r\nPUT: nothing in this surface is mutable at runtime, and pretending\r\notherwise would be phantom success. Changes go through configuration +\r\na restart.
 */
export type SettingsView = {
    /**
     * @description Orchestration policy as bound from `Orchestration:*`.
     * @type object
     */
    orchestration: OrchestrationSettingsView;
    /**
     * @description Compute selection + scale defaults from `Compute:*`.
     * @type object
     */
    compute: ComputeSettingsView;
    /**
     * @description Proxy state from ProxyOptions.
     * @type object
     */
    proxy: ProxySettingsView;
};
