/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Scheduled job partial-update body\n(`PATCH /api/v1/projects/{projectId}/scheduled-jobs/{jobId}`).\nNull fields leave the stored value untouched — the canonical PATCH\nsemantics. `cronExpression` is re-parsed on write; a malformed\nvalue surfaces `400` with the `scheduler.invalid_cron`\ncode.
*/
export type UpdateScheduledJobRequest = {
    /**
     * @description Null keeps the cron; non-null is re-parsed.
     * @type null,string
    */
    cronExpression?: string | null;
    /**
     * @description Worker brief payload replacement; null keeps the stored value.
     * @type null,string
    */
    briefJson?: string | null;
    /**
     * @description Null keeps the flag; false disables the dispatcher for this job.
     * @type null,boolean
    */
    enabled?: boolean | null;
};