/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Strong-typed identifier of a user account. Entity ids are UUIDv7\n(Guid Guid.CreateVersion7()): time-ordered, stored as Postgres\n`uuid`, exposed to the API as strings. Lives in the Identity module\n(not Shared.Kernel) — other modules learn about users through contracts.
*/
export type UserId = {
    /**
     * @type string | undefined, uuid
    */
    value?: string;
};