/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Wire row of one worker as the dashboard queue page sees it. Workers are\r\n<b>derived</b>, not registered: a busy worker is a live work-item lease\r\n(`leased_by` on a `Running` row); an idle worker is one whose\r\nlast claim still shows in the recent journal window. Fields only a\r\ncontainer runtime could answer (provider handle, uptime) are absent on\r\npurpose — this host does not compose the compute engine.
*/
export type WorkerView = {
    /**
     * @description Worker id the lease / claim event names.
     * @type string, uuid
    */
    workerId: string;
    /**
     * @description Derived: `busy` (live lease, fresh heartbeat), `offline` (lease held but stale — reaper candidate), `idle` (recent claim, no live lease).
     * @type string
    */
    state: string;
    /**
     * @description Owning project (via the leased item\'s run); null for idle rows with no live lease.
     * @type null,string, uuid
    */
    projectId: string | null;
    /**
     * @description Profile of the leased item; null when idle.
     * @type null,string
    */
    profileKey: string | null;
    /**
     * @description Image of the leased item; null when idle.
     * @type null,string
    */
    image: string | null;
    /**
     * @description Item the worker holds; null when idle.
     * @type null,string, uuid
    */
    currentWorkItemId: string | null;
    /**
     * @description Run of the leased item; null when idle.
     * @type null,string, uuid
    */
    currentRunId: string | null;
    /**
     * @description Lease expiry of the held item; null when idle.
     * @type null,string, date-time
    */
    leaseUntil: string | null;
    /**
     * @description Last heartbeat on the held item; null when idle.
     * @type null,string, date-time
    */
    heartbeatAt: string | null;
    /**
     * @description Attempts of the held item; 0 when idle.
     * @type integer,string, int32
    */
    attempt: (number | string);
    /**
     * @description Most recent of the worker\'s claim events, or the held item\'s heartbeat — whichever is later.
     * @type string, date-time
    */
    lastSeenAt: string;
};