/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { WorkTaskSourceRefView } from "./WorkTaskSourceRefView";

/**
 * @description Per-Task detail projection — the `GET /api/v1/work/tasks/{taskId}`\nresponse shape (the umbrella\'s `add-work-management` design\n§\"Work API\"). Caller-facing fields only — no aggregate internals.
*/
export type WorkTaskDetailView = {
    /**
     * @description Strong-typed task id (UUIDv7 string form).
     * @type string, uuid
    */
    id: string;
    /**
     * @description Owning project id.
     * @type string, uuid
    */
    projectId: string;
    /**
     * @description Task title.
     * @type string
    */
    title: string;
    /**
     * @description Task brief, current.
     * @type string
    */
    brief: string;
    /**
     * @description Versioned brief counter; bumped on every revision.
     * @type integer,string, int32
    */
    briefVersion: (number | string);
    /**
     * @description Wire-form status (PascalCase).
     * @type string
    */
    status: string;
    /**
     * @description Wire-form outcome if Resolved; null otherwise.
     * @type null,string
    */
    resolutionOutcome: string | null;
    /**
     * @description Current attempt ordinal; 1 before any append.
     * @type integer,string, int32
    */
    attemptOrdinal: (number | string);
    /**
     * @description Active attempt\'s run id; null when no attempt is in flight.
     * @type null,string, uuid
    */
    activeAttemptId: string | null;
    /**
     * @description Standalone | MissionAttached.
     * @type string
    */
    visibility: string;
    /**
     * @description Owning mission if MissionAttached; null otherwise.
     * @type null,string, uuid
    */
    missionId: string | null;
    /**
     * @description All source refs on the Task (primary first).
     * @type array
    */
    sourceRefs: WorkTaskSourceRefView[];
    /**
     * @description When the Task was first admitted.
     * @type string, date-time
    */
    createdAt: string;
    /**
     * @description Last status change.
     * @type string, date-time
    */
    updatedAt: string;
};