/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Stable contract identifier for one capability the Work module\nadvertises. The descriptor is immutable; consumers compare\ninstances by string WorkCapabilityDescriptor.Name (case-sensitive, ordinal).
*/
export type WorkCapabilityDescriptor = {
    /**
     * @description Stable dot.case identifier — see `add-mission-cowork/design.md` §\"Capability naming\".
     * @type string
    */
    name: string;
    /**
     * @description Short human-readable description, surfaced verbatim by the Broker probe.
     * @type string
    */
    description: string;
};