/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { WorkCapabilitiesView } from "./WorkCapabilitiesView";

/**
 * @description OK
*/
export type WorkCapabilitiesList200 = WorkCapabilitiesView;

export type WorkCapabilitiesListQueryResponse = WorkCapabilitiesList200;

export type WorkCapabilitiesListQuery = {
    Response: WorkCapabilitiesList200;
    Errors: any;
};