/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { WorkerView } from "./WorkerView";

/**
 * @description One page of derived workers plus the paging envelope (same shape as the runs page).
 */
export type WorkersPage = {
    /**
     * @description Page rows.
     * @type array
     */
    items: WorkerView[];
    /**
     * @description 1-based page number.
     * @type integer,string, int32
     */
    page: number | string;
    /**
     * @description Rows per page.
     * @type integer,string, int32
     */
    pageSize: number | string;
    /**
     * @description Total derived workers.
     * @type integer,string, int32
     */
    total: number | string;
};
