/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetails } from "./ProblemDetails"

export type ArtifactsVisualContentPathParams = {
  /**
   * @description Owning project (path, scope filter).
   * @type string, uuid
   */
  projectId: string
  /**
   * @description Artifact id (path).
   * @type string, uuid
   */
  artifactId: string
}

/**
 * @description OK
 */
export type ArtifactsVisualContent200 = any

/**
 * @description Not Found
 */
export type ArtifactsVisualContent404 = ProblemDetails

export type ArtifactsVisualContentQueryResponse = ArtifactsVisualContent200

export type ArtifactsVisualContentQuery = {
  Response: ArtifactsVisualContent200
  PathParams: ArtifactsVisualContentPathParams
  Errors: ArtifactsVisualContent404
}
