/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ChatSlashCommand = {
    /**
     * @type string
    */
    key: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type string
    */
    body: string;
    /**
     * @type string
    */
    source: string;
};