/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description What producing one message cost. Everything is optional — a user row\r\nhas no model and a journal row has no tokens — so a partial reading is\r\nexpressible without inventing zeroes.
 */
export type ChatMessageMeta = {
  /**
   * @description Model id that produced the message (`glm-4.7`, …); null for rows no model wrote.
   * @type null,string
   */
  model?: string | null
  /**
   * @description Prompt tokens consumed.
   * @type null,integer,string, int32
   */
  tokensIn?: (number | string) | null
  /**
   * @description Completion tokens produced.
   * @type null,integer,string, int32
   */
  tokensOut?: (number | string) | null
  /**
   * @description Cost in USD micros (the unit the costs capability journals).
   * @type null,integer,string, int64
   */
  costMicros?: (number | string) | null
  /**
   * @description Wall-clock time to produce the message, in milliseconds.
   * @type null,integer,string, int64
   */
  latencyMs?: (number | string) | null
  /**
   * @description Why generation stopped (`stop`, `length`, `tool_use`, …).
   * @type null,string
   */
  stopReason?: string | null
}
