/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ClaimWorkItemRequest = {
  /**
   * @type string
   */
  image: string
  /**
   * @type string
   */
  profilesRef: string
  /**
   * @type string
   */
  profileKey: string
}
