/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateNativeTicketRequest = {
    /**
     * @type string, uuid
    */
    projectId: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    body?: string;
    /**
     * @type null,string
    */
    externalId?: string | null;
    /**
     * @type null,string
    */
    author?: string | null;
};