/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateApiKeyRequest = {
  /**
   * @type string, uuid
   */
  userId: string
  /**
   * @type string
   */
  label: string
  /**
   * @type null,string, date-time
   */
  expiresAt?: string | null
}
