/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateAdmissionRuleRequest = {
  /**
   * @type string, uuid
   */
  projectId: string
  /**
   * @type string
   */
  mode: string
  /**
   * @type string
   */
  filterJson: string
}
