/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateSourceConnectionRequest = {
  /**
   * @type string, uuid
   */
  projectId: string
  /**
   * @type string
   */
  provider: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  settingsJson: string
  /**
   * @type string
   */
  secretEnvRef: string
}
