/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiV1ProjectsProjectidPathParams = {
  /**
   * @type string, uuid
   */
  projectId: string
}

/**
 * @description No Content
 */
export type DeleteApiV1ProjectsProjectid204 = any

export type DeleteApiV1ProjectsProjectidMutationResponse =
  DeleteApiV1ProjectsProjectid204

export type DeleteApiV1ProjectsProjectidMutation = {
  Response: DeleteApiV1ProjectsProjectid204
  PathParams: DeleteApiV1ProjectsProjectidPathParams
  Errors: any
}
