/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiV1ProjectsProjectidPathParams = {
  /**
   * @type string, uuid
   */
  projectId: string
}

/**
 * @description OK
 */
export type DeleteApiV1ProjectsProjectid200 = any

export type DeleteApiV1ProjectsProjectidMutationResponse =
  DeleteApiV1ProjectsProjectid200

export type DeleteApiV1ProjectsProjectidMutation = {
  Response: DeleteApiV1ProjectsProjectid200
  PathParams: DeleteApiV1ProjectsProjectidPathParams
  Errors: any
}
