/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams = {
  /**
   * @description Owning project (route context).
   * @type string, uuid
   */
  projectId: string
  /**
   * @description Job id.
   * @type string, uuid
   */
  jobId: string
}

/**
 * @description No Content
 */
export type DeleteApiV1ProjectsProjectidScheduledJobsJobid204 = any

export type DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse =
  DeleteApiV1ProjectsProjectidScheduledJobsJobid204

export type DeleteApiV1ProjectsProjectidScheduledJobsJobidMutation = {
  Response: DeleteApiV1ProjectsProjectidScheduledJobsJobid204
  PathParams: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams
  Errors: any
}
