/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Reference to an edge in the diff.
 */
export type EdgeRefDto = {
  /**
   * @description Source node id.
   * @type string
   */
  fromNodeId: string
  /**
   * @description Source outcome port.
   * @type string
   */
  fromPort: string
  /**
   * @description Destination node id.
   * @type string
   */
  toNodeId: string
}
