/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiV1ProxyKeys200 = any

export type GetApiV1ProxyKeysQueryResponse = GetApiV1ProxyKeys200

export type GetApiV1ProxyKeysQuery = {
  Response: GetApiV1ProxyKeys200
  Errors: any
}
