/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiV1Compute200 = any

export type GetApiV1ComputeQueryResponse = GetApiV1Compute200

export type GetApiV1ComputeQuery = {
  Response: GetApiV1Compute200
  Errors: any
}
