/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdmissionRuleView } from "./AdmissionRuleView"

export type GetApiV1AdmissionRulesQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  projectId?: string
}

/**
 * @description OK
 */
export type GetApiV1AdmissionRules200 = AdmissionRuleView[]

export type GetApiV1AdmissionRulesQueryResponse = GetApiV1AdmissionRules200

export type GetApiV1AdmissionRulesQuery = {
  Response: GetApiV1AdmissionRules200
  QueryParams: GetApiV1AdmissionRulesQueryParams
  Errors: any
}
