/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetails } from "./ProblemDetails"
import type { ProcedureTraceResponse } from "./ProcedureTraceResponse"

export type GetApiV1ProceduresRunsRunidTracePathParams = {
  /**
   * @description The run whose trace to read.
   * @type string, uuid
   */
  runId: string
}

/**
 * @description OK
 */
export type GetApiV1ProceduresRunsRunidTrace200 = ProcedureTraceResponse

/**
 * @description Not Found
 */
export type GetApiV1ProceduresRunsRunidTrace404 = ProblemDetails

export type GetApiV1ProceduresRunsRunidTraceQueryResponse =
  GetApiV1ProceduresRunsRunidTrace200

export type GetApiV1ProceduresRunsRunidTraceQuery = {
  Response: GetApiV1ProceduresRunsRunidTrace200
  PathParams: GetApiV1ProceduresRunsRunidTracePathParams
  Errors: GetApiV1ProceduresRunsRunidTrace404
}
