/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiV1Version200 = any

export type GetApiV1VersionQueryResponse = GetApiV1Version200

export type GetApiV1VersionQuery = {
  Response: GetApiV1Version200
  Errors: any
}
