/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description OK
 */
export type GetApiV1WorkersBackground200 = any

export type GetApiV1WorkersBackgroundQueryResponse =
  GetApiV1WorkersBackground200

export type GetApiV1WorkersBackgroundQuery = {
  Response: GetApiV1WorkersBackground200
  Errors: any
}
