/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetails } from "./ProblemDetails"
import type { SourceConnectionView } from "./SourceConnectionView"

export type GetApiV1IntegrationSourcesSourceidPathParams = {
  /**
   * @type string, uuid
   */
  sourceId: string
}

/**
 * @description OK
 */
export type GetApiV1IntegrationSourcesSourceid200 = SourceConnectionView

/**
 * @description Not Found
 */
export type GetApiV1IntegrationSourcesSourceid404 = ProblemDetails

export type GetApiV1IntegrationSourcesSourceidQueryResponse =
  GetApiV1IntegrationSourcesSourceid200

export type GetApiV1IntegrationSourcesSourceidQuery = {
  Response: GetApiV1IntegrationSourcesSourceid200
  PathParams: GetApiV1IntegrationSourcesSourceidPathParams
  Errors: GetApiV1IntegrationSourcesSourceid404
}
