/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiV1KnowledgeDocumentsQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  projectId?: string
  /**
   * @type integer,string | undefined, int32
   */
  page?: number | string
  /**
   * @type integer,string | undefined, int32
   */
  pageSize?: number | string
}

/**
 * @description OK
 */
export type GetApiV1KnowledgeDocuments200 = any

export type GetApiV1KnowledgeDocumentsQueryResponse =
  GetApiV1KnowledgeDocuments200

export type GetApiV1KnowledgeDocumentsQuery = {
  Response: GetApiV1KnowledgeDocuments200
  QueryParams: GetApiV1KnowledgeDocumentsQueryParams
  Errors: any
}
