/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { KnowledgeSearchResponse } from "./KnowledgeSearchResponse"

/**
 * @description OK
 */
export type GetApiV1KnowledgeSearch200 = KnowledgeSearchResponse

export type GetApiV1KnowledgeSearchQueryResponse = GetApiV1KnowledgeSearch200

export type GetApiV1KnowledgeSearchQuery = {
  Response: GetApiV1KnowledgeSearch200
  Errors: any
}
