/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SettingsView } from "./SettingsView"

/**
 * @description OK
 */
export type GetApiV1Settings200 = SettingsView

export type GetApiV1SettingsQueryResponse = GetApiV1Settings200

export type GetApiV1SettingsQuery = {
  Response: GetApiV1Settings200
  Errors: any
}
