/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InboundItemView } from "./InboundItemView"
import type { ProblemDetails } from "./ProblemDetails"

export type GetApiV1IntegrationInboxCatalogQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  connectionId?: string
  /**
   * @description 1-based page number.
   * @default 1
   * @type integer,string | undefined, int32
   */
  page?: number | string
}

/**
 * @description OK
 */
export type GetApiV1IntegrationInboxCatalog200 = InboundItemView[]

/**
 * @description Not Found
 */
export type GetApiV1IntegrationInboxCatalog404 = ProblemDetails

export type GetApiV1IntegrationInboxCatalogQueryResponse =
  GetApiV1IntegrationInboxCatalog200

export type GetApiV1IntegrationInboxCatalogQuery = {
  Response: GetApiV1IntegrationInboxCatalog200
  QueryParams: GetApiV1IntegrationInboxCatalogQueryParams
  Errors: GetApiV1IntegrationInboxCatalog404
}
