/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IdentityAdminPage } from "./IdentityAdminPage"
import type { ProblemDetails } from "./ProblemDetails"

export type GetApiV1UsersQueryParams = {
  /**
   * @type string | undefined
   */
  EmailContains?: string
  /**
   * @type integer,string | undefined, int32
   */
  Page?: number | string
  /**
   * @type integer,string | undefined, int32
   */
  PageSize?: number | string
}

/**
 * @description OK
 */
export type GetApiV1Users200 = IdentityAdminPage

/**
 * @description Bad Request
 */
export type GetApiV1Users400 = ProblemDetails

export type GetApiV1UsersQueryResponse = GetApiV1Users200

export type GetApiV1UsersQuery = {
  Response: GetApiV1Users200
  QueryParams: GetApiV1UsersQueryParams
  Errors: GetApiV1Users400
}
