/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatCommandDefinition } from "./ChatCommandDefinition"

/**
 * @description OK
 */
export type GetChatCommands200 = ChatCommandDefinition[]

export type GetChatCommandsQueryResponse = GetChatCommands200

export type GetChatCommandsQuery = {
  Response: GetChatCommands200
  Errors: any
}
