/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type IntakeTicketView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string, uuid
   */
  projectId: string
  /**
   * @type string
   */
  source: string
  /**
   * @type string
   */
  externalId: string
  /**
   * @type string
   */
  title: string
  /**
   * @type string
   */
  url: string
  /**
   * @type string
   */
  status: string
  /**
   * @type null,string, uuid
   */
  runId: string | null
  /**
   * @type string, date-time
   */
  createdAt: string
}
