/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessagePartCodePart } from "./MessagePartCodePart"
import type { MessagePartDiagramPart } from "./MessagePartDiagramPart"
import type { MessagePartHandoffPart } from "./MessagePartHandoffPart"
import type { MessagePartPlanPart } from "./MessagePartPlanPart"
import type { MessagePartTextPart } from "./MessagePartTextPart"
import type { MessagePartThinkingPart } from "./MessagePartThinkingPart"
import type { MessagePartToolPart } from "./MessagePartToolPart"

export type MessagePart =
  | (MessagePartTextPart & {
      kind: "text"
    })
  | (MessagePartCodePart & {
      kind: "code"
    })
  | (MessagePartDiagramPart & {
      kind: "diagram"
    })
  | (MessagePartThinkingPart & {
      kind: "thinking"
    })
  | (MessagePartToolPart & {
      kind: "tool"
    })
  | (MessagePartHandoffPart & {
      kind: "handoff"
    })
  | (MessagePartPlanPart & {
      kind: "plan"
    })
