/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const messagePartHandoffPartKindEnum = {
  handoff: "handoff",
} as const

export type MessagePartHandoffPartKindEnumKey =
  (typeof messagePartHandoffPartKindEnum)[keyof typeof messagePartHandoffPartKindEnum]

export type MessagePartHandoffPart = {
  /**
   * @type string | undefined
   */
  kind?: MessagePartHandoffPartKindEnumKey
  /**
   * @type string
   */
  query: string
}
