/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const messagePartHandoffPartKindEnum = {
  handoff: "handoff",
} as const

export type MessagePartHandoffPartKindEnumKey =
  (typeof messagePartHandoffPartKindEnum)[keyof typeof messagePartHandoffPartKindEnum]

/**
 * @description A hand-off to a screen. The console resolves the query through the\r\nsame search shapes the command palette uses, so chat and palette\r\ncannot disagree about where an answer lives.
 */
export type MessagePartHandoffPart = {
  /**
   * @type string | undefined
   */
  kind?: MessagePartHandoffPartKindEnumKey
  /**
   * @description Search query that opens the destination.
   * @type string
   */
  query: string
}
