/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const messagePartThinkingPartKindEnum = {
  thinking: "thinking",
} as const

export type MessagePartThinkingPartKindEnumKey =
  (typeof messagePartThinkingPartKindEnum)[keyof typeof messagePartThinkingPartKindEnum]

/**
 * @description The model\'s visible reasoning — collapsed by default in the console.
 */
export type MessagePartThinkingPart = {
  /**
   * @type string | undefined
   */
  kind?: MessagePartThinkingPartKindEnumKey
  /**
   * @description Reasoning text.
   * @type string
   */
  text: string
  /**
   * @description Reasoning tokens the model reported; null when unknown.
   * @type null,integer,string, int32
   */
  tokens?: (number | string) | null
}
