/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const messagePartCodePartKindEnum = {
  code: "code",
} as const

export type MessagePartCodePartKindEnumKey =
  (typeof messagePartCodePartKindEnum)[keyof typeof messagePartCodePartKindEnum]

/**
 * @description A source listing. Path and\r\nStartLine anchor it in a repository when the\r\nfragment was read from one.
 */
export type MessagePartCodePart = {
  /**
   * @type string | undefined
   */
  kind?: MessagePartCodePartKindEnumKey
  /**
   * @description Highlighting language key (`csharp`, `ts`, …).
   * @type string
   */
  language: string
  /**
   * @description The listing itself, verbatim.
   * @type string
   */
  source: string
  /**
   * @description Repository-relative file path; null when the snippet is free-standing.
   * @type null,string
   */
  path?: string | null
  /**
   * @description 1-based line the listing starts at; null when unanchored.
   * @type null,integer,string, int32
   */
  startLine?: (number | string) | null
}
