/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Platform-wide and per-project permission keys.
 */
export type PermissionsView = {
  /**
   * @type array
   */
  platform: string[]
  /**
   * @type object
   */
  projects: {
    [key: string]: string[]
  }
}
