/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiKeyView } from "./ApiKeyView"
import type { ProblemDetails } from "./ProblemDetails"

export type PostApiV1KeysKeyidRevokePathParams = {
  /**
   * @type string, uuid
   */
  keyId: string
}

/**
 * @description OK
 */
export type PostApiV1KeysKeyidRevoke200 = ApiKeyView

/**
 * @description Not Found
 */
export type PostApiV1KeysKeyidRevoke404 = ProblemDetails

export type PostApiV1KeysKeyidRevokeMutationResponse =
  PostApiV1KeysKeyidRevoke200

export type PostApiV1KeysKeyidRevokeMutation = {
  Response: PostApiV1KeysKeyidRevoke200
  PathParams: PostApiV1KeysKeyidRevokePathParams
  Errors: PostApiV1KeysKeyidRevoke404
}
