/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LinkOidcRequest } from "./LinkOidcRequest"
import type { OidcLinkView } from "./OidcLinkView"
import type { ProblemDetails } from "./ProblemDetails"

export type PostApiV1UsersUseridOidcLinkPathParams = {
  /**
   * @type string, uuid
   */
  userId: string
}

/**
 * @description Created
 */
export type PostApiV1UsersUseridOidcLink201 = OidcLinkView

/**
 * @description Bad Request
 */
export type PostApiV1UsersUseridOidcLink400 = ProblemDetails

/**
 * @description Not Found
 */
export type PostApiV1UsersUseridOidcLink404 = ProblemDetails

/**
 * @description Conflict
 */
export type PostApiV1UsersUseridOidcLink409 = ProblemDetails

export type PostApiV1UsersUseridOidcLinkMutationRequest = LinkOidcRequest

export type PostApiV1UsersUseridOidcLinkMutationResponse =
  PostApiV1UsersUseridOidcLink201

export type PostApiV1UsersUseridOidcLinkMutation = {
  Response: PostApiV1UsersUseridOidcLink201
  Request: PostApiV1UsersUseridOidcLinkMutationRequest
  PathParams: PostApiV1UsersUseridOidcLinkPathParams
  Errors:
    | PostApiV1UsersUseridOidcLink400
    | PostApiV1UsersUseridOidcLink404
    | PostApiV1UsersUseridOidcLink409
}
