/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateApiKeyRequest } from "./CreateApiKeyRequest"
import type { IssuedApiKeyResponse } from "./IssuedApiKeyResponse"
import type { ProblemDetails } from "./ProblemDetails"

/**
 * @description Created
 */
export type PostApiV1Keys201 = IssuedApiKeyResponse

/**
 * @description Bad Request
 */
export type PostApiV1Keys400 = ProblemDetails

/**
 * @description Not Found
 */
export type PostApiV1Keys404 = ProblemDetails

export type PostApiV1KeysMutationRequest = CreateApiKeyRequest

export type PostApiV1KeysMutationResponse = PostApiV1Keys201

export type PostApiV1KeysMutation = {
  Response: PostApiV1Keys201
  Request: PostApiV1KeysMutationRequest
  Errors: PostApiV1Keys400 | PostApiV1Keys404
}
