/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description No Content
 */
export type PostApiV1AuthLogout204 = any

export type PostApiV1AuthLogoutMutationResponse = PostApiV1AuthLogout204

export type PostApiV1AuthLogoutMutation = {
  Response: PostApiV1AuthLogout204
  Errors: any
}
