/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProblemDetails } from "./ProblemDetails"
import type { SourceProbeResult } from "./SourceProbeResult"

export type PostApiV1IntegrationSourcesSourceidProbePathParams = {
  /**
   * @type string, uuid
   */
  sourceId: string
}

/**
 * @description OK
 */
export type PostApiV1IntegrationSourcesSourceidProbe200 = SourceProbeResult

/**
 * @description Not Found
 */
export type PostApiV1IntegrationSourcesSourceidProbe404 = ProblemDetails

export type PostApiV1IntegrationSourcesSourceidProbeMutationResponse =
  PostApiV1IntegrationSourcesSourceidProbe200

export type PostApiV1IntegrationSourcesSourceidProbeMutation = {
  Response: PostApiV1IntegrationSourcesSourceidProbe200
  PathParams: PostApiV1IntegrationSourcesSourceidProbePathParams
  Errors: PostApiV1IntegrationSourcesSourceidProbe404
}
