/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostWorkersWorkitemidHeartbeatPathParams = {
  /**
   * @type string, uuid
   */
  workItemId: string
}

/**
 * @description OK
 */
export type PostWorkersWorkitemidHeartbeat200 = any

export type PostWorkersWorkitemidHeartbeatMutationResponse =
  PostWorkersWorkitemidHeartbeat200

export type PostWorkersWorkitemidHeartbeatMutation = {
  Response: PostWorkersWorkitemidHeartbeat200
  PathParams: PostWorkersWorkitemidHeartbeatPathParams
  Errors: any
}
