/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ClaimWorkItemRequest } from "./ClaimWorkItemRequest"

/**
 * @description OK
 */
export type PostWorkersClaim200 = any

export type PostWorkersClaimMutationRequest = ClaimWorkItemRequest

export type PostWorkersClaimMutationResponse = PostWorkersClaim200

export type PostWorkersClaimMutation = {
  Response: PostWorkersClaim200
  Request: PostWorkersClaimMutationRequest
  Errors: any
}
