/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateNativeTicketRequest } from "./CreateNativeTicketRequest"
import type { IntakeTicketView } from "./IntakeTicketView"
import type { ProblemDetails } from "./ProblemDetails"

/**
 * @description Created
 */
export type PostApiV1Tickets201 = IntakeTicketView

/**
 * @description Bad Request
 */
export type PostApiV1Tickets400 = ProblemDetails

/**
 * @description Conflict
 */
export type PostApiV1Tickets409 = ProblemDetails

export type PostApiV1TicketsMutationRequest = CreateNativeTicketRequest

export type PostApiV1TicketsMutationResponse = PostApiV1Tickets201

export type PostApiV1TicketsMutation = {
  Response: PostApiV1Tickets201
  Request: PostApiV1TicketsMutationRequest
  Errors: PostApiV1Tickets400 | PostApiV1Tickets409
}
