/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ClaimTicketRequest } from "./ClaimTicketRequest"
import type { IntakeTicketView } from "./IntakeTicketView"
import type { ProblemDetails } from "./ProblemDetails"

/**
 * @description OK
 */
export type PostApiV1InboxClaim200 = IntakeTicketView

/**
 * @description Bad Request
 */
export type PostApiV1InboxClaim400 = ProblemDetails

/**
 * @description Not Found
 */
export type PostApiV1InboxClaim404 = ProblemDetails

/**
 * @description Conflict
 */
export type PostApiV1InboxClaim409 = ProblemDetails

export type PostApiV1InboxClaimMutationRequest = ClaimTicketRequest

export type PostApiV1InboxClaimMutationResponse = PostApiV1InboxClaim200

export type PostApiV1InboxClaimMutation = {
  Response: PostApiV1InboxClaim200
  Request: PostApiV1InboxClaimMutationRequest
  Errors:
    PostApiV1InboxClaim400 | PostApiV1InboxClaim404 | PostApiV1InboxClaim409
}
