/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateScheduledJobRequest } from "./CreateScheduledJobRequest"
import type { ProblemDetails } from "./ProblemDetails"
import type { ScheduledJobView } from "./ScheduledJobView"

export type PostApiV1ProjectsProjectidScheduledJobsPathParams = {
  /**
   * @description Owning project.
   * @type string, uuid
   */
  projectId: string
}

/**
 * @description Created
 */
export type PostApiV1ProjectsProjectidScheduledJobs201 = ScheduledJobView

/**
 * @description Bad Request
 */
export type PostApiV1ProjectsProjectidScheduledJobs400 = ProblemDetails

export type PostApiV1ProjectsProjectidScheduledJobsMutationRequest =
  CreateScheduledJobRequest

export type PostApiV1ProjectsProjectidScheduledJobsMutationResponse =
  PostApiV1ProjectsProjectidScheduledJobs201

export type PostApiV1ProjectsProjectidScheduledJobsMutation = {
  Response: PostApiV1ProjectsProjectidScheduledJobs201
  Request: PostApiV1ProjectsProjectidScheduledJobsMutationRequest
  PathParams: PostApiV1ProjectsProjectidScheduledJobsPathParams
  Errors: PostApiV1ProjectsProjectidScheduledJobs400
}
