/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CancelRunRequest } from "./CancelRunRequest"
import type { ProblemDetails } from "./ProblemDetails"

export type PostApiV1RunsRunidCancelPathParams = {
  /**
   * @type string, uuid
   */
  runId: string
}

/**
 * @description No Content
 */
export type PostApiV1RunsRunidCancel204 = any

/**
 * @description Not Found
 */
export type PostApiV1RunsRunidCancel404 = ProblemDetails

/**
 * @description Conflict
 */
export type PostApiV1RunsRunidCancel409 = ProblemDetails

export type PostApiV1RunsRunidCancelMutationRequest = CancelRunRequest

export type PostApiV1RunsRunidCancelMutationResponse =
  PostApiV1RunsRunidCancel204

export type PostApiV1RunsRunidCancelMutation = {
  Response: PostApiV1RunsRunidCancel204
  Request: PostApiV1RunsRunidCancelMutationRequest
  PathParams: PostApiV1RunsRunidCancelPathParams
  Errors: PostApiV1RunsRunidCancel404 | PostApiV1RunsRunidCancel409
}
