/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProbeSourceDraftRequest = {
  /**
   * @type string
   */
  provider: string
  /**
   * @type string
   */
  settingsJson: string
  /**
   * @type string
   */
  secretEnvRef: string
}
