/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response DTO for a compiled procedure version\r\n(`GET /api/v1/procedures/{projectId}/{procedureKey}` and\r\n`GET /api/v1/procedures/versions/{versionId}`). Carries only the\r\nidentity + provenance fields the dashboard renders — the compiled\r\ngraph itself stays server-side.
 */
export type ProcedureVersionResponse = {
  /**
   * @type string
   */
  versionId: string
  /**
   * @type string, uuid
   */
  projectId: string
  /**
   * @type string
   */
  procedureKey: string
  /**
   * @type string
   */
  catalogVersion: string
  /**
   * @type string
   */
  sourceRef: string
}
