/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectId } from "./ProjectId"
import type { UsageEventView } from "./UsageEventView"

/**
 * @description Project cost summary for GET /api/v1/projects/{id}/costs.\r\nMoney fields are USD micros (1 USD = 1_000_000).
 */
export type ProjectCostsView = {
  /**
   * @description Strong-typed identifier of a project — the scope unit for runs, work items,\r\nsettings and role assignments.
   * @type object
   */
  projectId: ProjectId
  /**
   * @type integer,string, int64
   */
  spentUsdMicros: number | string
  /**
   * @type null,integer,string, int64
   */
  softLimitUsdMicros: (number | string) | null
  /**
   * @type null,integer,string, int64
   */
  hardLimitUsdMicros: (number | string) | null
  /**
   * @type boolean
   */
  softExceeded: boolean
  /**
   * @type boolean
   */
  hardExceeded: boolean
  /**
   * @type array
   */
  recent: UsageEventView[]
}
