/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Wire row of one project\'s slice.
 */
export type ProjectCostSliceView = {
  /**
   * @description Project the spend is attributed to.
   * @type string, uuid
   */
  projectId: string
  /**
   * @description Window spend in USD micros.
   * @type integer,string, int64
   */
  costUsdMicros: number | string
  /**
   * @description Distinct runs the window\'s events name.
   * @type integer,string, int32
   */
  runs: number | string
}
