/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Strong-typed identifier of a project — the scope unit for runs, work items,\r\nsettings and role assignments.
 */
export type ProjectId = {
  /**
   * @type string | undefined, uuid
   */
  value?: string
}
