/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Reject body of the learning-candidates surface — carries the optional human reason.
 */
export type RejectLearningCandidateRequest = {
  /**
   * @description Why the suggestion was rejected; null means \"no reason given\".
   * @type null,string
   */
  reason: string | null
}
