/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { VerificationGateView } from "./VerificationGateView"

/**
 * @description Run-level wire shape for `GET /api/v1/runs/{runId}/verification`\n(add-orchestra §3 — Coda, `verification/spec.md` Requirement\n\"Verification view is a derived read\"). The two top-level booleans\nsurface the \"verification pending\" annotation the FE renders as a\npill under the run\'s status strip; the per-gate list renders as the\nevidence drill-down beneath it. The semantics are derived from the\nIReadOnlyList&lt;VerificationGateView&gt; RunVerificationView.Gates list alone — a future per-project\n`VerifyEnabled` read is gated on the registry returning at\nleast one record (the project is provably opted in if a provider\nhas stamped anything).
 */
export type RunVerificationView = {
  /**
   * @description Run the verdicts belong to.
   * @type string, uuid
   */
  runId: string
  /**
   * @description `true` when every gate in IReadOnlyList&lt;VerificationGateView&gt; RunVerificationView.Gates is\n`passed` AND at least one gate has been evaluated — the run\'s\nverification axis is fully terminal and positive. A run with no\ngates yet, with mixed `passed`/`pending`, or with any\n`failed` is `false`.
   * @type boolean
   */
  verified: boolean
  /**
   * @description `true` when at least one gate is still `pending`\nAND the run is not yet fully verified — the \"verification pending\"\nannotation the spec introduces. Terminal failures do NOT count as\npending: a run with one `pending` and one `failed` gate\nis `pending=true`; a run with only `failed` is\n`pending=false`.
   * @type boolean
   */
  verificationPending: boolean
  /**
   * @description One entry per evaluated (work item, gate) pair. Newest first within a work item.
   * @type array
   */
  gates: VerificationGateView[]
}
