/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ScheduledJobView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string, uuid
   */
  projectId: string
  /**
   * @type string
   */
  cronExpression: string
  /**
   * @type string
   */
  profileKey: string
  /**
   * @type string
   */
  briefJson: string
  /**
   * @type null,string, date-time
   */
  runOnOnceAt: string | null
  /**
   * @type boolean
   */
  enabled: boolean
  /**
   * @type null,string, date-time
   */
  lastFiredAt: string | null
  /**
   * @type string, date-time
   */
  nextFireAt: string
  /**
   * @type string, date-time
   */
  createdAt: string
  /**
   * @type string, date-time
   */
  updatedAt: string
}
