/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ScheduledJobView } from "./ScheduledJobView"

/**
 * @description One paginated read of scheduled jobs for a project.\r\nWire shape: `{ \"items\": [ScheduledJobView], \"total\": N }`.\r\nThe scheduler surface is small (per project, one page per request)\r\n— pagination is opt-in via `?page` + `?pageSize`; the\r\ndefault returns everything.
 */
export type ScheduledJobsPage = {
  /**
   * @description Page contents (already-projected views).
   * @type array
   */
  items: ScheduledJobView[]
  /**
   * @description Total jobs in the project (not the page size).
   * @type integer,string, int32
   */
  total: number | string
}
