/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SecretRotationResponse = {
  /**
   * @type string, uuid
   */
  sourceId: string
  /**
   * @type string
   */
  secret: string
  /**
   * @type string
   */
  secretEnvRef: string
  /**
   * @type string, date-time
   */
  rotatedAt: string
}
