/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectDomainType } from "./ProjectDomainType"

/**
 * @description Wire body of PUT /api/v1/projects/{projectId}/settings.\r\nint UpdateSettingsRequest.Version is the version the client read — a stale version\r\nis refused with 409.
 */
export type UpdateSettingsRequest = {
  /**
   * @type integer,string, int32
   */
  version: number | string
  /**
   * @type integer,string, int32
   */
  minIdle: number | string
  /**
   * @type integer,string, int32
   */
  maxConcurrent: number | string
  /**
   * @type null,integer,string, int32
   */
  idleTtlSeconds: (number | string) | null
  /**
   * @type boolean
   */
  approveRequired: boolean
  /**
   * @type boolean
   */
  knowledgeEnabled: boolean
  /**
   * @type boolean
   */
  verifyEnabled: boolean
  /**
   * @type boolean
   */
  proxyEnabled: boolean
  /**
   * @type null,integer,string, int64
   */
  softBudgetUsdMicros: (number | string) | null
  /**
   * @type null,integer,string, int64
   */
  hardBudgetUsdMicros: (number | string) | null
  /**
   * @description Per-project routing mode for user-facing domain types\r\n(`code`, `data`, `infra`, `research`, …).\r\nA Standard project sends every domain through the fixed default\r\nprofile. A Custom project routes only via the\r\nstring? ProjectSettings.CustomDomainTypesJson map. A Hybrid\r\nproject tries the default first, falls back to the JSON map.
   */
  domainType: ProjectDomainType
  /**
   * @description Per-project JSON map of `domain-type → profile-key`.
   * @type null,string
   */
  customDomainTypesJson: string | null
}
