/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Wire body of PATCH /api/v1/projects/{projectId} — null fields are left untouched.
 */
export type UpdateProjectRequest = {
  /**
   * @type null,string
   */
  name: string | null
  /**
   * @type null,string
   */
  description: string | null
  /**
   * @type null,string
   */
  profilesGitUrl: string | null
  /**
   * @type null,string
   */
  profilesGitRef: string | null
}
