/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateSourceConnectionRequest = {
    /**
     * @type null,string
    */
    name?: string | null;
    /**
     * @type null,string
    */
    settingsJson?: string | null;
    /**
     * @type null,string
    */
    secretEnvRef?: string | null;
    /**
     * @type null,boolean
    */
    enabled?: boolean | null;
};