/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateAdmissionRuleRequest = {
    /**
     * @type null,string
    */
    mode?: string | null;
    /**
     * @type null,string
    */
    filterJson?: string | null;
    /**
     * @type null,boolean
    */
    enabled?: boolean | null;
};