/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserId } from "./UserId"

export type UserAccountView = {
  /**
   * @type object
   */
  id: UserId
  /**
   * @type string
   */
  email: string
  /**
   * @type string
   */
  displayName: string
  /**
   * @type boolean
   */
  disabled: boolean
  /**
   * @type integer,string, int32
   */
  tokensVersion: number | string
  /**
   * @type string, date-time
   */
  createdAt: string
}
