/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserId } from "./UserId"

/**
 * @description Read model of a user account — no secrets ride along.
 */
export type UserAccountView = {
  /**
   * @description Strong-typed identifier of a user account. Entity ids are UUIDv7\r\n(Guid Guid.CreateVersion7()): time-ordered, stored as Postgres\r\n`uuid`, exposed to the API as strings. Lives in the Identity module\r\n(not Shared.Kernel) — other modules learn about users through contracts.
   * @type object
   */
  id: UserId
  /**
   * @type string
   */
  email: string
  /**
   * @type string
   */
  displayName: string
  /**
   * @type boolean
   */
  disabled: boolean
  /**
   * @type integer,string, int32
   */
  tokensVersion: number | string
  /**
   * @type string, date-time
   */
  createdAt: string
}
