/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { VisualArtifactListItem } from "./VisualArtifactListItem"

export type VisualArtifactPage = {
  /**
   * @type array
   */
  items: VisualArtifactListItem[]
  /**
   * @type string, uuid
   */
  projectId: string
}
