<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Comuki.Modules.Verify.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\shared\Comuki.Shared.Kernel\Comuki.Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
