/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type { GetApiV1InfoQueryResponse } from "../types/GetApiV1Info.ts"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1Info } from "../clients/getApiV1Info.ts"

export const getApiV1InfoQueryKey = () => [{ url: "/api/v1/info" }] as const

export type GetApiV1InfoQueryKey = ReturnType<typeof getApiV1InfoQueryKey>

export function getApiV1InfoQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1InfoQueryKey()
  return queryOptions<
    GetApiV1InfoQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1InfoQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Info({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /api/v1/info}
 */
export function useGetApiV1Info<
  TData = GetApiV1InfoQueryResponse,
  TQueryData = GetApiV1InfoQueryResponse,
  TQueryKey extends QueryKey = GetApiV1InfoQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1InfoQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getApiV1InfoQueryKey()

  const query = useQuery(
    {
      ...getApiV1InfoQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
