// <auto-generated />
using System;
using Comuki.Modules.Artifacts.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comuki.Modules.Artifacts.Infrastructure.Migrations
{
    [DbContext(typeof(ArtifactsDbContext))]
    [Migration("20260903141326_InitialArtifactsSchema")]
    partial class InitialArtifactsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comuki.Modules.Artifacts.Domain.RunArtifactBundle", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("RunId")
                        .HasName("pk_run_bundles");

                    b.ToTable("run_bundles", "artifacts");
                });
#pragma warning restore 612, 618
        }
    }
}
