// <auto-generated-stub />
// Source: hand-placed placeholder — REPLACE on next CLI `bun run generate:contracts`.
// The CLI's kubb config (`cli/kubb.config.ts`) regenerates the HTTP half of
// `cli/src/contracts/_generated/http/types/*` from
// `artifacts/openapi.json` and would emit `EditionView.ts`,
// `FeatureAvailabilityView.ts` and `LimitUsageView.ts` next to its other
// HTTP types; until that regen runs in CI, this self-contained module
// lets `cli/src/contracts/index.ts` (and downstream CLI commands) reference
// the edition shape without a hand-edit drift. The two paths are
// byte-identical on the wire (the kubb types are derived from the same
// OpenAPI document this file mirrors); replacing this stub with the
// kubb output is a delete-and-rename. eslint-disable-next-line @typescript-eslint/consistent-type-definitions

export const EditionStatusValues = {
  Valid: "valid",
  Grace: "grace",
  Expired: "expired",
  Absent: "absent",
} as const;

export type EditionStatus =
  (typeof EditionStatusValues)[keyof typeof EditionStatusValues];

export interface FeatureAvailabilityView {
  readonly key: string;
  readonly available: boolean;
}

export interface LimitUsageView {
  readonly key: string;
  readonly current: number;
  readonly cap: number;
}

export interface EditionView {
  readonly tier: string;
  readonly status: EditionStatus;
  readonly features: ReadonlyArray<FeatureAvailabilityView>;
  readonly limits: ReadonlyArray<LimitUsageView>;
  readonly version: string;
  /**
   * ISO-8601 UTC expiry from the verified license. The host emits this
   * only when `Status` is not `absent` (the C# side uses
   * `[JsonIgnore(Condition = WhenWritingNull)]`); the CLI matches that
   * contract by treating an absent field as "no expiry applies".
   */
  readonly expiresAt?: string;
}
