// <auto-generated />
// Source: Comuki.Shared.Contracts/Realtime (C#) -- DO NOT EDIT BY HAND.
// Regenerate via: dotnet run --project tools/Comuki.Codegen.Realtime (slice #11).
// eslint-disable-next-line @typescript-eslint/consistent-type-definitions

export const RealtimeTransportMethods = {
  RunEvent: "RunEvent",
  Attention: "Attention",
  ChatChunk: "ChatChunk",
  ChatTurnComplete: "ChatTurnComplete",
} as const;

export interface AttentionView {
  readonly runId: string;
  readonly projectId: string;
  readonly workItemId: string | null;
  readonly status: string;
  readonly attentionKind: string;
  readonly occurredAtUnixMs: number;
}

export interface ChatChunkView {
  readonly sessionId: string;
  readonly seq: number;
  readonly text: string;
}

export interface ChatTurnCompleteView {
  readonly sessionId: string;
  readonly outcome: string;
}

export interface RunEventView {
  readonly runId: string;
  readonly type: string;
  readonly workItemId: string | null;
  readonly occurredAtUnixMs: number;
  readonly payloadJson: string | null;
  readonly payloadOmitted: boolean;
}

