<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>Comuki.Host.Translator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="protobuf-net.Grpc" />
    <PackageReference Include="Refit.HttpClientFactory" />
    <PackageReference Include="Refit.Reflection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Comuki.Shared.Contracts\Comuki.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
