/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  ArtifactsVisualListQueryResponse,
  ArtifactsVisualListPathParams,
  ArtifactsVisualListQueryParams,
  ArtifactsVisualList404,
} from "../types/ArtifactsVisualList"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { artifactsVisualList } from "../clients/artifactsVisualList"

export const artifactsVisualListQueryKey = (
  projectId: ArtifactsVisualListPathParams["projectId"] | undefined,
  params?: ArtifactsVisualListQueryParams
) =>
  [
    {
      url: "/api/v1/projects/:projectId/artifacts",
      params: { projectId: projectId },
    },
    ...(params ? [params] : []),
  ] as const

export type ArtifactsVisualListQueryKey = ReturnType<
  typeof artifactsVisualListQueryKey
>

export function artifactsVisualListQueryOptions(
  projectId: ArtifactsVisualListPathParams["projectId"] | undefined,
  params?: ArtifactsVisualListQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = artifactsVisualListQueryKey(projectId, params)
  return queryOptions<
    ArtifactsVisualListQueryResponse,
    ResponseErrorConfig<ArtifactsVisualList404>,
    ArtifactsVisualListQueryResponse,
    typeof queryKey
  >({
    enabled: !!projectId,
    queryKey,
    queryFn: async ({ signal }) => {
      return artifactsVisualList(projectId!, params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary One page of visual-artifact metadata for one project, oldest
 * first. Empty when the project has no visual artifacts yet.
 * {@link /api/v1/projects/:projectId/artifacts}
 */
export function useArtifactsVisualList<
  TData = ArtifactsVisualListQueryResponse,
  TQueryData = ArtifactsVisualListQueryResponse,
  TQueryKey extends QueryKey = ArtifactsVisualListQueryKey,
>(
  projectId: ArtifactsVisualListPathParams["projectId"] | undefined,
  params?: ArtifactsVisualListQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ArtifactsVisualListQueryResponse,
        ResponseErrorConfig<ArtifactsVisualList404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? artifactsVisualListQueryKey(projectId, params)

  const query = useQuery(
    {
      ...artifactsVisualListQueryOptions(projectId, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ArtifactsVisualList404>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
