/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  ArtifactsVisualContentQueryResponse,
  ArtifactsVisualContentPathParams,
  ArtifactsVisualContent404,
} from "../types/ArtifactsVisualContent"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { artifactsVisualContent } from "../clients/artifactsVisualContent"

export const artifactsVisualContentSuspenseQueryKey = (
  projectId: ArtifactsVisualContentPathParams["projectId"] | undefined,
  artifactId: ArtifactsVisualContentPathParams["artifactId"] | undefined
) =>
  [
    {
      url: "/api/v1/projects/:projectId/artifacts/:artifactId/content",
      params: { projectId: projectId, artifactId: artifactId },
    },
  ] as const

export type ArtifactsVisualContentSuspenseQueryKey = ReturnType<
  typeof artifactsVisualContentSuspenseQueryKey
>

export function artifactsVisualContentSuspenseQueryOptions(
  projectId: ArtifactsVisualContentPathParams["projectId"],
  artifactId: ArtifactsVisualContentPathParams["artifactId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = artifactsVisualContentSuspenseQueryKey(projectId, artifactId)
  return queryOptions<
    ArtifactsVisualContentQueryResponse,
    ResponseErrorConfig<ArtifactsVisualContent404>,
    ArtifactsVisualContentQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return artifactsVisualContent(projectId, artifactId, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Streams the bytes of one visual artifact. `image/png`
 * serves with a short cache + nosniff; `text/html` and
 * `image/svg+xml` add a strict CSP that blocks
 * same-origin / inline-eval / remote-frame — the FE embeds them
 * in a sandboxed iframe, never the dashboard's frame.
 * {@link /api/v1/projects/:projectId/artifacts/:artifactId/content}
 */
export function useArtifactsVisualContentSuspense<
  TData = ArtifactsVisualContentQueryResponse,
  TQueryKey extends QueryKey = ArtifactsVisualContentSuspenseQueryKey,
>(
  projectId: ArtifactsVisualContentPathParams["projectId"],
  artifactId: ArtifactsVisualContentPathParams["artifactId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ArtifactsVisualContentQueryResponse,
        ResponseErrorConfig<ArtifactsVisualContent404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    artifactsVisualContentSuspenseQueryKey(projectId, artifactId)

  const query = useSuspenseQuery(
    {
      ...artifactsVisualContentSuspenseQueryOptions(
        projectId,
        artifactId,
        config
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<ArtifactsVisualContent404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
