/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  ArtifactsVisualContentQueryResponse,
  ArtifactsVisualContentPathParams,
  ArtifactsVisualContent404,
} from "../types/ArtifactsVisualContent"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { artifactsVisualContent } from "../clients/artifactsVisualContent"

export const artifactsVisualContentQueryKey = (
  projectId: ArtifactsVisualContentPathParams["projectId"] | undefined,
  artifactId: ArtifactsVisualContentPathParams["artifactId"] | undefined
) =>
  [
    {
      url: "/api/v1/projects/:projectId/artifacts/:artifactId/content",
      params: { projectId: projectId, artifactId: artifactId },
    },
  ] as const

export type ArtifactsVisualContentQueryKey = ReturnType<
  typeof artifactsVisualContentQueryKey
>

export function artifactsVisualContentQueryOptions(
  projectId: ArtifactsVisualContentPathParams["projectId"] | undefined,
  artifactId: ArtifactsVisualContentPathParams["artifactId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = artifactsVisualContentQueryKey(projectId, artifactId)
  return queryOptions<
    ArtifactsVisualContentQueryResponse,
    ResponseErrorConfig<ArtifactsVisualContent404>,
    ArtifactsVisualContentQueryResponse,
    typeof queryKey
  >({
    enabled: !!(projectId && artifactId),
    queryKey,
    queryFn: async ({ signal }) => {
      return artifactsVisualContent(projectId!, artifactId!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/projects/:projectId/artifacts/:artifactId/content}
 */
export function useArtifactsVisualContent<
  TData = ArtifactsVisualContentQueryResponse,
  TQueryData = ArtifactsVisualContentQueryResponse,
  TQueryKey extends QueryKey = ArtifactsVisualContentQueryKey,
>(
  projectId: ArtifactsVisualContentPathParams["projectId"] | undefined,
  artifactId: ArtifactsVisualContentPathParams["artifactId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ArtifactsVisualContentQueryResponse,
        ResponseErrorConfig<ArtifactsVisualContent404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    artifactsVisualContentQueryKey(projectId, artifactId)

  const query = useQuery(
    {
      ...artifactsVisualContentQueryOptions(projectId, artifactId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ArtifactsVisualContent404>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
