/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  DeleteApiV1AdmissionRulesRuleidMutationResponse,
  DeleteApiV1AdmissionRulesRuleidPathParams,
} from "../types/DeleteApiV1AdmissionRulesRuleid"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { deleteApiV1AdmissionRulesRuleid } from "../clients/deleteApiV1AdmissionRulesRuleid"

export const deleteApiV1AdmissionRulesRuleidMutationKey = () =>
  [{ url: "/api/v1/admission-rules/:ruleId" }] as const

export type DeleteApiV1AdmissionRulesRuleidMutationKey = ReturnType<
  typeof deleteApiV1AdmissionRulesRuleidMutationKey
>

export function deleteApiV1AdmissionRulesRuleidMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteApiV1AdmissionRulesRuleidMutationKey()
  return mutationOptions<
    DeleteApiV1AdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1AdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ruleId }) => {
      return deleteApiV1AdmissionRulesRuleid(ruleId, config)
    },
  })
}

/**
 * {@link /api/v1/admission-rules/:ruleId}
 */
export function useDeleteApiV1AdmissionRulesRuleid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1AdmissionRulesRuleidMutationResponse,
      ResponseErrorConfig<Error>,
      { ruleId: DeleteApiV1AdmissionRulesRuleidPathParams["ruleId"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1AdmissionRulesRuleidMutationKey()

  const baseOptions = deleteApiV1AdmissionRulesRuleidMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteApiV1AdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1AdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >

  return useMutation<
    DeleteApiV1AdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1AdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DeleteApiV1AdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1AdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >
}
