/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse,
  DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams,
} from "../types/DeleteApiV1ProjectsProjectidScheduledJobsJobid"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { deleteApiV1ProjectsProjectidScheduledJobsJobid } from "../clients/deleteApiV1ProjectsProjectidScheduledJobsJobid"

export const deleteApiV1ProjectsProjectidScheduledJobsJobidMutationKey = () =>
  [{ url: "/api/v1/projects/:projectId/scheduled-jobs/:jobId" }] as const

export type DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationKey =
  ReturnType<typeof deleteApiV1ProjectsProjectidScheduledJobsJobidMutationKey>

export function deleteApiV1ProjectsProjectidScheduledJobsJobidMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey =
    deleteApiV1ProjectsProjectidScheduledJobsJobidMutationKey()
  return mutationOptions<
    DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse,
    ResponseErrorConfig<Error>,
    {
      projectId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["projectId"]
      jobId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["jobId"]
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ projectId, jobId }) => {
      return deleteApiV1ProjectsProjectidScheduledJobsJobid(
        projectId,
        jobId,
        config
      )
    },
  })
}

/**
 * {@link /api/v1/projects/:projectId/scheduled-jobs/:jobId}
 */
export function useDeleteApiV1ProjectsProjectidScheduledJobsJobid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse,
      ResponseErrorConfig<Error>,
      {
        projectId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["projectId"]
        jobId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["jobId"]
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteApiV1ProjectsProjectidScheduledJobsJobidMutationKey()

  const baseOptions =
    deleteApiV1ProjectsProjectidScheduledJobsJobidMutationOptions(
      config
    ) as UseMutationOptions<
      DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse,
      ResponseErrorConfig<Error>,
      {
        projectId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["projectId"]
        jobId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["jobId"]
      },
      TContext
    >

  return useMutation<
    DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse,
    ResponseErrorConfig<Error>,
    {
      projectId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["projectId"]
      jobId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["jobId"]
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DeleteApiV1ProjectsProjectidScheduledJobsJobidMutationResponse,
    ResponseErrorConfig<Error>,
    {
      projectId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["projectId"]
      jobId: DeleteApiV1ProjectsProjectidScheduledJobsJobidPathParams["jobId"]
    },
    TContext
  >
}
