/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  DeleteApiV1IntegrationAdmissionRulesRuleidMutationResponse,
  DeleteApiV1IntegrationAdmissionRulesRuleidPathParams,
} from "../types/DeleteApiV1IntegrationAdmissionRulesRuleid"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { deleteApiV1IntegrationAdmissionRulesRuleid } from "../clients/deleteApiV1IntegrationAdmissionRulesRuleid"

export const deleteApiV1IntegrationAdmissionRulesRuleidMutationKey = () =>
  [{ url: "/api/v1/integration/admission-rules/:ruleId" }] as const

export type DeleteApiV1IntegrationAdmissionRulesRuleidMutationKey = ReturnType<
  typeof deleteApiV1IntegrationAdmissionRulesRuleidMutationKey
>

export function deleteApiV1IntegrationAdmissionRulesRuleidMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteApiV1IntegrationAdmissionRulesRuleidMutationKey()
  return mutationOptions<
    DeleteApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ruleId }) => {
      return deleteApiV1IntegrationAdmissionRulesRuleid(ruleId, config)
    },
  })
}

/**
 * @summary Deletes a rule (idempotent).
 * {@link /api/v1/integration/admission-rules/:ruleId}
 */
export function useDeleteApiV1IntegrationAdmissionRulesRuleid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1IntegrationAdmissionRulesRuleidMutationResponse,
      ResponseErrorConfig<Error>,
      {
        ruleId: DeleteApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteApiV1IntegrationAdmissionRulesRuleidMutationKey()

  const baseOptions = deleteApiV1IntegrationAdmissionRulesRuleidMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >

  return useMutation<
    DeleteApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DeleteApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<Error>,
    { ruleId: DeleteApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"] },
    TContext
  >
}
