/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1ProceduresRunsRunidTraceQueryResponse,
  GetApiV1ProceduresRunsRunidTracePathParams,
  GetApiV1ProceduresRunsRunidTrace404,
} from "../types/GetApiV1ProceduresRunsRunidTrace"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1ProceduresRunsRunidTrace } from "../clients/getApiV1ProceduresRunsRunidTrace"

export const getApiV1ProceduresRunsRunidTraceQueryKey = (
  runId: GetApiV1ProceduresRunsRunidTracePathParams["runId"] | undefined
) =>
  [
    { url: "/api/v1/procedures/runs/:runId/trace", params: { runId: runId } },
  ] as const

export type GetApiV1ProceduresRunsRunidTraceQueryKey = ReturnType<
  typeof getApiV1ProceduresRunsRunidTraceQueryKey
>

export function getApiV1ProceduresRunsRunidTraceQueryOptions(
  runId: GetApiV1ProceduresRunsRunidTracePathParams["runId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1ProceduresRunsRunidTraceQueryKey(runId)
  return queryOptions<
    GetApiV1ProceduresRunsRunidTraceQueryResponse,
    ResponseErrorConfig<GetApiV1ProceduresRunsRunidTrace404>,
    GetApiV1ProceduresRunsRunidTraceQueryResponse,
    typeof queryKey
  >({
    enabled: !!runId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProceduresRunsRunidTrace(runId!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Returns the planned-vs-observed trace for one procedure-pinned
 * run — the timeline Studio's Replay panel renders. 404 when the
 * run has not been admitted against a procedure (no seeded trace).
 * {@link /api/v1/procedures/runs/:runId/trace}
 */
export function useGetApiV1ProceduresRunsRunidTrace<
  TData = GetApiV1ProceduresRunsRunidTraceQueryResponse,
  TQueryData = GetApiV1ProceduresRunsRunidTraceQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProceduresRunsRunidTraceQueryKey,
>(
  runId: GetApiV1ProceduresRunsRunidTracePathParams["runId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProceduresRunsRunidTraceQueryResponse,
        ResponseErrorConfig<GetApiV1ProceduresRunsRunidTrace404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1ProceduresRunsRunidTraceQueryKey(runId)

  const query = useQuery(
    {
      ...getApiV1ProceduresRunsRunidTraceQueryOptions(runId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1ProceduresRunsRunidTrace404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
