/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1ProceduresVersionsVersionidQueryResponse,
  GetApiV1ProceduresVersionsVersionidPathParams,
  GetApiV1ProceduresVersionsVersionid404,
} from "../types/GetApiV1ProceduresVersionsVersionid"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1ProceduresVersionsVersionid } from "../clients/getApiV1ProceduresVersionsVersionid"

export const getApiV1ProceduresVersionsVersionidSuspenseQueryKey = (
  versionId:
    GetApiV1ProceduresVersionsVersionidPathParams["versionId"] | undefined
) =>
  [
    {
      url: "/api/v1/procedures/versions/:versionId",
      params: { versionId: versionId },
    },
  ] as const

export type GetApiV1ProceduresVersionsVersionidSuspenseQueryKey = ReturnType<
  typeof getApiV1ProceduresVersionsVersionidSuspenseQueryKey
>

export function getApiV1ProceduresVersionsVersionidSuspenseQueryOptions(
  versionId: GetApiV1ProceduresVersionsVersionidPathParams["versionId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey =
    getApiV1ProceduresVersionsVersionidSuspenseQueryKey(versionId)
  return queryOptions<
    GetApiV1ProceduresVersionsVersionidQueryResponse,
    ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>,
    GetApiV1ProceduresVersionsVersionidQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProceduresVersionsVersionid(versionId, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Reads one compiled version by its content-addressed id.
 * {@link /api/v1/procedures/versions/:versionId}
 */
export function useGetApiV1ProceduresVersionsVersionidSuspense<
  TData = GetApiV1ProceduresVersionsVersionidQueryResponse,
  TQueryKey extends QueryKey =
    GetApiV1ProceduresVersionsVersionidSuspenseQueryKey,
>(
  versionId: GetApiV1ProceduresVersionsVersionidPathParams["versionId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1ProceduresVersionsVersionidQueryResponse,
        ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ProceduresVersionsVersionidSuspenseQueryKey(versionId)

  const query = useSuspenseQuery(
    {
      ...getApiV1ProceduresVersionsVersionidSuspenseQueryOptions(
        versionId,
        config
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
