/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1ProceduresVersionsVersionidQueryResponse,
  GetApiV1ProceduresVersionsVersionidPathParams,
  GetApiV1ProceduresVersionsVersionid404,
} from "../types/GetApiV1ProceduresVersionsVersionid"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1ProceduresVersionsVersionid } from "../clients/getApiV1ProceduresVersionsVersionid"

export const getApiV1ProceduresVersionsVersionidQueryKey = (
  versionId:
    GetApiV1ProceduresVersionsVersionidPathParams["versionId"] | undefined
) =>
  [
    {
      url: "/api/v1/procedures/versions/:versionId",
      params: { versionId: versionId },
    },
  ] as const

export type GetApiV1ProceduresVersionsVersionidQueryKey = ReturnType<
  typeof getApiV1ProceduresVersionsVersionidQueryKey
>

export function getApiV1ProceduresVersionsVersionidQueryOptions(
  versionId:
    GetApiV1ProceduresVersionsVersionidPathParams["versionId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1ProceduresVersionsVersionidQueryKey(versionId)
  return queryOptions<
    GetApiV1ProceduresVersionsVersionidQueryResponse,
    ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>,
    GetApiV1ProceduresVersionsVersionidQueryResponse,
    typeof queryKey
  >({
    enabled: !!versionId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProceduresVersionsVersionid(versionId!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Reads one compiled version by its content-addressed id.
 * {@link /api/v1/procedures/versions/:versionId}
 */
export function useGetApiV1ProceduresVersionsVersionid<
  TData = GetApiV1ProceduresVersionsVersionidQueryResponse,
  TQueryData = GetApiV1ProceduresVersionsVersionidQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProceduresVersionsVersionidQueryKey,
>(
  versionId:
    GetApiV1ProceduresVersionsVersionidPathParams["versionId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProceduresVersionsVersionidQueryResponse,
        ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ProceduresVersionsVersionidQueryKey(versionId)

  const query = useQuery(
    {
      ...getApiV1ProceduresVersionsVersionidQueryOptions(versionId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
