/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1AuthOidcProviderStartQueryResponse,
  GetApiV1AuthOidcProviderStartPathParams,
  GetApiV1AuthOidcProviderStartQueryParams,
  GetApiV1AuthOidcProviderStart404,
} from "../types/GetApiV1AuthOidcProviderStart"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1AuthOidcProviderStart } from "../clients/getApiV1AuthOidcProviderStart"

export const getApiV1AuthOidcProviderStartSuspenseQueryKey = (
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"] | undefined,
  params?: GetApiV1AuthOidcProviderStartQueryParams
) =>
  [
    {
      url: "/api/v1/auth/oidc/:provider/start",
      params: { provider: provider },
    },
    ...(params ? [params] : []),
  ] as const

export type GetApiV1AuthOidcProviderStartSuspenseQueryKey = ReturnType<
  typeof getApiV1AuthOidcProviderStartSuspenseQueryKey
>

export function getApiV1AuthOidcProviderStartSuspenseQueryOptions(
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"],
  params?: GetApiV1AuthOidcProviderStartQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1AuthOidcProviderStartSuspenseQueryKey(
    provider,
    params
  )
  return queryOptions<
    GetApiV1AuthOidcProviderStartQueryResponse,
    ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>,
    GetApiV1AuthOidcProviderStartQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1AuthOidcProviderStart(provider, params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/auth/oidc/:provider/start}
 */
export function useGetApiV1AuthOidcProviderStartSuspense<
  TData = GetApiV1AuthOidcProviderStartQueryResponse,
  TQueryKey extends QueryKey = GetApiV1AuthOidcProviderStartSuspenseQueryKey,
>(
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"],
  params?: GetApiV1AuthOidcProviderStartQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1AuthOidcProviderStartQueryResponse,
        ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1AuthOidcProviderStartSuspenseQueryKey(provider, params)

  const query = useSuspenseQuery(
    {
      ...getApiV1AuthOidcProviderStartSuspenseQueryOptions(
        provider,
        params,
        config
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
