/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1AuthOidcCallbackQueryResponse,
  GetApiV1AuthOidcCallbackQueryParams,
} from "../types/GetApiV1AuthOidcCallback"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1AuthOidcCallback } from "../clients/getApiV1AuthOidcCallback"

export const getApiV1AuthOidcCallbackSuspenseQueryKey = (
  params?: GetApiV1AuthOidcCallbackQueryParams
) =>
  [{ url: "/api/v1/auth/oidc/callback" }, ...(params ? [params] : [])] as const

export type GetApiV1AuthOidcCallbackSuspenseQueryKey = ReturnType<
  typeof getApiV1AuthOidcCallbackSuspenseQueryKey
>

export function getApiV1AuthOidcCallbackSuspenseQueryOptions(
  params?: GetApiV1AuthOidcCallbackQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1AuthOidcCallbackSuspenseQueryKey(params)
  return queryOptions<
    GetApiV1AuthOidcCallbackQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1AuthOidcCallbackQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1AuthOidcCallback(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/auth/oidc/callback}
 */
export function useGetApiV1AuthOidcCallbackSuspense<
  TData = GetApiV1AuthOidcCallbackQueryResponse,
  TQueryKey extends QueryKey = GetApiV1AuthOidcCallbackSuspenseQueryKey,
>(
  params?: GetApiV1AuthOidcCallbackQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1AuthOidcCallbackQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1AuthOidcCallbackSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getApiV1AuthOidcCallbackSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
