/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiV1InboxCatalogQueryResponse, GetApiV1InboxCatalogQueryParams, GetApiV1InboxCatalog404 } from "../types/GetApiV1InboxCatalog";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getApiV1InboxCatalog } from "../clients/getApiV1InboxCatalog";

export const getApiV1InboxCatalogQueryKey = (params?: GetApiV1InboxCatalogQueryParams) => [{ url: '/api/v1/inbox/catalog' }, ...(params ? [params] : [])] as const

export type GetApiV1InboxCatalogQueryKey = ReturnType<typeof getApiV1InboxCatalogQueryKey>

export function getApiV1InboxCatalogQueryOptions(params?: GetApiV1InboxCatalogQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1InboxCatalogQueryKey(params)
        return queryOptions<GetApiV1InboxCatalogQueryResponse, ResponseErrorConfig<GetApiV1InboxCatalog404>, GetApiV1InboxCatalogQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiV1InboxCatalog(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/v1/inbox/catalog}
 */
export function useGetApiV1InboxCatalog<TData = GetApiV1InboxCatalogQueryResponse, TQueryData = GetApiV1InboxCatalogQueryResponse, TQueryKey extends QueryKey = GetApiV1InboxCatalogQueryKey>(params?: GetApiV1InboxCatalogQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1InboxCatalogQueryResponse, ResponseErrorConfig<GetApiV1InboxCatalog404>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiV1InboxCatalogQueryKey(params)
         

         const query = useQuery({
          ...getApiV1InboxCatalogQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetApiV1InboxCatalog404>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}