/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type { GetApiV1ComputeQueryResponse } from "../types/GetApiV1Compute"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1Compute } from "../clients/getApiV1Compute"

export const getApiV1ComputeSuspenseQueryKey = () =>
  [{ url: "/api/v1/compute" }] as const

export type GetApiV1ComputeSuspenseQueryKey = ReturnType<
  typeof getApiV1ComputeSuspenseQueryKey
>

export function getApiV1ComputeSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1ComputeSuspenseQueryKey()
  return queryOptions<
    GetApiV1ComputeQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1ComputeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Compute({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /api/v1/compute}
 */
export function useGetApiV1ComputeSuspense<
  TData = GetApiV1ComputeQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ComputeSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1ComputeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1ComputeSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getApiV1ComputeSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
