/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type { GetApiV1SettingsQueryResponse } from "../types/GetApiV1Settings"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1Settings } from "../clients/getApiV1Settings"

export const getApiV1SettingsSuspenseQueryKey = () =>
  [{ url: "/api/v1/settings" }] as const

export type GetApiV1SettingsSuspenseQueryKey = ReturnType<
  typeof getApiV1SettingsSuspenseQueryKey
>

export function getApiV1SettingsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1SettingsSuspenseQueryKey()
  return queryOptions<
    GetApiV1SettingsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1SettingsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Settings({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /api/v1/settings}
 */
export function useGetApiV1SettingsSuspense<
  TData = GetApiV1SettingsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1SettingsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1SettingsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1SettingsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getApiV1SettingsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
