/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1ProjectsQueryResponse,
  GetApiV1ProjectsQueryParams,
} from "../types/GetApiV1Projects"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1Projects } from "../clients/getApiV1Projects"

export const getApiV1ProjectsQueryKey = (params: GetApiV1ProjectsQueryParams) =>
  [{ url: "/api/v1/projects" }, ...(params ? [params] : [])] as const

export type GetApiV1ProjectsQueryKey = ReturnType<
  typeof getApiV1ProjectsQueryKey
>

export function getApiV1ProjectsQueryOptions(
  params: GetApiV1ProjectsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1ProjectsQueryKey(params)
  return queryOptions<
    GetApiV1ProjectsQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1ProjectsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Projects(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/projects}
 */
export function useGetApiV1Projects<
  TData = GetApiV1ProjectsQueryResponse,
  TQueryData = GetApiV1ProjectsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProjectsQueryKey,
>(
  params: GetApiV1ProjectsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProjectsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getApiV1ProjectsQueryKey(params)

  const query = useQuery(
    {
      ...getApiV1ProjectsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
