/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1ProceduresProjectidProcedurekeyQueryResponse,
  GetApiV1ProceduresProjectidProcedurekeyPathParams,
  GetApiV1ProceduresProjectidProcedurekey404,
} from "../types/GetApiV1ProceduresProjectidProcedurekey"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1ProceduresProjectidProcedurekey } from "../clients/getApiV1ProceduresProjectidProcedurekey"

export const getApiV1ProceduresProjectidProcedurekeyQueryKey = (
  projectId:
    GetApiV1ProceduresProjectidProcedurekeyPathParams["projectId"] | undefined,
  procedureKey:
    | GetApiV1ProceduresProjectidProcedurekeyPathParams["procedureKey"]
    | undefined
) =>
  [
    {
      url: "/api/v1/procedures/:projectId/:procedureKey",
      params: { projectId: projectId, procedureKey: procedureKey },
    },
  ] as const

export type GetApiV1ProceduresProjectidProcedurekeyQueryKey = ReturnType<
  typeof getApiV1ProceduresProjectidProcedurekeyQueryKey
>

export function getApiV1ProceduresProjectidProcedurekeyQueryOptions(
  projectId:
    GetApiV1ProceduresProjectidProcedurekeyPathParams["projectId"] | undefined,
  procedureKey:
    | GetApiV1ProceduresProjectidProcedurekeyPathParams["procedureKey"]
    | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1ProceduresProjectidProcedurekeyQueryKey(
    projectId,
    procedureKey
  )
  return queryOptions<
    GetApiV1ProceduresProjectidProcedurekeyQueryResponse,
    ResponseErrorConfig<GetApiV1ProceduresProjectidProcedurekey404>,
    GetApiV1ProceduresProjectidProcedurekeyQueryResponse,
    typeof queryKey
  >({
    enabled: !!(projectId && procedureKey),
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProceduresProjectidProcedurekey(
        projectId!,
        procedureKey!,
        { ...config, signal: config.signal ?? signal }
      )
    },
  })
}

/**
 * @summary Returns the current compiled version of a procedure — the one the
 * attempt pin points at. 404 when no pin has been published yet.
 * {@link /api/v1/procedures/:projectId/:procedureKey}
 */
export function useGetApiV1ProceduresProjectidProcedurekey<
  TData = GetApiV1ProceduresProjectidProcedurekeyQueryResponse,
  TQueryData = GetApiV1ProceduresProjectidProcedurekeyQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProceduresProjectidProcedurekeyQueryKey,
>(
  projectId:
    GetApiV1ProceduresProjectidProcedurekeyPathParams["projectId"] | undefined,
  procedureKey:
    | GetApiV1ProceduresProjectidProcedurekeyPathParams["procedureKey"]
    | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProceduresProjectidProcedurekeyQueryResponse,
        ResponseErrorConfig<GetApiV1ProceduresProjectidProcedurekey404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ProceduresProjectidProcedurekeyQueryKey(projectId, procedureKey)

  const query = useQuery(
    {
      ...getApiV1ProceduresProjectidProcedurekeyQueryOptions(
        projectId,
        procedureKey,
        config
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1ProceduresProjectidProcedurekey404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
