/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1IntegrationAdmissionRulesQueryResponse,
  GetApiV1IntegrationAdmissionRulesQueryParams,
} from "../types/GetApiV1IntegrationAdmissionRules"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1IntegrationAdmissionRules } from "../clients/getApiV1IntegrationAdmissionRules"

export const getApiV1IntegrationAdmissionRulesSuspenseQueryKey = (
  params?: GetApiV1IntegrationAdmissionRulesQueryParams
) =>
  [
    { url: "/api/v1/integration/admission-rules" },
    ...(params ? [params] : []),
  ] as const

export type GetApiV1IntegrationAdmissionRulesSuspenseQueryKey = ReturnType<
  typeof getApiV1IntegrationAdmissionRulesSuspenseQueryKey
>

export function getApiV1IntegrationAdmissionRulesSuspenseQueryOptions(
  params?: GetApiV1IntegrationAdmissionRulesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1IntegrationAdmissionRulesSuspenseQueryKey(params)
  return queryOptions<
    GetApiV1IntegrationAdmissionRulesQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1IntegrationAdmissionRulesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1IntegrationAdmissionRules(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Lists rules, optionally per project.
 * {@link /api/v1/integration/admission-rules}
 */
export function useGetApiV1IntegrationAdmissionRulesSuspense<
  TData = GetApiV1IntegrationAdmissionRulesQueryResponse,
  TQueryKey extends QueryKey =
    GetApiV1IntegrationAdmissionRulesSuspenseQueryKey,
>(
  params?: GetApiV1IntegrationAdmissionRulesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1IntegrationAdmissionRulesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1IntegrationAdmissionRulesSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getApiV1IntegrationAdmissionRulesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
