/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type { GetApiV1ProxyKeysQueryResponse } from "../types/GetApiV1ProxyKeys"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1ProxyKeys } from "../clients/getApiV1ProxyKeys"

export const getApiV1ProxyKeysQueryKey = () =>
  [{ url: "/api/v1/proxy/keys" }] as const

export type GetApiV1ProxyKeysQueryKey = ReturnType<
  typeof getApiV1ProxyKeysQueryKey
>

export function getApiV1ProxyKeysQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1ProxyKeysQueryKey()
  return queryOptions<
    GetApiV1ProxyKeysQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1ProxyKeysQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProxyKeys({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /api/v1/proxy/keys}
 */
export function useGetApiV1ProxyKeys<
  TData = GetApiV1ProxyKeysQueryResponse,
  TQueryData = GetApiV1ProxyKeysQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProxyKeysQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProxyKeysQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getApiV1ProxyKeysQueryKey()

  const query = useQuery(
    {
      ...getApiV1ProxyKeysQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
