/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type { GetProfilesQueryResponse } from "../types/GetProfiles"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getProfiles } from "../clients/getProfiles"

export const getProfilesSuspenseQueryKey = () => [{ url: "/profiles" }] as const

export type GetProfilesSuspenseQueryKey = ReturnType<
  typeof getProfilesSuspenseQueryKey
>

export function getProfilesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getProfilesSuspenseQueryKey()
  return queryOptions<
    GetProfilesQueryResponse,
    ResponseErrorConfig<Error>,
    GetProfilesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProfiles({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /profiles}
 */
export function useGetProfilesSuspense<
  TData = GetProfilesQueryResponse,
  TQueryKey extends QueryKey = GetProfilesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProfilesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getProfilesSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getProfilesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
