/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiV1ChatSlashQueryResponse } from "../types/GetApiV1ChatSlash";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getApiV1ChatSlash } from "../clients/getApiV1ChatSlash";

export const getApiV1ChatSlashQueryKey = () => [{ url: '/api/v1/chat/slash' }] as const

export type GetApiV1ChatSlashQueryKey = ReturnType<typeof getApiV1ChatSlashQueryKey>

export function getApiV1ChatSlashQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1ChatSlashQueryKey()
        return queryOptions<GetApiV1ChatSlashQueryResponse, ResponseErrorConfig<Error>, GetApiV1ChatSlashQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiV1ChatSlash({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/v1/chat/slash}
 */
export function useGetApiV1ChatSlash<TData = GetApiV1ChatSlashQueryResponse, TQueryData = GetApiV1ChatSlashQueryResponse, TQueryKey extends QueryKey = GetApiV1ChatSlashQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1ChatSlashQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiV1ChatSlashQueryKey()
         

         const query = useQuery({
          ...getApiV1ChatSlashQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}