/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1SourcesQueryResponse,
  GetApiV1SourcesQueryParams,
} from "../types/GetApiV1Sources"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1Sources } from "../clients/getApiV1Sources"

export const getApiV1SourcesQueryKey = (params?: GetApiV1SourcesQueryParams) =>
  [{ url: "/api/v1/sources" }, ...(params ? [params] : [])] as const

export type GetApiV1SourcesQueryKey = ReturnType<typeof getApiV1SourcesQueryKey>

export function getApiV1SourcesQueryOptions(
  params?: GetApiV1SourcesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1SourcesQueryKey(params)
  return queryOptions<
    GetApiV1SourcesQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1SourcesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Sources(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/sources}
 */
export function useGetApiV1Sources<
  TData = GetApiV1SourcesQueryResponse,
  TQueryData = GetApiV1SourcesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1SourcesQueryKey,
>(
  params?: GetApiV1SourcesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1SourcesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getApiV1SourcesQueryKey(params)

  const query = useQuery(
    {
      ...getApiV1SourcesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
