/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1UsersQueryResponse,
  GetApiV1UsersQueryParams,
  GetApiV1Users400,
} from "../types/GetApiV1Users"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1Users } from "../clients/getApiV1Users"

export const getApiV1UsersQueryKey = (params?: GetApiV1UsersQueryParams) =>
  [{ url: "/api/v1/users" }, ...(params ? [params] : [])] as const

export type GetApiV1UsersQueryKey = ReturnType<typeof getApiV1UsersQueryKey>

export function getApiV1UsersQueryOptions(
  params?: GetApiV1UsersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1UsersQueryKey(params)
  return queryOptions<
    GetApiV1UsersQueryResponse,
    ResponseErrorConfig<GetApiV1Users400>,
    GetApiV1UsersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Users(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Lists user accounts (issue #45 / F13 — read side of the identity admin).
 * Permission `identity:read`; returns a paged
 * `{ items, total }` envelope of UserAccountView.
 * Optional `emailContains` is a case-insensitive substring filter.
 * {@link /api/v1/users}
 */
export function useGetApiV1Users<
  TData = GetApiV1UsersQueryResponse,
  TQueryData = GetApiV1UsersQueryResponse,
  TQueryKey extends QueryKey = GetApiV1UsersQueryKey,
>(
  params?: GetApiV1UsersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1UsersQueryResponse,
        ResponseErrorConfig<GetApiV1Users400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getApiV1UsersQueryKey(params)

  const query = useQuery(
    {
      ...getApiV1UsersQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetApiV1Users400>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
