/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
  GetApiV1IntegrationAdmissionRulesRuleidPathParams,
  GetApiV1IntegrationAdmissionRulesRuleid404,
} from "../types/GetApiV1IntegrationAdmissionRulesRuleid"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1IntegrationAdmissionRulesRuleid } from "../clients/getApiV1IntegrationAdmissionRulesRuleid"

export const getApiV1IntegrationAdmissionRulesRuleidSuspenseQueryKey = (
  ruleId:
    GetApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"] | undefined
) =>
  [
    {
      url: "/api/v1/integration/admission-rules/:ruleId",
      params: { ruleId: ruleId },
    },
  ] as const

export type GetApiV1IntegrationAdmissionRulesRuleidSuspenseQueryKey =
  ReturnType<typeof getApiV1IntegrationAdmissionRulesRuleidSuspenseQueryKey>

export function getApiV1IntegrationAdmissionRulesRuleidSuspenseQueryOptions(
  ruleId: GetApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey =
    getApiV1IntegrationAdmissionRulesRuleidSuspenseQueryKey(ruleId)
  return queryOptions<
    GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
    ResponseErrorConfig<GetApiV1IntegrationAdmissionRulesRuleid404>,
    GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1IntegrationAdmissionRulesRuleid(ruleId, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Reads one rule.
 * {@link /api/v1/integration/admission-rules/:ruleId}
 */
export function useGetApiV1IntegrationAdmissionRulesRuleidSuspense<
  TData = GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
  TQueryKey extends QueryKey =
    GetApiV1IntegrationAdmissionRulesRuleidSuspenseQueryKey,
>(
  ruleId: GetApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
        ResponseErrorConfig<GetApiV1IntegrationAdmissionRulesRuleid404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1IntegrationAdmissionRulesRuleidSuspenseQueryKey(ruleId)

  const query = useSuspenseQuery(
    {
      ...getApiV1IntegrationAdmissionRulesRuleidSuspenseQueryOptions(
        ruleId,
        config
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1IntegrationAdmissionRulesRuleid404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
