/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1GrantsQueryResponse,
  GetApiV1GrantsQueryParams,
  GetApiV1Grants400,
} from "../types/GetApiV1Grants"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1Grants } from "../clients/getApiV1Grants"

export const getApiV1GrantsQueryKey = (params?: GetApiV1GrantsQueryParams) =>
  [{ url: "/api/v1/grants" }, ...(params ? [params] : [])] as const

export type GetApiV1GrantsQueryKey = ReturnType<typeof getApiV1GrantsQueryKey>

export function getApiV1GrantsQueryOptions(
  params?: GetApiV1GrantsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1GrantsQueryKey(params)
  return queryOptions<
    GetApiV1GrantsQueryResponse,
    ResponseErrorConfig<GetApiV1Grants400>,
    GetApiV1GrantsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Grants(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/grants}
 */
export function useGetApiV1Grants<
  TData = GetApiV1GrantsQueryResponse,
  TQueryData = GetApiV1GrantsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1GrantsQueryKey,
>(
  params?: GetApiV1GrantsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1GrantsQueryResponse,
        ResponseErrorConfig<GetApiV1Grants400>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getApiV1GrantsQueryKey(params)

  const query = useQuery(
    {
      ...getApiV1GrantsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetApiV1Grants400>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
