/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1AuthOidcProviderStartQueryResponse,
  GetApiV1AuthOidcProviderStartPathParams,
  GetApiV1AuthOidcProviderStartQueryParams,
  GetApiV1AuthOidcProviderStart404,
} from "../types/GetApiV1AuthOidcProviderStart"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1AuthOidcProviderStart } from "../clients/getApiV1AuthOidcProviderStart"

export const getApiV1AuthOidcProviderStartQueryKey = (
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"] | undefined,
  params?: GetApiV1AuthOidcProviderStartQueryParams
) =>
  [
    {
      url: "/api/v1/auth/oidc/:provider/start",
      params: { provider: provider },
    },
    ...(params ? [params] : []),
  ] as const

export type GetApiV1AuthOidcProviderStartQueryKey = ReturnType<
  typeof getApiV1AuthOidcProviderStartQueryKey
>

export function getApiV1AuthOidcProviderStartQueryOptions(
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"] | undefined,
  params?: GetApiV1AuthOidcProviderStartQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1AuthOidcProviderStartQueryKey(provider, params)
  return queryOptions<
    GetApiV1AuthOidcProviderStartQueryResponse,
    ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>,
    GetApiV1AuthOidcProviderStartQueryResponse,
    typeof queryKey
  >({
    enabled: !!provider,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1AuthOidcProviderStart(provider!, params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/auth/oidc/:provider/start}
 */
export function useGetApiV1AuthOidcProviderStart<
  TData = GetApiV1AuthOidcProviderStartQueryResponse,
  TQueryData = GetApiV1AuthOidcProviderStartQueryResponse,
  TQueryKey extends QueryKey = GetApiV1AuthOidcProviderStartQueryKey,
>(
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"] | undefined,
  params?: GetApiV1AuthOidcProviderStartQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1AuthOidcProviderStartQueryResponse,
        ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1AuthOidcProviderStartQueryKey(provider, params)

  const query = useQuery(
    {
      ...getApiV1AuthOidcProviderStartQueryOptions(provider, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
