/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1InboxQueryResponse,
  GetApiV1InboxQueryParams,
} from "../types/GetApiV1Inbox"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1Inbox } from "../clients/getApiV1Inbox"

export const getApiV1InboxSuspenseQueryKey = (
  params?: GetApiV1InboxQueryParams
) => [{ url: "/api/v1/inbox" }, ...(params ? [params] : [])] as const

export type GetApiV1InboxSuspenseQueryKey = ReturnType<
  typeof getApiV1InboxSuspenseQueryKey
>

export function getApiV1InboxSuspenseQueryOptions(
  params?: GetApiV1InboxQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1InboxSuspenseQueryKey(params)
  return queryOptions<
    GetApiV1InboxQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1InboxQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Inbox(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/inbox}
 */
export function useGetApiV1InboxSuspense<
  TData = GetApiV1InboxQueryResponse,
  TQueryKey extends QueryKey = GetApiV1InboxSuspenseQueryKey,
>(
  params?: GetApiV1InboxQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1InboxQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1InboxSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getApiV1InboxSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
