/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiV1AdmissionRulesQueryResponse, GetApiV1AdmissionRulesQueryParams } from "../types/GetApiV1AdmissionRules";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getApiV1AdmissionRules } from "../clients/getApiV1AdmissionRules";

export const getApiV1AdmissionRulesQueryKey = (params?: GetApiV1AdmissionRulesQueryParams) => [{ url: '/api/v1/admission-rules' }, ...(params ? [params] : [])] as const

export type GetApiV1AdmissionRulesQueryKey = ReturnType<typeof getApiV1AdmissionRulesQueryKey>

export function getApiV1AdmissionRulesQueryOptions(params?: GetApiV1AdmissionRulesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1AdmissionRulesQueryKey(params)
        return queryOptions<GetApiV1AdmissionRulesQueryResponse, ResponseErrorConfig<Error>, GetApiV1AdmissionRulesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiV1AdmissionRules(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/v1/admission-rules}
 */
export function useGetApiV1AdmissionRules<TData = GetApiV1AdmissionRulesQueryResponse, TQueryData = GetApiV1AdmissionRulesQueryResponse, TQueryKey extends QueryKey = GetApiV1AdmissionRulesQueryKey>(params?: GetApiV1AdmissionRulesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1AdmissionRulesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiV1AdmissionRulesQueryKey(params)
         

         const query = useQuery({
          ...getApiV1AdmissionRulesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}