/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type { GetApiV1KnowledgeSearchQueryResponse } from "../types/GetApiV1KnowledgeSearch"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { getApiV1KnowledgeSearch } from "../clients/getApiV1KnowledgeSearch"

export const getApiV1KnowledgeSearchQueryKey = () =>
  [{ url: "/api/v1/knowledge/search" }] as const

export type GetApiV1KnowledgeSearchQueryKey = ReturnType<
  typeof getApiV1KnowledgeSearchQueryKey
>

export function getApiV1KnowledgeSearchQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1KnowledgeSearchQueryKey()
  return queryOptions<
    GetApiV1KnowledgeSearchQueryResponse,
    ResponseErrorConfig<Error>,
    GetApiV1KnowledgeSearchQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1KnowledgeSearch({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /api/v1/knowledge/search}
 */
export function useGetApiV1KnowledgeSearch<
  TData = GetApiV1KnowledgeSearchQueryResponse,
  TQueryData = GetApiV1KnowledgeSearchQueryResponse,
  TQueryKey extends QueryKey = GetApiV1KnowledgeSearchQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1KnowledgeSearchQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1KnowledgeSearchQueryKey()

  const query = useQuery(
    {
      ...getApiV1KnowledgeSearchQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
