/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiV1ProjectsQueryResponse, GetApiV1ProjectsQueryParams } from "../types/GetApiV1Projects";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1Projects } from "../clients/getApiV1Projects";

export const getApiV1ProjectsSuspenseQueryKey = (params: GetApiV1ProjectsQueryParams) => [{ url: '/api/v1/projects' }, ...(params ? [params] : [])] as const

export type GetApiV1ProjectsSuspenseQueryKey = ReturnType<typeof getApiV1ProjectsSuspenseQueryKey>

export function getApiV1ProjectsSuspenseQueryOptions(params: GetApiV1ProjectsQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1ProjectsSuspenseQueryKey(params)
        return queryOptions<GetApiV1ProjectsQueryResponse, ResponseErrorConfig<Error>, GetApiV1ProjectsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiV1Projects(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/v1/projects}
 */
export function useGetApiV1ProjectsSuspense<TData = GetApiV1ProjectsQueryResponse, TQueryKey extends QueryKey = GetApiV1ProjectsSuspenseQueryKey>(params: GetApiV1ProjectsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetApiV1ProjectsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiV1ProjectsSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getApiV1ProjectsSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}