/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiV1SourcesQueryResponse, GetApiV1SourcesQueryParams } from "../types/GetApiV1Sources";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiV1Sources } from "../clients/getApiV1Sources";

export const getApiV1SourcesSuspenseQueryKey = (params?: GetApiV1SourcesQueryParams) => [{ url: '/api/v1/sources' }, ...(params ? [params] : [])] as const

export type GetApiV1SourcesSuspenseQueryKey = ReturnType<typeof getApiV1SourcesSuspenseQueryKey>

export function getApiV1SourcesSuspenseQueryOptions(params?: GetApiV1SourcesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1SourcesSuspenseQueryKey(params)
        return queryOptions<GetApiV1SourcesQueryResponse, ResponseErrorConfig<Error>, GetApiV1SourcesQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiV1Sources(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/v1/sources}
 */
export function useGetApiV1SourcesSuspense<TData = GetApiV1SourcesQueryResponse, TQueryKey extends QueryKey = GetApiV1SourcesSuspenseQueryKey>(params?: GetApiV1SourcesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetApiV1SourcesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiV1SourcesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getApiV1SourcesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}