/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiV1ProjectsProjectidSettingsQueryResponse, GetApiV1ProjectsProjectidSettingsPathParams } from "../types/GetApiV1ProjectsProjectidSettings";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getApiV1ProjectsProjectidSettings } from "../clients/getApiV1ProjectsProjectidSettings";

export const getApiV1ProjectsProjectidSettingsQueryKey = (projectId: GetApiV1ProjectsProjectidSettingsPathParams["projectId"] | undefined) => [{ url: '/api/v1/projects/:projectId/settings', params: {projectId:projectId} }] as const

export type GetApiV1ProjectsProjectidSettingsQueryKey = ReturnType<typeof getApiV1ProjectsProjectidSettingsQueryKey>

export function getApiV1ProjectsProjectidSettingsQueryOptions(projectId: GetApiV1ProjectsProjectidSettingsPathParams["projectId"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiV1ProjectsProjectidSettingsQueryKey(projectId)
        return queryOptions<GetApiV1ProjectsProjectidSettingsQueryResponse, ResponseErrorConfig<Error>, GetApiV1ProjectsProjectidSettingsQueryResponse, typeof queryKey>({
         enabled: !!(projectId),
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiV1ProjectsProjectidSettings(projectId!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/v1/projects/:projectId/settings}
 */
export function useGetApiV1ProjectsProjectidSettings<TData = GetApiV1ProjectsProjectidSettingsQueryResponse, TQueryData = GetApiV1ProjectsProjectidSettingsQueryResponse, TQueryKey extends QueryKey = GetApiV1ProjectsProjectidSettingsQueryKey>(projectId: GetApiV1ProjectsProjectidSettingsPathParams["projectId"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<GetApiV1ProjectsProjectidSettingsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiV1ProjectsProjectidSettingsQueryKey(projectId)
         

         const query = useQuery({
          ...getApiV1ProjectsProjectidSettingsQueryOptions(projectId, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}