/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type { GetChatCommandsQueryResponse } from "../types/GetChatCommands"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getChatCommands } from "../clients/getChatCommands"

export const getChatCommandsSuspenseQueryKey = () =>
  [{ url: "/chat-commands" }] as const

export type GetChatCommandsSuspenseQueryKey = ReturnType<
  typeof getChatCommandsSuspenseQueryKey
>

export function getChatCommandsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getChatCommandsSuspenseQueryKey()
  return queryOptions<
    GetChatCommandsQueryResponse,
    ResponseErrorConfig<Error>,
    GetChatCommandsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getChatCommands({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /chat-commands}
 */
export function useGetChatCommandsSuspense<
  TData = GetChatCommandsQueryResponse,
  TQueryKey extends QueryKey = GetChatCommandsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetChatCommandsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getChatCommandsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getChatCommandsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
