/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  GetApiV1KeysQueryResponse,
  GetApiV1KeysQueryParams,
  GetApiV1Keys400,
} from "../types/GetApiV1Keys"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { getApiV1Keys } from "../clients/getApiV1Keys"

export const getApiV1KeysSuspenseQueryKey = (
  params?: GetApiV1KeysQueryParams
) => [{ url: "/api/v1/keys" }, ...(params ? [params] : [])] as const

export type GetApiV1KeysSuspenseQueryKey = ReturnType<
  typeof getApiV1KeysSuspenseQueryKey
>

export function getApiV1KeysSuspenseQueryOptions(
  params?: GetApiV1KeysQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getApiV1KeysSuspenseQueryKey(params)
  return queryOptions<
    GetApiV1KeysQueryResponse,
    ResponseErrorConfig<GetApiV1Keys400>,
    GetApiV1KeysQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1Keys(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Lists API keys (issue #45 / F13 — read side of the identity admin).
 * Permission `identity:read`; returns a paged
 * `{ items, total }` envelope of ApiKeyView. The
 * plaintext token never appears in the response — only public-facing
 * fields (prefix, name, status, timestamps). Optional `userId`
 * narrows to a single user.
 * {@link /api/v1/keys}
 */
export function useGetApiV1KeysSuspense<
  TData = GetApiV1KeysQueryResponse,
  TQueryKey extends QueryKey = GetApiV1KeysSuspenseQueryKey,
>(
  params?: GetApiV1KeysQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetApiV1KeysQueryResponse,
        ResponseErrorConfig<GetApiV1Keys400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1KeysSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getApiV1KeysSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetApiV1Keys400>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
