/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  LearningCandidatesGetByIdQueryResponse,
  LearningCandidatesGetByIdPathParams,
  LearningCandidatesGetById404,
} from "../types/LearningCandidatesGetById"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { learningCandidatesGetById } from "../clients/learningCandidatesGetById"

export const learningCandidatesGetByIdQueryKey = (
  candidateId: LearningCandidatesGetByIdPathParams["candidateId"] | undefined
) =>
  [
    {
      url: "/api/v1/learning/candidates/:candidateId",
      params: { candidateId: candidateId },
    },
  ] as const

export type LearningCandidatesGetByIdQueryKey = ReturnType<
  typeof learningCandidatesGetByIdQueryKey
>

export function learningCandidatesGetByIdQueryOptions(
  candidateId: LearningCandidatesGetByIdPathParams["candidateId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = learningCandidatesGetByIdQueryKey(candidateId)
  return queryOptions<
    LearningCandidatesGetByIdQueryResponse,
    ResponseErrorConfig<LearningCandidatesGetById404>,
    LearningCandidatesGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!candidateId,
    queryKey,
    queryFn: async ({ signal }) => {
      return learningCandidatesGetById(candidateId!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Reads one learning candidate. Absent ids read as 404.
 * {@link /api/v1/learning/candidates/:candidateId}
 */
export function useLearningCandidatesGetById<
  TData = LearningCandidatesGetByIdQueryResponse,
  TQueryData = LearningCandidatesGetByIdQueryResponse,
  TQueryKey extends QueryKey = LearningCandidatesGetByIdQueryKey,
>(
  candidateId: LearningCandidatesGetByIdPathParams["candidateId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        LearningCandidatesGetByIdQueryResponse,
        ResponseErrorConfig<LearningCandidatesGetById404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? learningCandidatesGetByIdQueryKey(candidateId)

  const query = useQuery(
    {
      ...learningCandidatesGetByIdQueryOptions(candidateId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<LearningCandidatesGetById404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
