/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import type {
  LearningCandidatesGetByIdQueryResponse,
  LearningCandidatesGetByIdPathParams,
  LearningCandidatesGetById404,
} from "../types/LearningCandidatesGetById"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"
import { learningCandidatesGetById } from "../clients/learningCandidatesGetById"

export const learningCandidatesGetByIdSuspenseQueryKey = (
  candidateId: LearningCandidatesGetByIdPathParams["candidateId"] | undefined
) =>
  [
    {
      url: "/api/v1/learning/candidates/:candidateId",
      params: { candidateId: candidateId },
    },
  ] as const

export type LearningCandidatesGetByIdSuspenseQueryKey = ReturnType<
  typeof learningCandidatesGetByIdSuspenseQueryKey
>

export function learningCandidatesGetByIdSuspenseQueryOptions(
  candidateId: LearningCandidatesGetByIdPathParams["candidateId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = learningCandidatesGetByIdSuspenseQueryKey(candidateId)
  return queryOptions<
    LearningCandidatesGetByIdQueryResponse,
    ResponseErrorConfig<LearningCandidatesGetById404>,
    LearningCandidatesGetByIdQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return learningCandidatesGetById(candidateId, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Reads one learning candidate. Absent ids read as 404.
 * {@link /api/v1/learning/candidates/:candidateId}
 */
export function useLearningCandidatesGetByIdSuspense<
  TData = LearningCandidatesGetByIdQueryResponse,
  TQueryKey extends QueryKey = LearningCandidatesGetByIdSuspenseQueryKey,
>(
  candidateId: LearningCandidatesGetByIdPathParams["candidateId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        LearningCandidatesGetByIdQueryResponse,
        ResponseErrorConfig<LearningCandidatesGetById404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    learningCandidatesGetByIdSuspenseQueryKey(candidateId)

  const query = useSuspenseQuery(
    {
      ...learningCandidatesGetByIdSuspenseQueryOptions(candidateId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<LearningCandidatesGetById404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
