/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1SourcesSourceidProbeMutationResponse,
  PostApiV1SourcesSourceidProbePathParams,
  PostApiV1SourcesSourceidProbe404,
} from "../types/PostApiV1SourcesSourceidProbe"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1SourcesSourceidProbe } from "../clients/postApiV1SourcesSourceidProbe"

export const postApiV1SourcesSourceidProbeMutationKey = () =>
  [{ url: "/api/v1/sources/:sourceId/probe" }] as const

export type PostApiV1SourcesSourceidProbeMutationKey = ReturnType<
  typeof postApiV1SourcesSourceidProbeMutationKey
>

export function postApiV1SourcesSourceidProbeMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = postApiV1SourcesSourceidProbeMutationKey()
  return mutationOptions<
    PostApiV1SourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1SourcesSourceidProbe404>,
    { sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ sourceId }) => {
      return postApiV1SourcesSourceidProbe(sourceId, config)
    },
  })
}

/**
 * {@link /api/v1/sources/:sourceId/probe}
 */
export function usePostApiV1SourcesSourceidProbe<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1SourcesSourceidProbeMutationResponse,
      ResponseErrorConfig<PostApiV1SourcesSourceidProbe404>,
      { sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1SourcesSourceidProbeMutationKey()

  const baseOptions = postApiV1SourcesSourceidProbeMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1SourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1SourcesSourceidProbe404>,
    { sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"] },
    TContext
  >

  return useMutation<
    PostApiV1SourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1SourcesSourceidProbe404>,
    { sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1SourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1SourcesSourceidProbe404>,
    { sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"] },
    TContext
  >
}
