/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1RunsRunidSteerMutationRequest,
  PostApiV1RunsRunidSteerMutationResponse,
  PostApiV1RunsRunidSteerPathParams,
  PostApiV1RunsRunidSteer400,
  PostApiV1RunsRunidSteer403,
  PostApiV1RunsRunidSteer404,
  PostApiV1RunsRunidSteer409,
} from "../types/PostApiV1RunsRunidSteer"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1RunsRunidSteer } from "../clients/postApiV1RunsRunidSteer"

export const postApiV1RunsRunidSteerMutationKey = () =>
  [{ url: "/api/v1/runs/:runId/steer" }] as const

export type PostApiV1RunsRunidSteerMutationKey = ReturnType<
  typeof postApiV1RunsRunidSteerMutationKey
>

export function postApiV1RunsRunidSteerMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1RunsRunidSteerMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postApiV1RunsRunidSteerMutationKey()
  return mutationOptions<
    PostApiV1RunsRunidSteerMutationResponse,
    ResponseErrorConfig<
      | PostApiV1RunsRunidSteer400
      | PostApiV1RunsRunidSteer403
      | PostApiV1RunsRunidSteer404
      | PostApiV1RunsRunidSteer409
    >,
    {
      runId: PostApiV1RunsRunidSteerPathParams["runId"]
      data: PostApiV1RunsRunidSteerMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ runId, data }) => {
      return postApiV1RunsRunidSteer(runId, data, config)
    },
  })
}

/**
 * @summary Steers an in-flight run (add-orchestra §1 — Baton, Phase 1a). The
 * handler resolves `runId → WorkItem → LeasedBy → WorkerId`
 * through the shared IExecutionIdResolver seam and,
 * on the no-LiveSession runtime, stages a follow-up research
 * WorkItem on the same run. The follow-up carries the operator's
 * `text` as its brief — a fresh worker claims the new item
 * after the in-flight lease is fenced by cancel or reaped by the
 * lease policy. Terminal runs answer 409 `run.not_running`.
 * Unknown run ids answer 404 `run.not_found`. Gated by the
 * `steering` feature key (Feature Features.Steering) —
 * Community-tier requests answer 403
 * `edition.feature_unavailable` (issue #164).
 * {@link /api/v1/runs/:runId/steer}
 */
export function usePostApiV1RunsRunidSteer<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1RunsRunidSteerMutationResponse,
      ResponseErrorConfig<
        | PostApiV1RunsRunidSteer400
        | PostApiV1RunsRunidSteer403
        | PostApiV1RunsRunidSteer404
        | PostApiV1RunsRunidSteer409
      >,
      {
        runId: PostApiV1RunsRunidSteerPathParams["runId"]
        data: PostApiV1RunsRunidSteerMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiV1RunsRunidSteerMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1RunsRunidSteerMutationKey()

  const baseOptions = postApiV1RunsRunidSteerMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1RunsRunidSteerMutationResponse,
    ResponseErrorConfig<
      | PostApiV1RunsRunidSteer400
      | PostApiV1RunsRunidSteer403
      | PostApiV1RunsRunidSteer404
      | PostApiV1RunsRunidSteer409
    >,
    {
      runId: PostApiV1RunsRunidSteerPathParams["runId"]
      data: PostApiV1RunsRunidSteerMutationRequest
    },
    TContext
  >

  return useMutation<
    PostApiV1RunsRunidSteerMutationResponse,
    ResponseErrorConfig<
      | PostApiV1RunsRunidSteer400
      | PostApiV1RunsRunidSteer403
      | PostApiV1RunsRunidSteer404
      | PostApiV1RunsRunidSteer409
    >,
    {
      runId: PostApiV1RunsRunidSteerPathParams["runId"]
      data: PostApiV1RunsRunidSteerMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1RunsRunidSteerMutationResponse,
    ResponseErrorConfig<
      | PostApiV1RunsRunidSteer400
      | PostApiV1RunsRunidSteer403
      | PostApiV1RunsRunidSteer404
      | PostApiV1RunsRunidSteer409
    >,
    {
      runId: PostApiV1RunsRunidSteerPathParams["runId"]
      data: PostApiV1RunsRunidSteerMutationRequest
    },
    TContext
  >
}
