/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1ChatSessionsMutationRequest,
  PostApiV1ChatSessionsMutationResponse,
  PostApiV1ChatSessions400,
} from "../types/PostApiV1ChatSessions"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1ChatSessions } from "../clients/postApiV1ChatSessions"

export const postApiV1ChatSessionsMutationKey = () =>
  [{ url: "/api/v1/chat/sessions" }] as const

export type PostApiV1ChatSessionsMutationKey = ReturnType<
  typeof postApiV1ChatSessionsMutationKey
>

export function postApiV1ChatSessionsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1ChatSessionsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postApiV1ChatSessionsMutationKey()
  return mutationOptions<
    PostApiV1ChatSessionsMutationResponse,
    ResponseErrorConfig<PostApiV1ChatSessions400>,
    { data: PostApiV1ChatSessionsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1ChatSessions(data, config)
    },
  })
}

/**
 * {@link /api/v1/chat/sessions}
 */
export function usePostApiV1ChatSessions<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1ChatSessionsMutationResponse,
      ResponseErrorConfig<PostApiV1ChatSessions400>,
      { data: PostApiV1ChatSessionsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiV1ChatSessionsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1ChatSessionsMutationKey()

  const baseOptions = postApiV1ChatSessionsMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1ChatSessionsMutationResponse,
    ResponseErrorConfig<PostApiV1ChatSessions400>,
    { data: PostApiV1ChatSessionsMutationRequest },
    TContext
  >

  return useMutation<
    PostApiV1ChatSessionsMutationResponse,
    ResponseErrorConfig<PostApiV1ChatSessions400>,
    { data: PostApiV1ChatSessionsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1ChatSessionsMutationResponse,
    ResponseErrorConfig<PostApiV1ChatSessions400>,
    { data: PostApiV1ChatSessionsMutationRequest },
    TContext
  >
}
