/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiV1InboxClaimMutationRequest, PostApiV1InboxClaimMutationResponse, PostApiV1InboxClaim400, PostApiV1InboxClaim404, PostApiV1InboxClaim409 } from "../types/PostApiV1InboxClaim";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postApiV1InboxClaim } from "../clients/postApiV1InboxClaim";

export const postApiV1InboxClaimMutationKey = () => [{ url: '/api/v1/inbox/claim' }] as const

export type PostApiV1InboxClaimMutationKey = ReturnType<typeof postApiV1InboxClaimMutationKey>

export function postApiV1InboxClaimMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiV1InboxClaimMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postApiV1InboxClaimMutationKey()
        return mutationOptions<PostApiV1InboxClaimMutationResponse, ResponseErrorConfig<PostApiV1InboxClaim400 | PostApiV1InboxClaim404 | PostApiV1InboxClaim409>, {data: PostApiV1InboxClaimMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postApiV1InboxClaim(data, config)
          },
        })

}

/**
 * {@link /api/v1/inbox/claim}
 */
export function usePostApiV1InboxClaim<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiV1InboxClaimMutationResponse, ResponseErrorConfig<PostApiV1InboxClaim400 | PostApiV1InboxClaim404 | PostApiV1InboxClaim409>, {data: PostApiV1InboxClaimMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiV1InboxClaimMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiV1InboxClaimMutationKey()

          const baseOptions = postApiV1InboxClaimMutationOptions(config) as UseMutationOptions<PostApiV1InboxClaimMutationResponse, ResponseErrorConfig<PostApiV1InboxClaim400 | PostApiV1InboxClaim404 | PostApiV1InboxClaim409>, {data: PostApiV1InboxClaimMutationRequest}, TContext>
          

          return useMutation<PostApiV1InboxClaimMutationResponse, ResponseErrorConfig<PostApiV1InboxClaim400 | PostApiV1InboxClaim404 | PostApiV1InboxClaim409>, {data: PostApiV1InboxClaimMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiV1InboxClaimMutationResponse, ResponseErrorConfig<PostApiV1InboxClaim400 | PostApiV1InboxClaim404 | PostApiV1InboxClaim409>, {data: PostApiV1InboxClaimMutationRequest}, TContext>
      
}