/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PutApiV1IntegrationAdmissionRulesRuleidMutationRequest,
  PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
  PutApiV1IntegrationAdmissionRulesRuleidPathParams,
  PutApiV1IntegrationAdmissionRulesRuleid404,
} from "../types/PutApiV1IntegrationAdmissionRulesRuleid"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { putApiV1IntegrationAdmissionRulesRuleid } from "../clients/putApiV1IntegrationAdmissionRulesRuleid"

export const putApiV1IntegrationAdmissionRulesRuleidMutationKey = () =>
  [{ url: "/api/v1/integration/admission-rules/:ruleId" }] as const

export type PutApiV1IntegrationAdmissionRulesRuleidMutationKey = ReturnType<
  typeof putApiV1IntegrationAdmissionRulesRuleidMutationKey
>

export function putApiV1IntegrationAdmissionRulesRuleidMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PutApiV1IntegrationAdmissionRulesRuleidMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = putApiV1IntegrationAdmissionRulesRuleidMutationKey()
  return mutationOptions<
    PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationAdmissionRulesRuleid404>,
    {
      ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
      data: PutApiV1IntegrationAdmissionRulesRuleidMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ruleId, data }) => {
      return putApiV1IntegrationAdmissionRulesRuleid(ruleId, data, config)
    },
  })
}

/**
 * @summary Partial update (PATCH semantics — null fields stay).
 * {@link /api/v1/integration/admission-rules/:ruleId}
 */
export function usePutApiV1IntegrationAdmissionRulesRuleid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
      ResponseErrorConfig<PutApiV1IntegrationAdmissionRulesRuleid404>,
      {
        ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
        data: PutApiV1IntegrationAdmissionRulesRuleidMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<
      RequestConfig<PutApiV1IntegrationAdmissionRulesRuleidMutationRequest>
    > & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ??
    putApiV1IntegrationAdmissionRulesRuleidMutationKey()

  const baseOptions = putApiV1IntegrationAdmissionRulesRuleidMutationOptions(
    config
  ) as UseMutationOptions<
    PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationAdmissionRulesRuleid404>,
    {
      ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
      data: PutApiV1IntegrationAdmissionRulesRuleidMutationRequest
    },
    TContext
  >

  return useMutation<
    PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationAdmissionRulesRuleid404>,
    {
      ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
      data: PutApiV1IntegrationAdmissionRulesRuleidMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationAdmissionRulesRuleid404>,
    {
      ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
      data: PutApiV1IntegrationAdmissionRulesRuleidMutationRequest
    },
    TContext
  >
}
