/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostWorkersWorkitemidFailMutationRequest, PostWorkersWorkitemidFailMutationResponse, PostWorkersWorkitemidFailPathParams } from "../types/PostWorkersWorkitemidFail";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postWorkersWorkitemidFail } from "../clients/postWorkersWorkitemidFail";

export const postWorkersWorkitemidFailMutationKey = () => [{ url: '/workers/:workItemId/fail' }] as const

export type PostWorkersWorkitemidFailMutationKey = ReturnType<typeof postWorkersWorkitemidFailMutationKey>

export function postWorkersWorkitemidFailMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostWorkersWorkitemidFailMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postWorkersWorkitemidFailMutationKey()
        return mutationOptions<PostWorkersWorkitemidFailMutationResponse, ResponseErrorConfig<Error>, {workItemId: PostWorkersWorkitemidFailPathParams["workItemId"], data: PostWorkersWorkitemidFailMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ workItemId, data }) => {
            return postWorkersWorkitemidFail(workItemId, data, config)
          },
        })

}

/**
 * {@link /workers/:workItemId/fail}
 */
export function usePostWorkersWorkitemidFail<TContext>(options: 
{
  mutation?: UseMutationOptions<PostWorkersWorkitemidFailMutationResponse, ResponseErrorConfig<Error>, {workItemId: PostWorkersWorkitemidFailPathParams["workItemId"], data: PostWorkersWorkitemidFailMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostWorkersWorkitemidFailMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postWorkersWorkitemidFailMutationKey()

          const baseOptions = postWorkersWorkitemidFailMutationOptions(config) as UseMutationOptions<PostWorkersWorkitemidFailMutationResponse, ResponseErrorConfig<Error>, {workItemId: PostWorkersWorkitemidFailPathParams["workItemId"], data: PostWorkersWorkitemidFailMutationRequest}, TContext>
          

          return useMutation<PostWorkersWorkitemidFailMutationResponse, ResponseErrorConfig<Error>, {workItemId: PostWorkersWorkitemidFailPathParams["workItemId"], data: PostWorkersWorkitemidFailMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostWorkersWorkitemidFailMutationResponse, ResponseErrorConfig<Error>, {workItemId: PostWorkersWorkitemidFailPathParams["workItemId"], data: PostWorkersWorkitemidFailMutationRequest}, TContext>
      
}