/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
  PostApiV1IntegrationSourcesSourceidProbePathParams,
  PostApiV1IntegrationSourcesSourceidProbe404,
} from "../types/PostApiV1IntegrationSourcesSourceidProbe"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1IntegrationSourcesSourceidProbe } from "../clients/postApiV1IntegrationSourcesSourceidProbe"

export const postApiV1IntegrationSourcesSourceidProbeMutationKey = () =>
  [{ url: "/api/v1/integration/sources/:sourceId/probe" }] as const

export type PostApiV1IntegrationSourcesSourceidProbeMutationKey = ReturnType<
  typeof postApiV1IntegrationSourcesSourceidProbeMutationKey
>

export function postApiV1IntegrationSourcesSourceidProbeMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = postApiV1IntegrationSourcesSourceidProbeMutationKey()
  return mutationOptions<
    PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1IntegrationSourcesSourceidProbe404>,
    {
      sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"]
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ sourceId }) => {
      return postApiV1IntegrationSourcesSourceidProbe(sourceId, config)
    },
  })
}

/**
 * @summary Probes an existing source connection (issue #42).
 * {@link /api/v1/integration/sources/:sourceId/probe}
 */
export function usePostApiV1IntegrationSourcesSourceidProbe<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
      ResponseErrorConfig<PostApiV1IntegrationSourcesSourceidProbe404>,
      {
        sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"]
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1IntegrationSourcesSourceidProbeMutationKey()

  const baseOptions = postApiV1IntegrationSourcesSourceidProbeMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1IntegrationSourcesSourceidProbe404>,
    {
      sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"]
    },
    TContext
  >

  return useMutation<
    PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1IntegrationSourcesSourceidProbe404>,
    {
      sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"]
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1IntegrationSourcesSourceidProbe404>,
    {
      sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"]
    },
    TContext
  >
}
