/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1GrantsMutationRequest,
  PostApiV1GrantsMutationResponse,
  PostApiV1Grants400,
  PostApiV1Grants409,
} from "../types/PostApiV1Grants"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1Grants } from "../clients/postApiV1Grants"

export const postApiV1GrantsMutationKey = () =>
  [{ url: "/api/v1/grants" }] as const

export type PostApiV1GrantsMutationKey = ReturnType<
  typeof postApiV1GrantsMutationKey
>

export function postApiV1GrantsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1GrantsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postApiV1GrantsMutationKey()
  return mutationOptions<
    PostApiV1GrantsMutationResponse,
    ResponseErrorConfig<PostApiV1Grants400 | PostApiV1Grants409>,
    { data: PostApiV1GrantsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1Grants(data, config)
    },
  })
}

/**
 * {@link /api/v1/grants}
 */
export function usePostApiV1Grants<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1GrantsMutationResponse,
      ResponseErrorConfig<PostApiV1Grants400 | PostApiV1Grants409>,
      { data: PostApiV1GrantsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiV1GrantsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1GrantsMutationKey()

  const baseOptions = postApiV1GrantsMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1GrantsMutationResponse,
    ResponseErrorConfig<PostApiV1Grants400 | PostApiV1Grants409>,
    { data: PostApiV1GrantsMutationRequest },
    TContext
  >

  return useMutation<
    PostApiV1GrantsMutationResponse,
    ResponseErrorConfig<PostApiV1Grants400 | PostApiV1Grants409>,
    { data: PostApiV1GrantsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1GrantsMutationResponse,
    ResponseErrorConfig<PostApiV1Grants400 | PostApiV1Grants409>,
    { data: PostApiV1GrantsMutationRequest },
    TContext
  >
}
