/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiV1SourcesMutationRequest, PostApiV1SourcesMutationResponse, PostApiV1Sources400 } from "../types/PostApiV1Sources";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postApiV1Sources } from "../clients/postApiV1Sources";

export const postApiV1SourcesMutationKey = () => [{ url: '/api/v1/sources' }] as const

export type PostApiV1SourcesMutationKey = ReturnType<typeof postApiV1SourcesMutationKey>

export function postApiV1SourcesMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostApiV1SourcesMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postApiV1SourcesMutationKey()
        return mutationOptions<PostApiV1SourcesMutationResponse, ResponseErrorConfig<PostApiV1Sources400>, {data: PostApiV1SourcesMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postApiV1Sources(data, config)
          },
        })

}

/**
 * {@link /api/v1/sources}
 */
export function usePostApiV1Sources<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiV1SourcesMutationResponse, ResponseErrorConfig<PostApiV1Sources400>, {data: PostApiV1SourcesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostApiV1SourcesMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiV1SourcesMutationKey()

          const baseOptions = postApiV1SourcesMutationOptions(config) as UseMutationOptions<PostApiV1SourcesMutationResponse, ResponseErrorConfig<PostApiV1Sources400>, {data: PostApiV1SourcesMutationRequest}, TContext>
          

          return useMutation<PostApiV1SourcesMutationResponse, ResponseErrorConfig<PostApiV1Sources400>, {data: PostApiV1SourcesMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiV1SourcesMutationResponse, ResponseErrorConfig<PostApiV1Sources400>, {data: PostApiV1SourcesMutationRequest}, TContext>
      
}