/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1RunsRunidApproveMutationResponse,
  PostApiV1RunsRunidApprovePathParams,
  PostApiV1RunsRunidApprove404,
  PostApiV1RunsRunidApprove409,
} from "../types/PostApiV1RunsRunidApprove"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1RunsRunidApprove } from "../clients/postApiV1RunsRunidApprove"

export const postApiV1RunsRunidApproveMutationKey = () =>
  [{ url: "/api/v1/runs/:runId/approve" }] as const

export type PostApiV1RunsRunidApproveMutationKey = ReturnType<
  typeof postApiV1RunsRunidApproveMutationKey
>

export function postApiV1RunsRunidApproveMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = postApiV1RunsRunidApproveMutationKey()
  return mutationOptions<
    PostApiV1RunsRunidApproveMutationResponse,
    ResponseErrorConfig<
      PostApiV1RunsRunidApprove404 | PostApiV1RunsRunidApprove409
    >,
    { runId: PostApiV1RunsRunidApprovePathParams["runId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ runId }) => {
      return postApiV1RunsRunidApprove(runId, config)
    },
  })
}

/**
 * {@link /api/v1/runs/:runId/approve}
 */
export function usePostApiV1RunsRunidApprove<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1RunsRunidApproveMutationResponse,
      ResponseErrorConfig<
        PostApiV1RunsRunidApprove404 | PostApiV1RunsRunidApprove409
      >,
      { runId: PostApiV1RunsRunidApprovePathParams["runId"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1RunsRunidApproveMutationKey()

  const baseOptions = postApiV1RunsRunidApproveMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1RunsRunidApproveMutationResponse,
    ResponseErrorConfig<
      PostApiV1RunsRunidApprove404 | PostApiV1RunsRunidApprove409
    >,
    { runId: PostApiV1RunsRunidApprovePathParams["runId"] },
    TContext
  >

  return useMutation<
    PostApiV1RunsRunidApproveMutationResponse,
    ResponseErrorConfig<
      PostApiV1RunsRunidApprove404 | PostApiV1RunsRunidApprove409
    >,
    { runId: PostApiV1RunsRunidApprovePathParams["runId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1RunsRunidApproveMutationResponse,
    ResponseErrorConfig<
      PostApiV1RunsRunidApprove404 | PostApiV1RunsRunidApprove409
    >,
    { runId: PostApiV1RunsRunidApprovePathParams["runId"] },
    TContext
  >
}
