/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1ProjectsMutationRequest,
  PostApiV1ProjectsMutationResponse,
} from "../types/PostApiV1Projects"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1Projects } from "../clients/postApiV1Projects"

export const postApiV1ProjectsMutationKey = () =>
  [{ url: "/api/v1/projects" }] as const

export type PostApiV1ProjectsMutationKey = ReturnType<
  typeof postApiV1ProjectsMutationKey
>

export function postApiV1ProjectsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1ProjectsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postApiV1ProjectsMutationKey()
  return mutationOptions<
    PostApiV1ProjectsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ProjectsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1Projects(data, config)
    },
  })
}

/**
 * {@link /api/v1/projects}
 */
export function usePostApiV1Projects<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1ProjectsMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PostApiV1ProjectsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiV1ProjectsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1ProjectsMutationKey()

  const baseOptions = postApiV1ProjectsMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1ProjectsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ProjectsMutationRequest },
    TContext
  >

  return useMutation<
    PostApiV1ProjectsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ProjectsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1ProjectsMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1ProjectsMutationRequest },
    TContext
  >
}
