/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1KeysKeyidRevokeMutationResponse,
  PostApiV1KeysKeyidRevokePathParams,
  PostApiV1KeysKeyidRevoke404,
} from "../types/PostApiV1KeysKeyidRevoke"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1KeysKeyidRevoke } from "../clients/postApiV1KeysKeyidRevoke"

export const postApiV1KeysKeyidRevokeMutationKey = () =>
  [{ url: "/api/v1/keys/:keyId/revoke" }] as const

export type PostApiV1KeysKeyidRevokeMutationKey = ReturnType<
  typeof postApiV1KeysKeyidRevokeMutationKey
>

export function postApiV1KeysKeyidRevokeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = postApiV1KeysKeyidRevokeMutationKey()
  return mutationOptions<
    PostApiV1KeysKeyidRevokeMutationResponse,
    ResponseErrorConfig<PostApiV1KeysKeyidRevoke404>,
    { keyId: PostApiV1KeysKeyidRevokePathParams["keyId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ keyId }) => {
      return postApiV1KeysKeyidRevoke(keyId, config)
    },
  })
}

/**
 * {@link /api/v1/keys/:keyId/revoke}
 */
export function usePostApiV1KeysKeyidRevoke<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1KeysKeyidRevokeMutationResponse,
      ResponseErrorConfig<PostApiV1KeysKeyidRevoke404>,
      { keyId: PostApiV1KeysKeyidRevokePathParams["keyId"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1KeysKeyidRevokeMutationKey()

  const baseOptions = postApiV1KeysKeyidRevokeMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1KeysKeyidRevokeMutationResponse,
    ResponseErrorConfig<PostApiV1KeysKeyidRevoke404>,
    { keyId: PostApiV1KeysKeyidRevokePathParams["keyId"] },
    TContext
  >

  return useMutation<
    PostApiV1KeysKeyidRevokeMutationResponse,
    ResponseErrorConfig<PostApiV1KeysKeyidRevoke404>,
    { keyId: PostApiV1KeysKeyidRevokePathParams["keyId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1KeysKeyidRevokeMutationResponse,
    ResponseErrorConfig<PostApiV1KeysKeyidRevoke404>,
    { keyId: PostApiV1KeysKeyidRevokePathParams["keyId"] },
    TContext
  >
}
