/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest,
  PostApiV1ProceduresProjectidProcedurekeyPublishMutationResponse,
  PostApiV1ProceduresProjectidProcedurekeyPublishPathParams,
  PostApiV1ProceduresProjectidProcedurekeyPublish400,
} from "../types/PostApiV1ProceduresProjectidProcedurekeyPublish"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1ProceduresProjectidProcedurekeyPublish } from "../clients/postApiV1ProceduresProjectidProcedurekeyPublish"

export const postApiV1ProceduresProjectidProcedurekeyPublishMutationKey = () =>
  [{ url: "/api/v1/procedures/:projectId/:procedureKey/publish" }] as const

export type PostApiV1ProceduresProjectidProcedurekeyPublishMutationKey =
  ReturnType<typeof postApiV1ProceduresProjectidProcedurekeyPublishMutationKey>

export function postApiV1ProceduresProjectidProcedurekeyPublishMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey =
    postApiV1ProceduresProjectidProcedurekeyPublishMutationKey()
  return mutationOptions<
    PostApiV1ProceduresProjectidProcedurekeyPublishMutationResponse,
    ResponseErrorConfig<PostApiV1ProceduresProjectidProcedurekeyPublish400>,
    {
      projectId: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["projectId"]
      procedureKey: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["procedureKey"]
      data: PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ projectId, procedureKey, data }) => {
      return postApiV1ProceduresProjectidProcedurekeyPublish(
        projectId,
        procedureKey,
        data,
        config
      )
    },
  })
}

/**
 * @summary Publishes a human-approved patch: validates the patch against the
 * base graph + policy context, runs the deterministic compile gate,
 * persists the new compiled version, and writes the
 * `procedures.procedure.published.v1` outbox event. The brain
 * cannot reach this endpoint; only an authenticated human with
 * `procedure:write` can publish (the publication-rights check
 * inside the service refuses brain drafts).
 * {@link /api/v1/procedures/:projectId/:procedureKey/publish}
 */
export function usePostApiV1ProceduresProjectidProcedurekeyPublish<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1ProceduresProjectidProcedurekeyPublishMutationResponse,
      ResponseErrorConfig<PostApiV1ProceduresProjectidProcedurekeyPublish400>,
      {
        projectId: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["projectId"]
        procedureKey: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["procedureKey"]
        data: PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<
      RequestConfig<PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest>
    > & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1ProceduresProjectidProcedurekeyPublishMutationKey()

  const baseOptions =
    postApiV1ProceduresProjectidProcedurekeyPublishMutationOptions(
      config
    ) as UseMutationOptions<
      PostApiV1ProceduresProjectidProcedurekeyPublishMutationResponse,
      ResponseErrorConfig<PostApiV1ProceduresProjectidProcedurekeyPublish400>,
      {
        projectId: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["projectId"]
        procedureKey: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["procedureKey"]
        data: PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest
      },
      TContext
    >

  return useMutation<
    PostApiV1ProceduresProjectidProcedurekeyPublishMutationResponse,
    ResponseErrorConfig<PostApiV1ProceduresProjectidProcedurekeyPublish400>,
    {
      projectId: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["projectId"]
      procedureKey: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["procedureKey"]
      data: PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1ProceduresProjectidProcedurekeyPublishMutationResponse,
    ResponseErrorConfig<PostApiV1ProceduresProjectidProcedurekeyPublish400>,
    {
      projectId: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["projectId"]
      procedureKey: PostApiV1ProceduresProjectidProcedurekeyPublishPathParams["procedureKey"]
      data: PostApiV1ProceduresProjectidProcedurekeyPublishMutationRequest
    },
    TContext
  >
}
