/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1IntegrationItemsMutationRequest,
  PostApiV1IntegrationItemsMutationResponse,
  PostApiV1IntegrationItems400,
  PostApiV1IntegrationItems409,
} from "../types/PostApiV1IntegrationItems"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1IntegrationItems } from "../clients/postApiV1IntegrationItems"

export const postApiV1IntegrationItemsMutationKey = () =>
  [{ url: "/api/v1/integration/items" }] as const

export type PostApiV1IntegrationItemsMutationKey = ReturnType<
  typeof postApiV1IntegrationItemsMutationKey
>

export function postApiV1IntegrationItemsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1IntegrationItemsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postApiV1IntegrationItemsMutationKey()
  return mutationOptions<
    PostApiV1IntegrationItemsMutationResponse,
    ResponseErrorConfig<
      PostApiV1IntegrationItems400 | PostApiV1IntegrationItems409
    >,
    { data: PostApiV1IntegrationItemsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1IntegrationItems(data, config)
    },
  })
}

/**
 * @summary Creates a native inbound item and launches its run.
 * {@link /api/v1/integration/items}
 */
export function usePostApiV1IntegrationItems<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1IntegrationItemsMutationResponse,
      ResponseErrorConfig<
        PostApiV1IntegrationItems400 | PostApiV1IntegrationItems409
      >,
      { data: PostApiV1IntegrationItemsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<
      RequestConfig<PostApiV1IntegrationItemsMutationRequest>
    > & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1IntegrationItemsMutationKey()

  const baseOptions = postApiV1IntegrationItemsMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1IntegrationItemsMutationResponse,
    ResponseErrorConfig<
      PostApiV1IntegrationItems400 | PostApiV1IntegrationItems409
    >,
    { data: PostApiV1IntegrationItemsMutationRequest },
    TContext
  >

  return useMutation<
    PostApiV1IntegrationItemsMutationResponse,
    ResponseErrorConfig<
      PostApiV1IntegrationItems400 | PostApiV1IntegrationItems409
    >,
    { data: PostApiV1IntegrationItemsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1IntegrationItemsMutationResponse,
    ResponseErrorConfig<
      PostApiV1IntegrationItems400 | PostApiV1IntegrationItems409
    >,
    { data: PostApiV1IntegrationItemsMutationRequest },
    TContext
  >
}
