/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1UsersMutationRequest,
  PostApiV1UsersMutationResponse,
  PostApiV1Users400,
  PostApiV1Users409,
} from "../types/PostApiV1Users"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1Users } from "../clients/postApiV1Users"

export const postApiV1UsersMutationKey = () =>
  [{ url: "/api/v1/users" }] as const

export type PostApiV1UsersMutationKey = ReturnType<
  typeof postApiV1UsersMutationKey
>

export function postApiV1UsersMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostApiV1UsersMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postApiV1UsersMutationKey()
  return mutationOptions<
    PostApiV1UsersMutationResponse,
    ResponseErrorConfig<PostApiV1Users400 | PostApiV1Users409>,
    { data: PostApiV1UsersMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1Users(data, config)
    },
  })
}

/**
 * {@link /api/v1/users}
 */
export function usePostApiV1Users<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1UsersMutationResponse,
      ResponseErrorConfig<PostApiV1Users400 | PostApiV1Users409>,
      { data: PostApiV1UsersMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostApiV1UsersMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postApiV1UsersMutationKey()

  const baseOptions = postApiV1UsersMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1UsersMutationResponse,
    ResponseErrorConfig<PostApiV1Users400 | PostApiV1Users409>,
    { data: PostApiV1UsersMutationRequest },
    TContext
  >

  return useMutation<
    PostApiV1UsersMutationResponse,
    ResponseErrorConfig<PostApiV1Users400 | PostApiV1Users409>,
    { data: PostApiV1UsersMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1UsersMutationResponse,
    ResponseErrorConfig<PostApiV1Users400 | PostApiV1Users409>,
    { data: PostApiV1UsersMutationRequest },
    TContext
  >
}
