/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PatchApiV1UsersUseridMutationRequest,
  PatchApiV1UsersUseridMutationResponse,
  PatchApiV1UsersUseridPathParams,
  PatchApiV1UsersUserid400,
  PatchApiV1UsersUserid404,
} from "../types/PatchApiV1UsersUserid"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { patchApiV1UsersUserid } from "../clients/patchApiV1UsersUserid"

export const patchApiV1UsersUseridMutationKey = () =>
  [{ url: "/api/v1/users/:userId" }] as const

export type PatchApiV1UsersUseridMutationKey = ReturnType<
  typeof patchApiV1UsersUseridMutationKey
>

export function patchApiV1UsersUseridMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchApiV1UsersUseridMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = patchApiV1UsersUseridMutationKey()
  return mutationOptions<
    PatchApiV1UsersUseridMutationResponse,
    ResponseErrorConfig<PatchApiV1UsersUserid400 | PatchApiV1UsersUserid404>,
    {
      userId: PatchApiV1UsersUseridPathParams["userId"]
      data: PatchApiV1UsersUseridMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ userId, data }) => {
      return patchApiV1UsersUserid(userId, data, config)
    },
  })
}

/**
 * {@link /api/v1/users/:userId}
 */
export function usePatchApiV1UsersUserid<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchApiV1UsersUseridMutationResponse,
      ResponseErrorConfig<PatchApiV1UsersUserid400 | PatchApiV1UsersUserid404>,
      {
        userId: PatchApiV1UsersUseridPathParams["userId"]
        data: PatchApiV1UsersUseridMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PatchApiV1UsersUseridMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? patchApiV1UsersUseridMutationKey()

  const baseOptions = patchApiV1UsersUseridMutationOptions(
    config
  ) as UseMutationOptions<
    PatchApiV1UsersUseridMutationResponse,
    ResponseErrorConfig<PatchApiV1UsersUserid400 | PatchApiV1UsersUserid404>,
    {
      userId: PatchApiV1UsersUseridPathParams["userId"]
      data: PatchApiV1UsersUseridMutationRequest
    },
    TContext
  >

  return useMutation<
    PatchApiV1UsersUseridMutationResponse,
    ResponseErrorConfig<PatchApiV1UsersUserid400 | PatchApiV1UsersUserid404>,
    {
      userId: PatchApiV1UsersUseridPathParams["userId"]
      data: PatchApiV1UsersUseridMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PatchApiV1UsersUseridMutationResponse,
    ResponseErrorConfig<PatchApiV1UsersUserid400 | PatchApiV1UsersUserid404>,
    {
      userId: PatchApiV1UsersUseridPathParams["userId"]
      data: PatchApiV1UsersUseridMutationRequest
    },
    TContext
  >
}
