/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import type {
  PostApiV1IntegrationSourcesProbeMutationRequest,
  PostApiV1IntegrationSourcesProbeMutationResponse,
} from "../types/PostApiV1IntegrationSourcesProbe"
import { mutationOptions, useMutation } from "@tanstack/react-query"
import { postApiV1IntegrationSourcesProbe } from "../clients/postApiV1IntegrationSourcesProbe"

export const postApiV1IntegrationSourcesProbeMutationKey = () =>
  [{ url: "/api/v1/integration/sources/probe" }] as const

export type PostApiV1IntegrationSourcesProbeMutationKey = ReturnType<
  typeof postApiV1IntegrationSourcesProbeMutationKey
>

export function postApiV1IntegrationSourcesProbeMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiV1IntegrationSourcesProbeMutationRequest>
  > & { client?: Client } = {}
) {
  const mutationKey = postApiV1IntegrationSourcesProbeMutationKey()
  return mutationOptions<
    PostApiV1IntegrationSourcesProbeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1IntegrationSourcesProbeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postApiV1IntegrationSourcesProbe(data, config)
    },
  })
}

/**
 * @summary Probes a draft source connection before save (issue #41).
 * {@link /api/v1/integration/sources/probe}
 */
export function usePostApiV1IntegrationSourcesProbe<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1IntegrationSourcesProbeMutationResponse,
      ResponseErrorConfig<Error>,
      { data: PostApiV1IntegrationSourcesProbeMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<
      RequestConfig<PostApiV1IntegrationSourcesProbeMutationRequest>
    > & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postApiV1IntegrationSourcesProbeMutationKey()

  const baseOptions = postApiV1IntegrationSourcesProbeMutationOptions(
    config
  ) as UseMutationOptions<
    PostApiV1IntegrationSourcesProbeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1IntegrationSourcesProbeMutationRequest },
    TContext
  >

  return useMutation<
    PostApiV1IntegrationSourcesProbeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1IntegrationSourcesProbeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostApiV1IntegrationSourcesProbeMutationResponse,
    ResponseErrorConfig<Error>,
    { data: PostApiV1IntegrationSourcesProbeMutationRequest },
    TContext
  >
}
