/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import type {
  RunsGetByIdQueryResponse,
  RunsGetByIdPathParams,
  RunsGetById404,
} from "../types/RunsGetById"
import { queryOptions, useQuery } from "@tanstack/react-query"
import { runsGetById } from "../clients/runsGetById"

export const runsGetByIdQueryKey = (
  runId: RunsGetByIdPathParams["runId"] | undefined
) => [{ url: "/api/v1/runs/:runId", params: { runId: runId } }] as const

export type RunsGetByIdQueryKey = ReturnType<typeof runsGetByIdQueryKey>

export function runsGetByIdQueryOptions(
  runId: RunsGetByIdPathParams["runId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = runsGetByIdQueryKey(runId)
  return queryOptions<
    RunsGetByIdQueryResponse,
    ResponseErrorConfig<RunsGetById404>,
    RunsGetByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!runId,
    queryKey,
    queryFn: async ({ signal }) => {
      return runsGetById(runId!, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Reads the full detail of one run: work items with their DAG edges, the
 * recent journal (top 20), the pinned revisions, and the brief. The
 * subject-scope query filter is the only gate beyond `run:read` —
 * a run the subject cannot see reads as 404, not 403.
 * {@link /api/v1/runs/:runId}
 */
export function useRunsGetById<
  TData = RunsGetByIdQueryResponse,
  TQueryData = RunsGetByIdQueryResponse,
  TQueryKey extends QueryKey = RunsGetByIdQueryKey,
>(
  runId: RunsGetByIdPathParams["runId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        RunsGetByIdQueryResponse,
        ResponseErrorConfig<RunsGetById404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? runsGetByIdQueryKey(runId)

  const query = useQuery(
    {
      ...runsGetByIdQueryOptions(runId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<RunsGetById404>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
