<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Comuki.Host.Brain.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\platform\src\host\Comuki.Host.Brain\Comuki.Host.Brain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\deploy\helm\templates\brain.yaml" Link="Deployment\brain.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\deploy\hybrid\host.Dockerfile" Link="Deployment\host.Dockerfile" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\deploy\hybrid\infra-dev.yaml" Link="Deployment\infra-dev.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
