/**
 * `comuki completion <shell>` — prints a completion script to stdout
 * (no Ink, no config): `pwsh` gets a `Register-ArgumentCompleter`
 * block, `bash` gets a `compgen -W` function. The generators are pure
 * `(commands, flags, themes) → string` so the emitted boilerplate is
 * unit-tested, and the word lists live next to their consumer instead
 * of being scraped from yargs at runtime.
 */
import { THEME_CHOICE_IDS } from "../themes"
import { colors } from "../theme"

/** Subcommands the completions offer (mirrors the yargs wiring in index.tsx). */
export const COMPLETION_COMMANDS: readonly string[] = [
  "status",
  "runs",
  "login",
  "whoami",
  "config",
  "setup",
  "completion",
]

/** Global flags the completions offer (mirrors the yargs options). */
export const COMPLETION_FLAGS: readonly string[] = [
  "--url",
  "--api-key",
  "--project",
  "--theme",
  "--help",
  "--version",
]

/** `@('a','b')` — the arrays are plain identifiers, single quotes suffice. */
function psList(values: readonly string[]): string {
  return `@(${values.map((value) => `'${value}'`).join(",")})`
}

/**
 * pwsh completion via `Register-ArgumentCompleter -Native`: commands +
 * flags for a bare word, flags only once the word starts with `-`, and
 * the 14 `<theme>-<dark|light>` ids right after `--theme`.
 */
export function powershellCompletion(
  commands: readonly string[],
  flags: readonly string[],
  themes: readonly string[]
): string {
  return [
    "# comuki completion (pwsh) — generated by `comuki completion pwsh`.",
    "# Add to your $PROFILE:  . '<path-to-this-file>'",
    "Register-ArgumentCompleter -CommandName 'comuki' -Native -ScriptBlock {",
    "    param($wordToComplete, $commandAst, $cursorPosition)",
    "",
    `    $commands = ${psList(commands)}`,
    `    $flags    = ${psList(flags)}`,
    `    $themes   = ${psList(themes)}`,
    "",
    "    $line = $commandAst.ToString()",
    "    if ($line -match '--theme\\s+(\\S*)$') {",
    "        $candidates = $themes",
    "    }",
    "    elseif ($wordToComplete.StartsWith('-')) {",
    "        $candidates = $flags",
    "    }",
    "    else {",
    "        $candidates = $commands + $flags",
    "    }",
    "",
    "    $candidates |",
    "        Where-Object { $_ -like ($wordToComplete + '*') } |",
    "        ForEach-Object {",
    "            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)",
    "        }",
    "}",
    "",
  ].join("\n")
}

/**
 * bash completion via `complete -F` — the `compgen -W` equivalent of
 * the pwsh block: same three-way candidate choice, same word lists.
 */
export function bashCompletion(
  commands: readonly string[],
  flags: readonly string[],
  themes: readonly string[]
): string {
  return [
    "# comuki completion (bash) — generated by `comuki completion bash`.",
    "# Add to ~/.bashrc:  source <(comuki completion bash)",
    "_comuki_complete() {",
    "  local cur prev candidates",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    `  local commands="${commands.join(" ")}"`,
    `  local flags="${flags.join(" ")}"`,
    `  local themes="${themes.join(" ")}"`,
    "",
    '  if [ "$prev" = "--theme" ]; then',
    '    candidates="$themes"',
    '  elif [ "${cur:0:1}" = "-" ]; then',
    '    candidates="$flags"',
    "  else",
    '    candidates="$commands $flags"',
    "  fi",
    "",
    "  COMPREPLY=($(compgen -W \"$candidates\" -- \"$cur\"))",
    "}",
    "complete -F _comuki_complete comuki",
    "",
  ].join("\n")
}

/**
 * Resolves a shell name to its script; undefined for anything the CLI
 * does not speak (the caller turns that into the usage error).
 */
export function completionScript(
  shell: string,
  themes: readonly string[] = THEME_CHOICE_IDS
): string | undefined {
  if (shell === "pwsh") {
    return powershellCompletion(COMPLETION_COMMANDS, COMPLETION_FLAGS, themes)
  }
  if (shell === "bash") {
    return bashCompletion(COMPLETION_COMMANDS, COMPLETION_FLAGS, themes)
  }
  return undefined
}

/** `comuki completion <shell>` entry: script to stdout, error to stderr. */
export function printCompletion(shell: string): void {
  const script = completionScript(shell)
  if (script === undefined) {
    console.error(
      `${colors.error}unknown shell: ${shell || "(none)"}${colors.reset} — expected pwsh or bash`
    )
    process.exitCode = 1
    return
  }
  process.stdout.write(script)
}
