<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\platform\src\application\api\Comuki.Platform.Api.Public\Comuki.Platform.Api.Public.csproj" />
    <ProjectReference Include="..\..\platform\src\feature\Comuki.Platform.Orchestration\Comuki.Platform.Orchestration.csproj" />
    <ProjectReference Include="..\..\platform\src\models\Comuki.Platform.Entity.Core\Comuki.Platform.Entity.Core.csproj" />
    <ProjectReference Include="..\..\platform\src\models\Comuki.Platform.Api.Contracts\Comuki.Platform.Api.Contracts.csproj" />
  </ItemGroup>

</Project>
