// <auto-generated />
using System;
using Comuki.Engine.Orchestration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comuki.Engine.Orchestration.Infrastructure.Migrations
{
    [DbContext(typeof(OrchestrationDbContext))]
    [Migration("20260903085423_UseSchemas")]
    partial class UseSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.Journal.RunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_run_events");

                    b.HasIndex("RunId", "OccurredAt")
                        .HasDatabaseName("ix_run_events_run_id_occurred_at");

                    b.ToTable("run_events", "orchestration");
                });

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.Runs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.ToTable("runs", "orchestration");
                });

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.WorkItems.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("brief");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<Guid?>("LeasedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("leased_by");

                    b.Property<string>("ProfileKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("profile_key");

                    b.Property<string>("ProfilesRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("profiles_ref");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_work_items_run_id");

                    b.HasIndex("ProfileKey", "CreatedAt")
                        .HasDatabaseName("ix_work_items_claim")
                        .HasFilter("status = 'Queued'");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_work_items_active")
                        .HasFilter("status IN ('Queued', 'Running')");

                    b.ToTable("work_items", "orchestration");
                });

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.WorkItems.WorkItemDependency", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.Property<Guid>("DependsOnWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_work_item_id");

                    b.HasKey("WorkItemId", "DependsOnWorkItemId")
                        .HasName("pk_work_item_dependencies");

                    b.HasIndex("DependsOnWorkItemId")
                        .HasDatabaseName("ix_work_item_dependencies_depends_on_work_item_id");

                    b.ToTable("work_item_dependencies", "orchestration");
                });

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.Journal.RunEvent", b =>
                {
                    b.HasOne("Comuki.Engine.Orchestration.Domain.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_events_runs_run_id");
                });

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.WorkItems.WorkItem", b =>
                {
                    b.HasOne("Comuki.Engine.Orchestration.Domain.Runs.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_runs_run_id");
                });

            modelBuilder.Entity("Comuki.Engine.Orchestration.Domain.WorkItems.WorkItemDependency", b =>
                {
                    b.HasOne("Comuki.Engine.Orchestration.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("DependsOnWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_dependencies_work_items_depends_on_work_item_id");

                    b.HasOne("Comuki.Engine.Orchestration.Domain.WorkItems.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_item_dependencies_work_items_work_item_id");
                });
#pragma warning restore 612, 618
        }
    }
}
