// <auto-generated />
using System;
using Comuki.Modules.Costs.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Comuki.Modules.Costs.Infrastructure.Migrations
{
    [DbContext(typeof(CostsDbContext))]
    partial class CostsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Comuki.Modules.Costs.Domain.Events.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CostUsdMicros")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_usd_micros");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_usage_events");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_usage_events_run_id");

                    b.HasIndex("ProjectId", "OccurredAt")
                        .HasDatabaseName("ix_usage_events_project_occurred");

                    b.ToTable("usage_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
