<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Comuki.Platform.Api.Public</RootNamespace>
    <AssemblyName>Comuki.Platform.Api.Public</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\feature\Comuki.Platform.Orchestration\Comuki.Platform.Orchestration.csproj" />
    <ProjectReference Include="..\..\..\models\Comuki.Platform.Api.Contracts\Comuki.Platform.Api.Contracts.csproj" />
    <ProjectReference Include="..\..\..\models\Comuki.Platform.Entity.Core\Comuki.Platform.Entity.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
