<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Comuki.Modules.Work.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Comuki.Shared.Kernel\Comuki.Shared.Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Comuki.Modules.Work.Application" />
    <InternalsVisibleTo Include="Comuki.Modules.Work.Infrastructure" />
    <InternalsVisibleTo Include="Comuki.Modules.Work.Unit" />
  </ItemGroup>

</Project>
