<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="protobuf-net.Grpc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\modules\Costs\Comuki.Modules.Costs.Domain\Comuki.Modules.Costs.Domain.csproj" />
    <ProjectReference Include="..\Comuki.Shared.Kernel\Comuki.Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
