using System.Reflection;
using System.Text;

namespace Comuki.Shared.Contracts.Realtime;

/// <summary>
/// Emits a TypeScript module from every <see cref="RealtimeContractAttribute"/>
/// type in the <see cref="RealtimeContractAssembly"/>. The output is a single
/// self-contained <c>.ts</c> file with one <c>export interface</c> per
/// contract plus a <c>RealtimeTransportMethods</c> const block. Used by the
/// dashboard's typed SignalR client so the wire types stay in sync with the
/// C# server without hand-written duplication.
/// </summary>
/// <remarks>
/// Hand-rolled over reflection (rather than Roslyn or a source generator)
/// because the realtime surface is a handful of records — the cost of a
/// build-time codegen pipeline is not yet justified. When the slice grows
/// past ~20 contracts, swap the body for a Roslyn <c>IIncrementalGenerator</c>
/// that reads <see cref="RealtimeContractAttribute"/> via
/// <c>ForAttributeWithMetadataName</c> and emits the same module to
/// <c>obj/generated/comuki-realtime.ts</c>.
/// </remarks>
public static class RealtimeContractEmitter
{
    /// <summary>
    /// Marker assembly — the emitter reads contracts from
    /// <c>RealtimeContractAssembly.Assembly</c> at runtime so the
    /// caller never has to pass an <see cref="Assembly"/> argument.
    /// Keeping the marker in this very class is enough; any other
    /// assembly that wants to ship contracts just references the
    /// shared contracts project and decorates its records.
    /// </summary>
    public static class RealtimeContractAssembly
    {
        /// <summary>The assembly searched for <see cref="RealtimeContractAttribute"/>-tagged types.</summary>
        public static readonly Assembly Assembly = typeof(RealtimeContractAttribute).Assembly;
    }

    /// <summary>Renders a TypeScript module containing every contract in the realtime assembly.</summary>
    /// <returns>A self-contained TypeScript string. The output is deterministic for a given assembly version.</returns>
    public static string Emit()
    {
        return Emit(RealtimeContractAssembly.Assembly);
    }

    /// <summary>Renders a TypeScript module from the contracts in the supplied assembly.</summary>
    /// <param name="assembly">The assembly to scan. Tests may pass a different one; production uses <see cref="Emit()"/>.</param>
    /// <returns>A self-contained TypeScript string. Deterministic for a given input.</returns>
    public static string Emit(Assembly assembly)
    {
        var contracts = assembly
            .GetTypes()
            .Where(static type => type.GetCustomAttribute<RealtimeContractAttribute>() is not null)
            .OrderBy(static type => type.FullName, StringComparer.Ordinal)
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Source: Comuki.Shared.Contracts/Realtime (C#) -- DO NOT EDIT BY HAND.");
        builder.AppendLine("// Regenerate via: dotnet run --project tools/Comuki.Codegen.Realtime (slice #11).");
        builder.AppendLine("// eslint-disable-next-line @typescript-eslint/consistent-type-definitions");
        builder.AppendLine();

        builder.AppendLine("export const RealtimeTransportMethods = {");
        builder.AppendLine("  RunEvent: \"RunEvent\",");
        builder.AppendLine("  Attention: \"Attention\",");
        builder.AppendLine("} as const;");
        builder.AppendLine();

        foreach (var contract in contracts)
        {
            EmitInterface(builder, contract);
            builder.AppendLine();
        }

        return builder.ToString();
    }

    /// <summary>Emits one <c>export interface</c> for a single contract type.</summary>
    /// <param name="builder">The string builder receiving the rendered module.</param>
    /// <param name="contract">The contract type. Must carry <see cref="RealtimeContractAttribute"/>.</param>
    private static void EmitInterface(StringBuilder builder, Type contract)
    {
        builder.Append("export interface ").Append(contract.Name).AppendLine(" {");

        foreach (var member in contract.GetMembers(BindingFlags.Public | BindingFlags.Instance))
        {
            if (member is not PropertyInfo property)
            {
                continue;
            }

            if (property.GetIndexParameters().Length > 0)
            {
                continue;
            }

            var wireName = property.GetCustomAttribute<RealtimeContractJsonNameAttribute>()?.Name
                ?? ToCamelCase(property.Name);

            builder.Append("  readonly ").Append(wireName).Append(": ").Append(MapType(property)).AppendLine(";");
        }

        builder.AppendLine("}");
    }

    /// <summary>Maps a CLR property to its TypeScript wire-shape, including the null modifier when the property admits null.</summary>
    /// <param name="property">The property to map. Nullable reference annotations and <see cref="Nullable{T}"/> both flow through <see cref="IsPropertyNullable"/>.</param>
    /// <returns>The TypeScript primitive (or <c>"... | null"</c> for nullable shapes).</returns>
    private static string MapType(PropertyInfo property)
    {
        var type = property.PropertyType;
        var nullable = IsPropertyNullable(property);
        var underlying = Nullable.GetUnderlyingType(type) ?? type;
        var core = underlying switch
        {
            Type t when t == typeof(string) => "string",
            Type t when t == typeof(bool) => "boolean",
            Type t when t == typeof(byte) || t == typeof(sbyte) || t == typeof(short) || t == typeof(ushort) || t == typeof(int) || t == typeof(uint) || t == typeof(long) || t == typeof(ulong) || t == typeof(float) || t == typeof(double) || t == typeof(decimal) => "number",
            Type t when t == typeof(Guid) => "string",
            Type t when t == typeof(DateTime) || t == typeof(DateTimeOffset) => "string",
            _ => "unknown",
        };
        return nullable ? core + " | null" : core;
    }

    /// <summary>True when the property admits null on the wire (nullable reference or <see cref="Nullable{T}"/>).</summary>
    /// <param name="property">The property to inspect.</param>
    private static bool IsPropertyNullable(PropertyInfo property)
    {
        if (Nullable.GetUnderlyingType(property.PropertyType) is not null)
        {
            return true;
        }

        if (property.PropertyType.IsValueType)
        {
            return false;
        }

        // System.Reflection.NullabilityInfoContext reads the [Nullable] /
        // [NullableContext] annotations the C# compiler emits on record
        // positional properties. Reflecting on those attributes by hand is
        // fragile across compiler versions; the public API does the right
        // thing and is the documented way to ask "is this property nullable?".
        // Note: NullabilityInfoContext is not thread-safe — the emitter is
        // called once per process so we keep a single instance on the
        // emitter rather than re-allocating per property.
        return nullability.Create(property).ReadState == NullabilityState.Nullable;
    }

    /// <summary>Shared, single-threaded nullability reader (NullabilityInfoContext is not thread-safe).</summary>
    private static readonly NullabilityInfoContext nullability = new();

    /// <summary>Converts a PascalCase CLR member name to camelCase for the TypeScript wire.</summary>
    /// <param name="name">The CLR member name (PascalCase).</param>
    private static string ToCamelCase(string name)
    {
        return string.IsNullOrEmpty(name) || char.IsLower(name[0])
            ? name
            : char.ToLowerInvariant(name[0]) + name[1..];
    }
}
