/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { DeleteApiV1SourcesSourceidMutationResponse, DeleteApiV1SourcesSourceidPathParams } from "../types/DeleteApiV1SourcesSourceid";

function getDeleteApiV1SourcesSourceidUrl(sourceId: DeleteApiV1SourcesSourceidPathParams["sourceId"]) {
  const res = { method: 'DELETE', url: `/api/v1/sources/${sourceId}` as const }
  return res
}

/**
 * {@link /api/v1/sources/:sourceId}
 */
export async function deleteApiV1SourcesSourceid(sourceId: DeleteApiV1SourcesSourceidPathParams["sourceId"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteApiV1SourcesSourceidMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteApiV1SourcesSourceidUrl(sourceId).url.toString(), ... requestConfig })
  return res.data
}