/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  DeleteApiV1IntegrationSourcesSourceidMutationResponse,
  DeleteApiV1IntegrationSourcesSourceidPathParams,
} from "../types/DeleteApiV1IntegrationSourcesSourceid"

function getDeleteApiV1IntegrationSourcesSourceidUrl(
  sourceId: DeleteApiV1IntegrationSourcesSourceidPathParams["sourceId"]
) {
  const res = {
    method: "DELETE",
    url: `/api/v1/integration/sources/${sourceId}` as const,
  }
  return res
}

/**
 * @summary Deletes a connection (idempotent).
 * {@link /api/v1/integration/sources/:sourceId}
 */
export async function deleteApiV1IntegrationSourcesSourceid(
  sourceId: DeleteApiV1IntegrationSourcesSourceidPathParams["sourceId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    DeleteApiV1IntegrationSourcesSourceidMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1IntegrationSourcesSourceidUrl(sourceId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
