/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1ProceduresVersionsVersionidQueryResponse,
  GetApiV1ProceduresVersionsVersionidPathParams,
  GetApiV1ProceduresVersionsVersionid404,
} from "../types/GetApiV1ProceduresVersionsVersionid"

function getGetApiV1ProceduresVersionsVersionidUrl(
  versionId: GetApiV1ProceduresVersionsVersionidPathParams["versionId"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/procedures/versions/${versionId}` as const,
  }
  return res
}

/**
 * @summary Reads one compiled version by its content-addressed id.
 * {@link /api/v1/procedures/versions/:versionId}
 */
export async function getApiV1ProceduresVersionsVersionid(
  versionId: GetApiV1ProceduresVersionsVersionidPathParams["versionId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1ProceduresVersionsVersionidQueryResponse,
    ResponseErrorConfig<GetApiV1ProceduresVersionsVersionid404>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ProceduresVersionsVersionidUrl(versionId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
