/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1IntegrationInboxCatalogQueryResponse,
  GetApiV1IntegrationInboxCatalogQueryParams,
  GetApiV1IntegrationInboxCatalog404,
} from "../types/GetApiV1IntegrationInboxCatalog"

function getGetApiV1IntegrationInboxCatalogUrl() {
  const res = {
    method: "GET",
    url: `/api/v1/integration/inbox/catalog` as const,
  }
  return res
}

/**
 * @summary Fetches one page of a connection's external issue catalog.
 * {@link /api/v1/integration/inbox/catalog}
 */
export async function getApiV1IntegrationInboxCatalog(
  params?: GetApiV1IntegrationInboxCatalogQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1IntegrationInboxCatalogQueryResponse,
    ResponseErrorConfig<GetApiV1IntegrationInboxCatalog404>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1IntegrationInboxCatalogUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
