/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1WorkersQueryResponse,
  GetApiV1WorkersQueryParams,
} from "../types/GetApiV1Workers"

function getGetApiV1WorkersUrl() {
  const res = { method: "GET", url: `/api/v1/workers` as const }
  return res
}

/**
 * {@link /api/v1/workers}
 */
export async function getApiV1Workers(
  params?: GetApiV1WorkersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1WorkersQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1WorkersUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
