/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1AuthOidcProviderStartQueryResponse,
  GetApiV1AuthOidcProviderStartPathParams,
  GetApiV1AuthOidcProviderStart404,
} from "../types/GetApiV1AuthOidcProviderStart"

function getGetApiV1AuthOidcProviderStartUrl(
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/auth/oidc/${provider}/start` as const,
  }
  return res
}

/**
 * {@link /api/v1/auth/oidc/:provider/start}
 */
export async function getApiV1AuthOidcProviderStart(
  provider: GetApiV1AuthOidcProviderStartPathParams["provider"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1AuthOidcProviderStartQueryResponse,
    ResponseErrorConfig<GetApiV1AuthOidcProviderStart404>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1AuthOidcProviderStartUrl(provider).url.toString(),
    ...requestConfig,
  })
  return res.data
}
