/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type { GetApiV1ChatSessionsQueryResponse } from "../types/GetApiV1ChatSessions"

function getGetApiV1ChatSessionsUrl() {
  const res = { method: "GET", url: `/api/v1/chat/sessions` as const }
  return res
}

/**
 * {@link /api/v1/chat/sessions}
 */
export async function getApiV1ChatSessions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1ChatSessionsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ChatSessionsUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
