/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
  GetApiV1IntegrationAdmissionRulesRuleidPathParams,
  GetApiV1IntegrationAdmissionRulesRuleid404,
} from "../types/GetApiV1IntegrationAdmissionRulesRuleid"

function getGetApiV1IntegrationAdmissionRulesRuleidUrl(
  ruleId: GetApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/integration/admission-rules/${ruleId}` as const,
  }
  return res
}

/**
 * @summary Reads one rule.
 * {@link /api/v1/integration/admission-rules/:ruleId}
 */
export async function getApiV1IntegrationAdmissionRulesRuleid(
  ruleId: GetApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1IntegrationAdmissionRulesRuleidQueryResponse,
    ResponseErrorConfig<GetApiV1IntegrationAdmissionRulesRuleid404>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1IntegrationAdmissionRulesRuleidUrl(ruleId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
