/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1SourcesQueryResponse,
  GetApiV1SourcesQueryParams,
} from "../types/GetApiV1Sources"

function getGetApiV1SourcesUrl() {
  const res = { method: "GET", url: `/api/v1/sources` as const }
  return res
}

/**
 * {@link /api/v1/sources}
 */
export async function getApiV1Sources(
  params?: GetApiV1SourcesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1SourcesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1SourcesUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
