/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  GetApiV1GrantsQueryResponse,
  GetApiV1GrantsQueryParams,
  GetApiV1Grants400,
} from "../types/GetApiV1Grants"

function getGetApiV1GrantsUrl() {
  const res = { method: "GET", url: `/api/v1/grants` as const }
  return res
}

/**
 * @summary Lists role assignments (issue #45 / F13 — read side of the identity admin).
 * Permission `identity:read`; returns a paged
 * `{ items, total }` envelope of RoleAssignmentView.
 * Optional `subjectKind` + `subjectId` narrow to a single user or key.
 * {@link /api/v1/grants}
 */
export async function getApiV1Grants(
  params?: GetApiV1GrantsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetApiV1GrantsQueryResponse,
    ResponseErrorConfig<GetApiV1Grants400>,
    unknown
  >({
    method: "GET",
    url: getGetApiV1GrantsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
