/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type { GetChatCommandsQueryResponse } from "../types/GetChatCommands"

function getGetChatCommandsUrl() {
  const res = { method: "GET", url: `/chat-commands` as const }
  return res
}

/**
 * {@link /chat-commands}
 */
export async function getChatCommands(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetChatCommandsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetChatCommandsUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
