/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type { GetV1ModelsQueryResponse } from "../types/GetV1Models"

function getGetV1ModelsUrl() {
  const res = { method: "GET", url: `/v1/models` as const }
  return res
}

/**
 * {@link /v1/models}
 */
export async function getV1Models(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetV1ModelsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetV1ModelsUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
