/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { PatchApiV1ProjectsProjectidMutationRequest, PatchApiV1ProjectsProjectidMutationResponse, PatchApiV1ProjectsProjectidPathParams } from "../types/PatchApiV1ProjectsProjectid";

function getPatchApiV1ProjectsProjectidUrl(projectId: PatchApiV1ProjectsProjectidPathParams["projectId"]) {
  const res = { method: 'PATCH', url: `/api/v1/projects/${projectId}` as const }
  return res
}

/**
 * {@link /api/v1/projects/:projectId}
 */
export async function patchApiV1ProjectsProjectid(projectId: PatchApiV1ProjectsProjectidPathParams["projectId"], data: PatchApiV1ProjectsProjectidMutationRequest, config: Partial<RequestConfig<PatchApiV1ProjectsProjectidMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PatchApiV1ProjectsProjectidMutationResponse, ResponseErrorConfig<Error>, PatchApiV1ProjectsProjectidMutationRequest>({ method : "PATCH", url : getPatchApiV1ProjectsProjectidUrl(projectId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}