/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1KeysMutationRequest,
  PostApiV1KeysMutationResponse,
  PostApiV1Keys400,
  PostApiV1Keys404,
} from "../types/PostApiV1Keys"

function getPostApiV1KeysUrl() {
  const res = { method: "POST", url: `/api/v1/keys` as const }
  return res
}

/**
 * {@link /api/v1/keys}
 */
export async function postApiV1Keys(
  data: PostApiV1KeysMutationRequest,
  config: Partial<RequestConfig<PostApiV1KeysMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostApiV1KeysMutationResponse,
    ResponseErrorConfig<PostApiV1Keys400 | PostApiV1Keys404>,
    PostApiV1KeysMutationRequest
  >({
    method: "POST",
    url: getPostApiV1KeysUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
