/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1KeysKeyidRevokeMutationResponse,
  PostApiV1KeysKeyidRevokePathParams,
  PostApiV1KeysKeyidRevoke404,
} from "../types/PostApiV1KeysKeyidRevoke"

function getPostApiV1KeysKeyidRevokeUrl(
  keyId: PostApiV1KeysKeyidRevokePathParams["keyId"]
) {
  const res = { method: "POST", url: `/api/v1/keys/${keyId}/revoke` as const }
  return res
}

/**
 * {@link /api/v1/keys/:keyId/revoke}
 */
export async function postApiV1KeysKeyidRevoke(
  keyId: PostApiV1KeysKeyidRevokePathParams["keyId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1KeysKeyidRevokeMutationResponse,
    ResponseErrorConfig<PostApiV1KeysKeyidRevoke404>,
    unknown
  >({
    method: "POST",
    url: getPostApiV1KeysKeyidRevokeUrl(keyId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
