/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { PostApiV1AuthLoginMutationRequest, PostApiV1AuthLoginMutationResponse, PostApiV1AuthLogin401 } from "../types/PostApiV1AuthLogin";

function getPostApiV1AuthLoginUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/login` as const }
  return res
}

/**
 * {@link /api/v1/auth/login}
 */
export async function postApiV1AuthLogin(data: PostApiV1AuthLoginMutationRequest, config: Partial<RequestConfig<PostApiV1AuthLoginMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostApiV1AuthLoginMutationResponse, ResponseErrorConfig<PostApiV1AuthLogin401>, PostApiV1AuthLoginMutationRequest>({ method : "POST", url : getPostApiV1AuthLoginUrl().url.toString(), data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/*+json', ...requestConfig.headers } })
  return res.data
}