/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1RunsRunidApproveMutationResponse,
  PostApiV1RunsRunidApprovePathParams,
  PostApiV1RunsRunidApprove404,
  PostApiV1RunsRunidApprove409,
} from "../types/PostApiV1RunsRunidApprove"

function getPostApiV1RunsRunidApproveUrl(
  runId: PostApiV1RunsRunidApprovePathParams["runId"]
) {
  const res = { method: "POST", url: `/api/v1/runs/${runId}/approve` as const }
  return res
}

/**
 * @summary Approves a run that the orchestrator escalated back to a human gate.
 * The transition is legal from `Escalated` only; every other
 * source (including terminal statuses) answers 409. Successful approve
 * returns 204 with no body; the orchestrator's journal
 * (`run.status_changed`) records the transition.
 * {@link /api/v1/runs/:runId/approve}
 */
export async function postApiV1RunsRunidApprove(
  runId: PostApiV1RunsRunidApprovePathParams["runId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1RunsRunidApproveMutationResponse,
    ResponseErrorConfig<
      PostApiV1RunsRunidApprove404 | PostApiV1RunsRunidApprove409
    >,
    unknown
  >({
    method: "POST",
    url: getPostApiV1RunsRunidApproveUrl(runId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
