/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostWorkersWorkitemidHeartbeatMutationResponse,
  PostWorkersWorkitemidHeartbeatPathParams,
} from "../types/PostWorkersWorkitemidHeartbeat"

function getPostWorkersWorkitemidHeartbeatUrl(
  workItemId: PostWorkersWorkitemidHeartbeatPathParams["workItemId"]
) {
  const res = {
    method: "POST",
    url: `/workers/${workItemId}/heartbeat` as const,
  }
  return res
}

/**
 * {@link /workers/:workItemId/heartbeat}
 */
export async function postWorkersWorkitemidHeartbeat(
  workItemId: PostWorkersWorkitemidHeartbeatPathParams["workItemId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostWorkersWorkitemidHeartbeatMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getPostWorkersWorkitemidHeartbeatUrl(workItemId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
