/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1GrantsGrantidRevokeMutationResponse,
  PostApiV1GrantsGrantidRevokePathParams,
  PostApiV1GrantsGrantidRevoke404,
} from "../types/PostApiV1GrantsGrantidRevoke"

function getPostApiV1GrantsGrantidRevokeUrl(
  grantId: PostApiV1GrantsGrantidRevokePathParams["grantId"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/grants/${grantId}/revoke` as const,
  }
  return res
}

/**
 * {@link /api/v1/grants/:grantId/revoke}
 */
export async function postApiV1GrantsGrantidRevoke(
  grantId: PostApiV1GrantsGrantidRevokePathParams["grantId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1GrantsGrantidRevokeMutationResponse,
    ResponseErrorConfig<PostApiV1GrantsGrantidRevoke404>,
    unknown
  >({
    method: "POST",
    url: getPostApiV1GrantsGrantidRevokeUrl(grantId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
