/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { PostApiV1AuthLogoutMutationResponse } from "../types/PostApiV1AuthLogout";

function getPostApiV1AuthLogoutUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/logout` as const }
  return res
}

/**
 * {@link /api/v1/auth/logout}
 */
export async function postApiV1AuthLogout(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiV1AuthLogoutMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiV1AuthLogoutUrl().url.toString(), ... requestConfig })
  return res.data
}