/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1LearningCandidatesCandidateidApproveMutationResponse,
  PostApiV1LearningCandidatesCandidateidApprovePathParams,
  PostApiV1LearningCandidatesCandidateidApprove404,
  PostApiV1LearningCandidatesCandidateidApprove409,
} from "../types/PostApiV1LearningCandidatesCandidateidApprove"

function getPostApiV1LearningCandidatesCandidateidApproveUrl(
  candidateId: PostApiV1LearningCandidatesCandidateidApprovePathParams["candidateId"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/learning/candidates/${candidateId}/approve` as const,
  }
  return res
}

/**
 * @summary Approves a pending candidate and publishes its rule. Successful
 * approve returns 204; deciding an already-decided candidate answers
 * 409 (an already-approved one is idempotent — the retry after a
 * publish failure re-publishes rather than conflicts).
 * {@link /api/v1/learning/candidates/:candidateId/approve}
 */
export async function postApiV1LearningCandidatesCandidateidApprove(
  candidateId: PostApiV1LearningCandidatesCandidateidApprovePathParams["candidateId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1LearningCandidatesCandidateidApproveMutationResponse,
    ResponseErrorConfig<
      | PostApiV1LearningCandidatesCandidateidApprove404
      | PostApiV1LearningCandidatesCandidateidApprove409
    >,
    unknown
  >({
    method: "POST",
    url: getPostApiV1LearningCandidatesCandidateidApproveUrl(
      candidateId
    ).url.toString(),
    ...requestConfig,
  })
  return res.data
}
