/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1GrantsMutationRequest,
  PostApiV1GrantsMutationResponse,
  PostApiV1Grants400,
  PostApiV1Grants409,
} from "../types/PostApiV1Grants"

function getPostApiV1GrantsUrl() {
  const res = { method: "POST", url: `/api/v1/grants` as const }
  return res
}

/**
 * {@link /api/v1/grants}
 */
export async function postApiV1Grants(
  data: PostApiV1GrantsMutationRequest,
  config: Partial<RequestConfig<PostApiV1GrantsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostApiV1GrantsMutationResponse,
    ResponseErrorConfig<PostApiV1Grants400 | PostApiV1Grants409>,
    PostApiV1GrantsMutationRequest
  >({
    method: "POST",
    url: getPostApiV1GrantsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
