/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/shared/api/kubb-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/shared/api/kubb-client";
import type { PostWorkersWorkitemidCompleteMutationRequest, PostWorkersWorkitemidCompleteMutationResponse, PostWorkersWorkitemidCompletePathParams } from "../types/PostWorkersWorkitemidComplete";

function getPostWorkersWorkitemidCompleteUrl(workItemId: PostWorkersWorkitemidCompletePathParams["workItemId"]) {
  const res = { method: 'POST', url: `/workers/${workItemId}/complete` as const }
  return res
}

/**
 * {@link /workers/:workItemId/complete}
 */
export async function postWorkersWorkitemidComplete(workItemId: PostWorkersWorkitemidCompletePathParams["workItemId"], data: PostWorkersWorkitemidCompleteMutationRequest, config: Partial<RequestConfig<PostWorkersWorkitemidCompleteMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostWorkersWorkitemidCompleteMutationResponse, ResponseErrorConfig<Error>, PostWorkersWorkitemidCompleteMutationRequest>({ method : "POST", url : getPostWorkersWorkitemidCompleteUrl(workItemId).url.toString(), data : requestData, ... requestConfig })
  return res.data
}