/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1TicketsMutationRequest,
  PostApiV1TicketsMutationResponse,
  PostApiV1Tickets400,
  PostApiV1Tickets409,
} from "../types/PostApiV1Tickets"

function getPostApiV1TicketsUrl() {
  const res = { method: "POST", url: `/api/v1/tickets` as const }
  return res
}

/**
 * {@link /api/v1/tickets}
 */
export async function postApiV1Tickets(
  data: PostApiV1TicketsMutationRequest,
  config: Partial<RequestConfig<PostApiV1TicketsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostApiV1TicketsMutationResponse,
    ResponseErrorConfig<PostApiV1Tickets400 | PostApiV1Tickets409>,
    PostApiV1TicketsMutationRequest
  >({
    method: "POST",
    url: getPostApiV1TicketsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
