/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1IntegrationSourcesMutationRequest,
  PostApiV1IntegrationSourcesMutationResponse,
  PostApiV1IntegrationSources400,
} from "../types/PostApiV1IntegrationSources"

function getPostApiV1IntegrationSourcesUrl() {
  const res = { method: "POST", url: `/api/v1/integration/sources` as const }
  return res
}

/**
 * @summary Creates a connection; the view carries the webhook path to configure in the tracker.
 * {@link /api/v1/integration/sources}
 */
export async function postApiV1IntegrationSources(
  data: PostApiV1IntegrationSourcesMutationRequest,
  config: Partial<RequestConfig<PostApiV1IntegrationSourcesMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostApiV1IntegrationSourcesMutationResponse,
    ResponseErrorConfig<PostApiV1IntegrationSources400>,
    PostApiV1IntegrationSourcesMutationRequest
  >({
    method: "POST",
    url: getPostApiV1IntegrationSourcesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
