/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
  PostApiV1IntegrationSourcesSourceidProbePathParams,
  PostApiV1IntegrationSourcesSourceidProbe404,
} from "../types/PostApiV1IntegrationSourcesSourceidProbe"

function getPostApiV1IntegrationSourcesSourceidProbeUrl(
  sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/integration/sources/${sourceId}/probe` as const,
  }
  return res
}

/**
 * @summary Probes an existing source connection (issue #42).
 * {@link /api/v1/integration/sources/:sourceId/probe}
 */
export async function postApiV1IntegrationSourcesSourceidProbe(
  sourceId: PostApiV1IntegrationSourcesSourceidProbePathParams["sourceId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1IntegrationSourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1IntegrationSourcesSourceidProbe404>,
    unknown
  >({
    method: "POST",
    url: getPostApiV1IntegrationSourcesSourceidProbeUrl(
      sourceId
    ).url.toString(),
    ...requestConfig,
  })
  return res.data
}
