/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1AdmissionRulesMutationRequest,
  PostApiV1AdmissionRulesMutationResponse,
  PostApiV1AdmissionRules400,
} from "../types/PostApiV1AdmissionRules"

function getPostApiV1AdmissionRulesUrl() {
  const res = { method: "POST", url: `/api/v1/admission-rules` as const }
  return res
}

/**
 * {@link /api/v1/admission-rules}
 */
export async function postApiV1AdmissionRules(
  data: PostApiV1AdmissionRulesMutationRequest,
  config: Partial<RequestConfig<PostApiV1AdmissionRulesMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostApiV1AdmissionRulesMutationResponse,
    ResponseErrorConfig<PostApiV1AdmissionRules400>,
    PostApiV1AdmissionRulesMutationRequest
  >({
    method: "POST",
    url: getPostApiV1AdmissionRulesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
