/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1SourcesSourceidRotateSecretMutationResponse,
  PostApiV1SourcesSourceidRotateSecretPathParams,
  PostApiV1SourcesSourceidRotateSecret404,
} from "../types/PostApiV1SourcesSourceidRotateSecret"

function getPostApiV1SourcesSourceidRotateSecretUrl(
  sourceId: PostApiV1SourcesSourceidRotateSecretPathParams["sourceId"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/sources/${sourceId}/rotate-secret` as const,
  }
  return res
}

/**
 * @summary Rotates a source connection's webhook verification secret (issue #46).
 * Generates a new 256-bit hex secret, persists it on the connection,
 * and returns the plaintext exactly once in the response so the
 * operator can configure the tracker. The structured log carries a
 * `source.secret_rotated` event id with the connection id and
 * env-var name — never the secret itself.
 * {@link /api/v1/sources/:sourceId/rotate-secret}
 */
export async function postApiV1SourcesSourceidRotateSecret(
  sourceId: PostApiV1SourcesSourceidRotateSecretPathParams["sourceId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1SourcesSourceidRotateSecretMutationResponse,
    ResponseErrorConfig<PostApiV1SourcesSourceidRotateSecret404>,
    unknown
  >({
    method: "POST",
    url: getPostApiV1SourcesSourceidRotateSecretUrl(sourceId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
