/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1IntegrationInboxClaimMutationRequest,
  PostApiV1IntegrationInboxClaimMutationResponse,
  PostApiV1IntegrationInboxClaim400,
  PostApiV1IntegrationInboxClaim404,
  PostApiV1IntegrationInboxClaim409,
} from "../types/PostApiV1IntegrationInboxClaim"

function getPostApiV1IntegrationInboxClaimUrl() {
  const res = {
    method: "POST",
    url: `/api/v1/integration/inbox/claim` as const,
  }
  return res
}

/**
 * @summary Claims one pending ticket into a run (exactly once — a repeat answers 409).
 * {@link /api/v1/integration/inbox/claim}
 */
export async function postApiV1IntegrationInboxClaim(
  data: PostApiV1IntegrationInboxClaimMutationRequest,
  config: Partial<
    RequestConfig<PostApiV1IntegrationInboxClaimMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostApiV1IntegrationInboxClaimMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IntegrationInboxClaim400
      | PostApiV1IntegrationInboxClaim404
      | PostApiV1IntegrationInboxClaim409
    >,
    PostApiV1IntegrationInboxClaimMutationRequest
  >({
    method: "POST",
    url: getPostApiV1IntegrationInboxClaimUrl().url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
