/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PostApiV1SourcesSourceidProbeMutationResponse,
  PostApiV1SourcesSourceidProbePathParams,
  PostApiV1SourcesSourceidProbe404,
} from "../types/PostApiV1SourcesSourceidProbe"

function getPostApiV1SourcesSourceidProbeUrl(
  sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/sources/${sourceId}/probe` as const,
  }
  return res
}

/**
 * {@link /api/v1/sources/:sourceId/probe}
 */
export async function postApiV1SourcesSourceidProbe(
  sourceId: PostApiV1SourcesSourceidProbePathParams["sourceId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    PostApiV1SourcesSourceidProbeMutationResponse,
    ResponseErrorConfig<PostApiV1SourcesSourceidProbe404>,
    unknown
  >({
    method: "POST",
    url: getPostApiV1SourcesSourceidProbeUrl(sourceId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
