/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PutApiV1IntegrationAdmissionRulesRuleidMutationRequest,
  PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
  PutApiV1IntegrationAdmissionRulesRuleidPathParams,
  PutApiV1IntegrationAdmissionRulesRuleid404,
} from "../types/PutApiV1IntegrationAdmissionRulesRuleid"

function getPutApiV1IntegrationAdmissionRulesRuleidUrl(
  ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"]
) {
  const res = {
    method: "PUT",
    url: `/api/v1/integration/admission-rules/${ruleId}` as const,
  }
  return res
}

/**
 * @summary Partial update (PATCH semantics — null fields stay).
 * {@link /api/v1/integration/admission-rules/:ruleId}
 */
export async function putApiV1IntegrationAdmissionRulesRuleid(
  ruleId: PutApiV1IntegrationAdmissionRulesRuleidPathParams["ruleId"],
  data: PutApiV1IntegrationAdmissionRulesRuleidMutationRequest,
  config: Partial<
    RequestConfig<PutApiV1IntegrationAdmissionRulesRuleidMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PutApiV1IntegrationAdmissionRulesRuleidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationAdmissionRulesRuleid404>,
    PutApiV1IntegrationAdmissionRulesRuleidMutationRequest
  >({
    method: "PUT",
    url: getPutApiV1IntegrationAdmissionRulesRuleidUrl(ruleId).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
