/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PutApiV1SourcesSourceidMutationRequest,
  PutApiV1SourcesSourceidMutationResponse,
  PutApiV1SourcesSourceidPathParams,
  PutApiV1SourcesSourceid404,
} from "../types/PutApiV1SourcesSourceid"

function getPutApiV1SourcesSourceidUrl(
  sourceId: PutApiV1SourcesSourceidPathParams["sourceId"]
) {
  const res = { method: "PUT", url: `/api/v1/sources/${sourceId}` as const }
  return res
}

/**
 * {@link /api/v1/sources/:sourceId}
 */
export async function putApiV1SourcesSourceid(
  sourceId: PutApiV1SourcesSourceidPathParams["sourceId"],
  data: PutApiV1SourcesSourceidMutationRequest,
  config: Partial<RequestConfig<PutApiV1SourcesSourceidMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PutApiV1SourcesSourceidMutationResponse,
    ResponseErrorConfig<PutApiV1SourcesSourceid404>,
    PutApiV1SourcesSourceidMutationRequest
  >({
    method: "PUT",
    url: getPutApiV1SourcesSourceidUrl(sourceId).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
