/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PutApiV1IntegrationSourcesSourceidMutationRequest,
  PutApiV1IntegrationSourcesSourceidMutationResponse,
  PutApiV1IntegrationSourcesSourceidPathParams,
  PutApiV1IntegrationSourcesSourceid404,
} from "../types/PutApiV1IntegrationSourcesSourceid"

function getPutApiV1IntegrationSourcesSourceidUrl(
  sourceId: PutApiV1IntegrationSourcesSourceidPathParams["sourceId"]
) {
  const res = {
    method: "PUT",
    url: `/api/v1/integration/sources/${sourceId}` as const,
  }
  return res
}

/**
 * @summary Partial update (PATCH semantics — null fields stay).
 * {@link /api/v1/integration/sources/:sourceId}
 */
export async function putApiV1IntegrationSourcesSourceid(
  sourceId: PutApiV1IntegrationSourcesSourceidPathParams["sourceId"],
  data: PutApiV1IntegrationSourcesSourceidMutationRequest,
  config: Partial<
    RequestConfig<PutApiV1IntegrationSourcesSourceidMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PutApiV1IntegrationSourcesSourceidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationSourcesSourceid404>,
    PutApiV1IntegrationSourcesSourceidMutationRequest
  >({
    method: "PUT",
    url: getPutApiV1IntegrationSourcesSourceidUrl(sourceId).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
