/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  PutApiV1IntegrationSourcesSourceidRulesRuleidMutationRequest,
  PutApiV1IntegrationSourcesSourceidRulesRuleidMutationResponse,
  PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams,
  PutApiV1IntegrationSourcesSourceidRulesRuleid404,
} from "../types/PutApiV1IntegrationSourcesSourceidRulesRuleid"

function getPutApiV1IntegrationSourcesSourceidRulesRuleidUrl(
  sourceId: PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams["sourceId"],
  ruleId: PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams["ruleId"]
) {
  const res = {
    method: "PUT",
    url: `/api/v1/integration/sources/${sourceId}/rules/${ruleId}` as const,
  }
  return res
}

/**
 * @summary Partial update of an admission rule nested under a source connection
 * (issue #40). Wire-compatible with the sibling
 * `PUT /api/v1/admission-rules/{ruleId}` — the source id is
 * accepted in the route for the FE's nested form, but the rule row
 * lives in its own table and is matched by id alone.
 * {@link /api/v1/integration/sources/:sourceId/rules/:ruleId}
 */
export async function putApiV1IntegrationSourcesSourceidRulesRuleid(
  sourceId: PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams["sourceId"],
  ruleId: PutApiV1IntegrationSourcesSourceidRulesRuleidPathParams["ruleId"],
  data: PutApiV1IntegrationSourcesSourceidRulesRuleidMutationRequest,
  config: Partial<
    RequestConfig<PutApiV1IntegrationSourcesSourceidRulesRuleidMutationRequest>
  > & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PutApiV1IntegrationSourcesSourceidRulesRuleidMutationResponse,
    ResponseErrorConfig<PutApiV1IntegrationSourcesSourceidRulesRuleid404>,
    PutApiV1IntegrationSourcesSourceidRulesRuleidMutationRequest
  >({
    method: "PUT",
    url: getPutApiV1IntegrationSourcesSourceidRulesRuleidUrl(
      sourceId,
      ruleId
    ).url.toString(),
    data: requestData,
    ...requestConfig,
    headers: { "Content-Type": "application/*+json", ...requestConfig.headers },
  })
  return res.data
}
