/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  RunsGetByIdQueryResponse,
  RunsGetByIdPathParams,
  RunsGetById404,
} from "../types/RunsGetById"

function getRunsGetByIdUrl(runId: RunsGetByIdPathParams["runId"]) {
  const res = { method: "GET", url: `/api/v1/runs/${runId}` as const }
  return res
}

/**
 * @summary Reads the full detail of one run: work items with their DAG edges, the
 * recent journal (top 20), the pinned revisions, and the brief. The
 * subject-scope query filter is the only gate beyond `run:read` —
 * a run the subject cannot see reads as 404, not 403.
 * {@link /api/v1/runs/:runId}
 */
export async function runsGetById(
  runId: RunsGetByIdPathParams["runId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    RunsGetByIdQueryResponse,
    ResponseErrorConfig<RunsGetById404>,
    unknown
  >({
    method: "GET",
    url: getRunsGetByIdUrl(runId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
