/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type {
  RunsGetVerificationQueryResponse,
  RunsGetVerificationPathParams,
  RunsGetVerification403,
  RunsGetVerification404,
} from "../types/RunsGetVerification"

function getRunsGetVerificationUrl(
  runId: RunsGetVerificationPathParams["runId"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/runs/${runId}/verification` as const,
  }
  return res
}

/**
 * @summary Reads the per-gate verification view (add-orchestra §3 — Coda).
 * Returns the flat list of (work item, gate) verdicts the
 * orchestrator has stamped for the run, and the derived
 * `verified` / `verificationPending` booleans the FE
 * renders as the "verification pending" pill under the run's
 * status strip. A run with no verdicts yet (project had
 * `VerifyEnabled=false`, or all work items still pending)
 * reads as 200 with an empty `Gates` list and both booleans
 * `false` — the FE renders "no gates evaluated"
 * without a separate null path. Gated by the `verification`
 * paid feature key — Community-tier requests answer 403
 * `edition.feature_unavailable`.
 * {@link /api/v1/runs/:runId/verification}
 */
export async function runsGetVerification(
  runId: RunsGetVerificationPathParams["runId"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    RunsGetVerificationQueryResponse,
    ResponseErrorConfig<RunsGetVerification403 | RunsGetVerification404>,
    unknown
  >({
    method: "GET",
    url: getRunsGetVerificationUrl(runId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
