/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/shared/api/kubb-client"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/kubb-client"
import type { WorkCapabilitiesListQueryResponse } from "../types/WorkCapabilitiesList"

function getWorkCapabilitiesListUrl() {
  const res = { method: "GET", url: `/api/v1/work/capabilities` as const }
  return res
}

/**
 * @summary The full set of WorkCapabilities the Work module
 * exposes. Stable contract; the worker's response is the wire
 * form the Broker indexes (see
 * `openspec/changes/add-mission-cowork/design.md`).
 * {@link /api/v1/work/capabilities}
 */
export async function workCapabilitiesList(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    WorkCapabilitiesListQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getWorkCapabilitiesListUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
