<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Comuki.License.Mint</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\platform\src\shared\Comuki.Shared.Editions\Comuki.Shared.Editions.csproj" />
  </ItemGroup>

</Project>