using System.Text.Json;
using Comuki.Shared.Contracts.Realtime;
using Shouldly;
using Xunit;

namespace Comuki.Shared.Contracts.Unit.Realtime;

/// <summary>
/// Codegen emitter coverage (#11 sub-slice): the dashboard SignalR client
/// reads the same wire shapes the host broadcasts, so the TypeScript
/// module rendered by <see cref="RealtimeContractEmitter"/> must stay in
/// lockstep with the C# records. These tests pin the rendered module's
/// shape (interface names, property wire names, types, transport method
/// constants) and the round-trip — a record serialised through
/// <see cref="JsonSerializer"/> carries every field the dashboard
/// expects to receive on the wire.
/// </summary>
public sealed class RealtimeContractEmitterShould
{
    [Fact(DisplayName = "Given the realtime assembly, when Emit is called, then every annotated type renders as an interface")]
    public void EmitEveryContract()
    {
        var module = RealtimeContractEmitter.Emit();

        module.ShouldContain("export interface RunEventView");
        module.ShouldContain("export interface AttentionView");
    }

    [Fact(DisplayName = "Given RunEventView, when Emit is called, then the interface declares the six wire properties in camelCase")]
    public void EmitRunEventViewShape()
    {
        var module = RealtimeContractEmitter.Emit();

        module.ShouldContain("readonly runId: string;");
        module.ShouldContain("readonly type: string;");
        module.ShouldContain("readonly workItemId: string | null;");
        module.ShouldContain("readonly occurredAtUnixMs: number;");
        module.ShouldContain("readonly payloadJson: string | null;");
        module.ShouldContain("readonly payloadOmitted: boolean;");
    }

    [Fact(DisplayName = "Given AttentionView, when Emit is called, then the interface declares the six wire properties in camelCase")]
    public void EmitAttentionViewShape()
    {
        var module = RealtimeContractEmitter.Emit();

        module.ShouldContain("readonly runId: string;");
        module.ShouldContain("readonly projectId: string;");
        module.ShouldContain("readonly workItemId: string | null;");
        module.ShouldContain("readonly status: string;");
        module.ShouldContain("readonly attentionKind: string;");
        module.ShouldContain("readonly occurredAtUnixMs: number;");
    }

    [Fact(DisplayName = "Given the realtime transport methods, when Emit is called, then the wire constants land in the TypeScript module")]
    public void EmitRealtimeTransportMethodsConstants()
    {
        var module = RealtimeContractEmitter.Emit();

        module.ShouldContain("export const RealtimeTransportMethods = {");
        module.ShouldContain("RunEvent: \"RunEvent\"");
        module.ShouldContain("Attention: \"Attention\"");
    }

    [Fact(DisplayName = "Given the module header, when Emit is called, then the auto-generated banner is the first non-empty line")]
    public void EmitHeaderBanner()
    {
        var module = RealtimeContractEmitter.Emit();

        module.TrimStart().ShouldStartWith("// <auto-generated />");
    }

    [Fact(DisplayName = "Given a RunEventView, when serialised to JSON, then every field reaches the wire as the dashboard expects")]
    public void RunEventViewRoundTrip()
    {
        var view = new RunEventView(
            RunId: Guid.Parse("11111111-2222-3333-4444-555555555555"),
            Type: "work_item.status_changed",
            WorkItemId: Guid.Parse("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
            OccurredAtUnixMs: 1_725_000_123_456,
            PayloadJson: /*lang=json,strict*/ """{"to":"Running","from":"Queued"}""",
            PayloadOmitted: false);

        var json = JsonSerializer.Serialize(view);

        json.ShouldContain("\"RunId\":\"11111111-2222-3333-4444-555555555555\"");
        json.ShouldContain("\"Type\":\"work_item.status_changed\"");
        json.ShouldContain("\"WorkItemId\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\"");
        json.ShouldContain("\"OccurredAtUnixMs\":1725000123456");
        json.ShouldContain("\"PayloadOmitted\":false");

        var roundTripped = JsonSerializer.Deserialize<RunEventView>(json)!;
        roundTripped.RunId.ShouldBe(view.RunId);
        roundTripped.Type.ShouldBe(view.Type);
        roundTripped.WorkItemId.ShouldBe(view.WorkItemId);
        roundTripped.OccurredAtUnixMs.ShouldBe(view.OccurredAtUnixMs);
        roundTripped.PayloadJson.ShouldBe(view.PayloadJson);
        roundTripped.PayloadOmitted.ShouldBe(view.PayloadOmitted);
    }

    [Fact(DisplayName = "Given an AttentionView, when serialised to JSON, then every field reaches the wire as the dashboard expects")]
    public void AttentionViewRoundTrip()
    {
        var view = new AttentionView(
            RunId: Guid.Parse("11111111-2222-3333-4444-555555555555"),
            ProjectId: Guid.Parse("66666666-7777-8888-9999-aaaaaaaaaaaa"),
            WorkItemId: Guid.Parse("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
            Status: "Failed",
            AttentionKind: "failed",
            OccurredAtUnixMs: 1_725_000_999_999);

        var json = JsonSerializer.Serialize(view);

        json.ShouldContain("\"RunId\":\"11111111-2222-3333-4444-555555555555\"");
        json.ShouldContain("\"ProjectId\":\"66666666-7777-8888-9999-aaaaaaaaaaaa\"");
        json.ShouldContain("\"WorkItemId\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\"");
        json.ShouldContain("\"Status\":\"Failed\"");
        json.ShouldContain("\"AttentionKind\":\"failed\"");
        json.ShouldContain("\"OccurredAtUnixMs\":1725000999999");

        var roundTripped = JsonSerializer.Deserialize<AttentionView>(json)!;
        roundTripped.RunId.ShouldBe(view.RunId);
        roundTripped.ProjectId.ShouldBe(view.ProjectId);
        roundTripped.WorkItemId.ShouldBe(view.WorkItemId);
        roundTripped.Status.ShouldBe(view.Status);
        roundTripped.AttentionKind.ShouldBe(view.AttentionKind);
        roundTripped.OccurredAtUnixMs.ShouldBe(view.OccurredAtUnixMs);
    }

    [Fact(DisplayName = "Given a RunEventView with null WorkItemId, when serialised to JSON, then the wire carries the absent work item id")]
    public void RunEventViewNullableWorkItemIdRoundTrip()
    {
        var view = new RunEventView(
            RunId: Guid.Parse("11111111-2222-3333-4444-555555555555"),
            Type: "run.status_changed",
            WorkItemId: null,
            OccurredAtUnixMs: 1_725_000_555_555,
            PayloadJson: null,
            PayloadOmitted: true);

        var json = JsonSerializer.Serialize(view);

        json.ShouldContain("\"WorkItemId\":null");
        json.ShouldContain("\"PayloadJson\":null");
        json.ShouldContain("\"PayloadOmitted\":true");

        var roundTripped = JsonSerializer.Deserialize<RunEventView>(json)!;
        roundTripped.WorkItemId.ShouldBeNull();
        roundTripped.PayloadJson.ShouldBeNull();
        roundTripped.PayloadOmitted.ShouldBeTrue();
    }
}
