/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Read-model of an admission rule.
 */
export const admissionRuleViewSchema = z
  .object({
    id: z.uuid(),
    projectId: z.uuid(),
    mode: z.string().describe("watch | inbox."),
    filterJson: z.string(),
    enabled: z.boolean(),
  })
  .describe("Read-model of an admission rule.")
