/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const artifactsVisualContentPathParamsSchema = z.object({
  projectId: z.uuid(),
  artifactId: z.uuid(),
})

/**
 * @description OK
 */
export const artifactsVisualContent200Schema = z.any()

/**
 * @description Not Found
 */
export const artifactsVisualContent404Schema = z.lazy(
  () => problemDetailsSchema
)

export const artifactsVisualContentQueryResponseSchema = z.lazy(
  () => artifactsVisualContent200Schema
)
