/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { visualArtifactPageSchema } from "./visualArtifactPageSchema"
import { z } from "zod/v4"

export const artifactsVisualListPathParamsSchema = z.object({
  projectId: z.uuid().describe("Owning project (path)."),
})

export const artifactsVisualListQueryParamsSchema = z
  .object({
    runId: z.optional(z.uuid().describe("Optional run filter (query).")),
    workItemId: z.optional(
      z.uuid().describe("Optional work-item filter (query).")
    ),
  })
  .optional()

/**
 * @description OK
 */
export const artifactsVisualList200Schema = z
  .lazy(() => visualArtifactPageSchema)
  .describe("Page envelope returned by the visual-artifacts list endpoint.")

/**
 * @description Not Found
 */
export const artifactsVisualList404Schema = z.lazy(() => problemDetailsSchema)

export const artifactsVisualListQueryResponseSchema = z.lazy(
  () => artifactsVisualList200Schema
)
