/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const chatSessionViewSchema = z.object({
    "id": z.uuid(),
"projectId": z.uuid().nullish(),
"title": z.string(),
"status": z.string(),
"createdAt": z.iso.datetime({ offset: true }),
"updatedAt": z.iso.datetime({ offset: true })
    })