/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const chatApproveRequestSchema = z.object({
    "approved": z.boolean(),
"reason": z.string().nullish()
    })