/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One slash command as listed to the dashboard / autocomplete and expanded\r\ninto the brain task by the router.
 */
export const chatSlashCommandSchema = z
  .object({
    key: z
      .string()
      .describe("Command identity without the slash (e.g. `init`)."),
    name: z.string().describe("Human-readable name."),
    description: z.string().describe("One-line description."),
    body: z
      .string()
      .describe(
        "Full instruction body expanded into the brain task (empty for graph-native commands like `init`)."
      ),
    source: z
      .string()
      .describe("Where the command comes from: `builtin` or `control-plane`."),
  })
  .describe(
    "One slash command as listed to the dashboard / autocomplete and expanded\r\ninto the brain task by the router."
  )
