/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One project × profile pool with the counts the queue can answer.
 */
export const computePoolViewSchema = z
  .object({
    projectId: z.uuid().describe("Owning project."),
    profileKey: z.string().describe("Profile the pool serves."),
    queued: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Items waiting for a claim."),
    running: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Items currently leased (busy workers)."),
    minIdle: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe(
        "Project's warm-idle floor (projects settings override the default)."
      ),
    maxConcurrent: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Project's concurrency cap."),
  })
  .describe("One project × profile pool with the counts the queue can answer.")
