/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Scale supervisor defaults from ScaleSupervisorOptions.
 */
export const computeScaleSettingsViewSchema = z
  .object({
    workerImage: z.string().describe("Default worker image."),
    profilesGitRef: z.string().describe("Default pinned profiles git ref."),
    minIdle: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Warm-idle floor per profile."),
    maxConcurrent: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Concurrency cap per project."),
    idleTtlSeconds: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Idle TTL before a worker is a reaper candidate."),
    pollIntervalSeconds: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Delay between supervisor passes."),
  })
  .describe("Scale supervisor defaults from ScaleSupervisorOptions.")
