/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Scale defaults from ScaleSupervisorOptions.
 */
export const computeScaleDefaultsViewSchema = z
  .object({
    workerImage: z
      .string()
      .describe("Default worker image (digest-pinned in production)."),
    profilesGitRef: z.string().describe("Default pinned profiles git ref."),
    minIdle: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Warm-idle floor per profile."),
    maxConcurrent: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Cap on concurrently running workers per project."),
    idleTtlSeconds: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Idle TTL before a worker is a reaper candidate, in seconds."),
    pollIntervalSeconds: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Delay between supervisor passes, in seconds."),
    profileKeys: z
      .array(z.string())
      .describe("Profile keys the supervisor polls per project."),
  })
  .describe("Scale defaults from ScaleSupervisorOptions.")
