/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { computeScaleSettingsViewSchema } from "./computeScaleSettingsViewSchema"
import { z } from "zod/v4"

/**
 * @description Compute selection + scale defaults from `Compute:*`.
 */
export const computeSettingsViewSchema = z
  .object({
    provider: z
      .string()
      .describe("Active provider key: `docker` or `kubernetes`."),
    get scale() {
      return computeScaleSettingsViewSchema.describe(
        "Scale supervisor defaults from ScaleSupervisorOptions."
      )
    },
  })
  .describe("Compute selection + scale defaults from `Compute:*`.")
