/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createAdmissionRuleRequestSchema = z.object({
    "projectId": z.uuid(),
"mode": z.string(),
"filterJson": z.string()
    })