/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Wire body of POST /api/v1/projects.
 */
export const createProjectRequestSchema = z
  .object({
    name: z.string(),
    slug: z.string(),
    description: z.nullable(z.string()),
    profilesGitUrl: z.nullable(z.string()),
    profilesGitRef: z.nullable(z.string()),
  })
  .describe("Wire body of POST /api/v1/projects.")
