/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const deleteApiV1IntegrationSourcesSourceidPathParamsSchema = z.object({
  sourceId: z.uuid(),
})

/**
 * @description No Content
 */
export const deleteApiV1IntegrationSourcesSourceid204Schema = z.any()

export const deleteApiV1IntegrationSourcesSourceidMutationResponseSchema =
  z.lazy(() => deleteApiV1IntegrationSourcesSourceid204Schema)
