/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const deleteApiV1AdmissionRulesRuleidPathParamsSchema = z.object({
  ruleId: z.uuid(),
})

/**
 * @description No Content
 */
export const deleteApiV1AdmissionRulesRuleid204Schema = z.any()

export const deleteApiV1AdmissionRulesRuleidMutationResponseSchema = z.lazy(
  () => deleteApiV1AdmissionRulesRuleid204Schema
)
