/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Drift verdict — same shape ProcedureTraceRecorder.ClassifyDrift produces.
 */
export const driftDtoSchema = z
  .object({
    isWithinPolicy: z
      .boolean()
      .describe(
        "True when the observed drift stayed inside the declared tolerance."
      ),
    summary: z.string().describe("Human-readable summary."),
  })
  .describe(
    "Drift verdict — same shape ProcedureTraceRecorder.ClassifyDrift produces."
  )
