/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Reference to an edge in the diff.
 */
export const edgeRefDtoSchema = z
  .object({
    fromNodeId: z.string().describe("Source node id."),
    fromPort: z.string().describe("Source outcome port."),
    toNodeId: z.string().describe("Destination node id."),
  })
  .describe("Reference to an edge in the diff.")
