/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { featureAvailabilityViewSchema } from "./featureAvailabilityViewSchema"
import { limitUsageViewSchema } from "./limitUsageViewSchema"
import { z } from "zod/v4"

/**
 * @description Wire shape of `GET /api/v1/edition` — the dashboard and CLI\'s\r\nread-only projection of the current license state. Anonymous by design\r\n(the dashboard\'s first paint renders an upsell before sign-in), so the\r\nendpoint is intentionally absent any permission / feature / role gates.\r\nThe response carries the live tier code and the current license\r\nstatus (`valid` / `grace` / `expired` / `absent`);\r\nDateTimeOffset? EditionView.ExpiresAt is always present on the wire — null when the\r\nlicense is absent — so the property\'s contract (required+nullable)\r\nmatches what the OpenAPI document declares and generated zod on the\r\nFE expects. The page projects `null` to `undefined` at the\r\nwire→snapshot boundary and still branches on presence there.
 */
export const editionViewSchema = z
  .object({
    tier: z
      .string()
      .describe(
        'Lowercase tier code the license names, or `"community"` when absent.'
      ),
    status: z
      .string()
      .describe("One of `valid` / `grace` / `expired` / `absent`."),
    get features() {
      return z
        .array(
          featureAvailabilityViewSchema.describe(
            "One feature's availability at the current edition. The view is honest\r\nabout every entry — including paid keys under Community, where\r\n`available` is `false` — so the dashboard can render the\r\nright disabled/locked affordance without a second call to the catalog."
          )
        )
        .describe(
          "Every registered feature, with `available` reflecting the current edition."
        )
    },
    get limits() {
      return z
        .array(
          limitUsageViewSchema.describe(
            "One limit's usage against its tier cap. The `current` value comes\r\nfrom the matching ILimitUsageProvider registered in DI;\r\nwhen no provider is registered the view reports `0` rather than\r\nrefusing to answer, because the gate is the source of truth for\r\nenforcement and the view is read-only."
          )
        )
        .describe(
          "Every registered limit, with `cap` from the tier and `current` from the matching `ILimitUsageProvider`."
        )
    },
    version: z
      .string()
      .describe(
        "Lowercase assembly version (`ComukiBuildInformation.Version`) the host boots from."
      ),
    expiresAt: z.nullable(
      z.iso
        .datetime({ offset: true })
        .describe(
          "ISO-8601 UTC expiry from the verified license; `null` when `Status` is `absent`. Always present on the wire."
        )
    ),
  })
  .describe(
    "Wire shape of `GET /api/v1/edition` — the dashboard and CLI's\r\nread-only projection of the current license state. Anonymous by design\r\n(the dashboard's first paint renders an upsell before sign-in), so the\r\nendpoint is intentionally absent any permission / feature / role gates.\r\nThe response carries the live tier code and the current license\r\nstatus (`valid` / `grace` / `expired` / `absent`);\r\nDateTimeOffset? EditionView.ExpiresAt is always present on the wire — null when the\r\nlicense is absent — so the property's contract (required+nullable)\r\nmatches what the OpenAPI document declares and generated zod on the\r\nFE expects. The page projects `null` to `undefined` at the\r\nwire→snapshot boundary and still branches on presence there."
  )
