/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Escalation ratchet from EscalationTimeoutOptions.
 */
export const escalationTimeoutSettingsViewSchema = z
  .object({
    enabled: z
      .boolean()
      .describe(
        "Ops kill-switch — false disables the passive ratchet globally."
      ),
    timeoutSeconds: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("How long a run may sit Escalated before auto-archival."),
    sweepIntervalSeconds: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Ratchet sweep cadence."),
  })
  .describe("Escalation ratchet from EscalationTimeoutOptions.")
