/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One feature\'s availability at the current edition. The view is honest\r\nabout every entry — including paid keys under Community, where\r\n`available` is `false` — so the dashboard can render the\r\nright disabled/locked affordance without a second call to the catalog.
 */
export const featureAvailabilityViewSchema = z
  .object({
    key: z
      .string()
      .describe(
        "The closed-vocabulary feature key (lowercase kebab-case slug; the same string the gate attribute carries)."
      ),
    available: z
      .boolean()
      .describe(
        "True when the current bool IEdition.Has(Feature feature) covers this key."
      ),
  })
  .describe(
    "One feature's availability at the current edition. The view is honest\r\nabout every entry — including paid keys under Community, where\r\n`available` is `false` — so the dashboard can render the\r\nright disabled/locked affordance without a second call to the catalog."
  )
