/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { chatSessionViewSchema } from "./chatSessionViewSchema"
import { z } from "zod/v4"

/**
 * @description OK
 */
export const getApiV1ChatSessions200Schema = z.array(
  z.lazy(() => chatSessionViewSchema)
)

export const getApiV1ChatSessionsQueryResponseSchema = z.lazy(
  () => getApiV1ChatSessions200Schema
)
