/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { admissionRuleViewSchema } from "./admissionRuleViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const getApiV1IntegrationAdmissionRulesRuleidPathParamsSchema = z.object(
  {
    ruleId: z.uuid(),
  }
)

/**
 * @description OK
 */
export const getApiV1IntegrationAdmissionRulesRuleid200Schema = z
  .lazy(() => admissionRuleViewSchema)
  .describe("Read-model of an admission rule.")

/**
 * @description Not Found
 */
export const getApiV1IntegrationAdmissionRulesRuleid404Schema = z.lazy(
  () => problemDetailsSchema
)

export const getApiV1IntegrationAdmissionRulesRuleidQueryResponseSchema =
  z.lazy(() => getApiV1IntegrationAdmissionRulesRuleid200Schema)
