/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { intakeTicketViewSchema } from "./intakeTicketViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const getApiV1InboxCatalogQueryParamsSchema = z.object({
  connectionId: z.optional(z.uuid()),
  page: z
    .union([z.coerce.number().int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
    .default(1),
})

/**
 * @description OK
 */
export const getApiV1InboxCatalog200Schema = z.array(
  z.lazy(() => intakeTicketViewSchema)
)

/**
 * @description Not Found
 */
export const getApiV1InboxCatalog404Schema = z.lazy(() => problemDetailsSchema)

export const getApiV1InboxCatalogQueryResponseSchema = z.lazy(
  () => getApiV1InboxCatalog200Schema
)
