/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const getApiV1AuthOidcProviderStartPathParamsSchema = z.object({
  provider: z.string(),
})

export const getApiV1AuthOidcProviderStartQueryParamsSchema = z
  .object({
    returnTo: z.optional(z.string()),
  })
  .optional()

/**
 * @description Found
 */
export const getApiV1AuthOidcProviderStart302Schema = z.any()

/**
 * @description Not Found
 */
export const getApiV1AuthOidcProviderStart404Schema = z.lazy(
  () => problemDetailsSchema
)

export const getApiV1AuthOidcProviderStartQueryResponseSchema = z.any()
