/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { sourceConnectionViewSchema } from "./sourceConnectionViewSchema"
import { z } from "zod/v4"

export const getApiV1SourcesSourceidPathParamsSchema = z.object({
  sourceId: z.uuid(),
})

/**
 * @description OK
 */
export const getApiV1SourcesSourceid200Schema = z
  .lazy(() => sourceConnectionViewSchema)
  .describe(
    "Read-model of a source connection. Settings and secret env NAMES are\r\nreturned (never secret values) plus the hook path to paste into the\r\ntracker's webhook settings."
  )

/**
 * @description Not Found
 */
export const getApiV1SourcesSourceid404Schema = z.lazy(
  () => problemDetailsSchema
)

export const getApiV1SourcesSourceidQueryResponseSchema = z.lazy(
  () => getApiV1SourcesSourceid200Schema
)
