/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { meResponseSchema } from "./meResponseSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

/**
 * @description OK
 */
export const getApiV1AuthMe200Schema = z.lazy(() => meResponseSchema)

/**
 * @description Unauthorized
 */
export const getApiV1AuthMe401Schema = z.lazy(() => problemDetailsSchema)

export const getApiV1AuthMeQueryResponseSchema = z.lazy(
  () => getApiV1AuthMe200Schema
)
