/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const getApiV1ProjectsProjectidSettingsPathParamsSchema = z.object({
  projectId: z.uuid(),
})

/**
 * @description OK
 */
export const getApiV1ProjectsProjectidSettings200Schema = z
  .lazy(() => projectSettingsViewSchema)
  .describe(
    "Read model of per-project settings. int ProjectSettingsView.Version rides along\r\nso API clients can echo it into the next PUT (optimistic concurrency)."
  )

export const getApiV1ProjectsProjectidSettingsQueryResponseSchema = z.lazy(
  () => getApiV1ProjectsProjectidSettings200Schema
)
