/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { identityAdminGrantsPageSchema } from "./identityAdminGrantsPageSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const getApiV1GrantsQueryParamsSchema = z
  .object({
    SubjectKind: z.optional(
      z
        .string()
        .describe('Optional subject-kind filter (`"user"` or `"api-key"`).')
    ),
    SubjectId: z.optional(z.uuid().describe("Optional subject id filter.")),
    Page: z.optional(
      z
        .union([
          z.coerce.number().int(),
          z.string().regex(/^-?(?:0|[1-9]\d*)$/),
        ])
        .describe("1-based page index; default 1.")
    ),
    PageSize: z.optional(
      z
        .union([
          z.coerce.number().int(),
          z.string().regex(/^-?(?:0|[1-9]\d*)$/),
        ])
        .describe("Page size (1..100); default 100.")
    ),
  })
  .optional()

/**
 * @description OK
 */
export const getApiV1Grants200Schema = z
  .lazy(() => identityAdminGrantsPageSchema)
  .describe("Paged envelope for role assignments.")

/**
 * @description Bad Request
 */
export const getApiV1Grants400Schema = z.lazy(() => problemDetailsSchema)

export const getApiV1GrantsQueryResponseSchema = z.lazy(
  () => getApiV1Grants200Schema
)
