/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { inboundItemViewSchema } from "./inboundItemViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const getApiV1IntegrationInboxCatalogQueryParamsSchema = z.object({
  connectionId: z.optional(z.uuid()),
  page: z
    .union([z.coerce.number().int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
    .default(1)
    .describe("1-based page number."),
})

/**
 * @description OK
 */
export const getApiV1IntegrationInboxCatalog200Schema = z.array(
  z
    .lazy(() => inboundItemViewSchema)
    .describe(
      "Read-model of an intake ticket for the inbox and the API surfaces."
    )
)

/**
 * @description Not Found
 */
export const getApiV1IntegrationInboxCatalog404Schema = z.lazy(
  () => problemDetailsSchema
)

export const getApiV1IntegrationInboxCatalogQueryResponseSchema = z.lazy(
  () => getApiV1IntegrationInboxCatalog200Schema
)
