/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const getApiV1CostsQueryParamsSchema = z
  .object({
    days: z.optional(
      z.union([z.coerce.number().int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
    ),
  })
  .optional()

/**
 * @description OK
 */
export const getApiV1Costs200Schema = z.any()

export const getApiV1CostsQueryResponseSchema = z.lazy(
  () => getApiV1Costs200Schema
)
