/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description OK
 */
export const getApiV1KnowledgeSearch200Schema = z.any()

export const getApiV1KnowledgeSearchQueryResponseSchema = z.lazy(
  () => getApiV1KnowledgeSearch200Schema
)
