/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { inboundItemViewSchema } from "./inboundItemViewSchema"
import { z } from "zod/v4"

export const getApiV1IntegrationInboxQueryParamsSchema = z
  .object({
    projectId: z.optional(z.uuid().describe("Optional project filter.")),
  })
  .optional()

/**
 * @description OK
 */
export const getApiV1IntegrationInbox200Schema = z.array(
  z
    .lazy(() => inboundItemViewSchema)
    .describe(
      "Read-model of an intake ticket for the inbox and the API surfaces."
    )
)

export const getApiV1IntegrationInboxQueryResponseSchema = z.lazy(
  () => getApiV1IntegrationInbox200Schema
)
