/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description OK
 */
export const getApiV1WorkersBackground200Schema = z.any()

export const getApiV1WorkersBackgroundQueryResponseSchema = z.lazy(
  () => getApiV1WorkersBackground200Schema
)
