/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { chatMessagesPageViewSchema } from "./chatMessagesPageViewSchema";
import { problemDetailsSchema } from "./problemDetailsSchema";
import { z } from "zod/v4";

export const getApiV1ChatSessionsSessionidMessagesPathParamsSchema = z.object({
    "sessionId": z.uuid()
    })

export const getApiV1ChatSessionsSessionidMessagesQueryParamsSchema = z.object({
    "page": z.union([z.coerce.number().int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).default(1),
"pageSize": z.union([z.coerce.number().int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]).default(50)
    })

/**
 * @description OK
 */
export const getApiV1ChatSessionsSessionidMessages200Schema = z.lazy(() => chatMessagesPageViewSchema)

/**
 * @description Not Found
 */
export const getApiV1ChatSessionsSessionidMessages404Schema = z.lazy(() => problemDetailsSchema)

export const getApiV1ChatSessionsSessionidMessagesQueryResponseSchema = z.lazy(() => getApiV1ChatSessionsSessionidMessages200Schema)