/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { admissionRuleViewSchema } from "./admissionRuleViewSchema";
import { z } from "zod/v4";

export const getApiV1AdmissionRulesQueryParamsSchema = z.object({
    "projectId": z.optional(z.uuid())
    }).optional()

/**
 * @description OK
 */
export const getApiV1AdmissionRules200Schema = z.array(z.lazy(() => admissionRuleViewSchema))

export const getApiV1AdmissionRulesQueryResponseSchema = z.lazy(() => getApiV1AdmissionRules200Schema)