/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { problemDetailsSchema } from "./problemDetailsSchema";
import { profileDefinitionSchema } from "./profileDefinitionSchema";
import { z } from "zod/v4";

export const getProfilesKeyPathParamsSchema = z.object({
    "key": z.string()
    })

/**
 * @description OK
 */
export const getProfilesKey200Schema = z.lazy(() => profileDefinitionSchema)

/**
 * @description Not Found
 */
export const getProfilesKey404Schema = z.lazy(() => problemDetailsSchema)

export const getProfilesKeyQueryResponseSchema = z.lazy(() => getProfilesKey200Schema)