/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { apiKeyViewSchema } from "./apiKeyViewSchema"
import { z } from "zod/v4"

export const identityAdminKeysPageSchema = z.object({
  get items() {
    return z.array(apiKeyViewSchema)
  },
  total: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
})
