/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Wire row of one search hit — document id, chunk id, snippet and cosine similarity score.
 */
export const knowledgeSearchHitViewSchema = z
  .object({
    documentId: z.uuid().describe("Source document the chunk belongs to."),
    chunkId: z.uuid().describe("The chunk id."),
    snippet: z.string().describe("The chunk text."),
    score: z
      .union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/),
      ])
      .describe("Cosine similarity in [0.0, 1.0] — higher is closer."),
  })
  .describe(
    "Wire row of one search hit — document id, chunk id, snippet and cosine similarity score."
  )
