/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const knowledgeIngestRequestSchema = z.object({
  projectId: z.uuid().nullish(),
  title: z.optional(z.string()),
  source: z.optional(z.string()),
  sourceRef: z.optional(z.string()),
  mimeType: z.optional(z.string()),
  text: z.optional(z.string()),
})
