/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Response body for `POST /api/v1/knowledge/ingest` — the source id + chunk count.
 */
export const knowledgeIngestResponseSchema = z
  .object({
    sourceDocumentId: z
      .string()
      .describe("The `memory.source_documents` row the ingest produced."),
    chunksWritten: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Chunks the chunker split out and persisted with embeddings."),
  })
  .describe(
    "Response body for `POST /api/v1/knowledge/ingest` — the source id + chunk count."
  )
