/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { permissionsViewSchema } from "./permissionsViewSchema"
import { z } from "zod/v4"

export const meResponseSchema = z.object({
  userId: z.nullable(z.uuid()),
  subjectType: z.string(),
  subjectId: z.uuid(),
  email: z.string().nullish(),
  displayName: z.string().nullish(),
  roles: z.array(z.string()),
  get permissions() {
    return permissionsViewSchema
  },
})
