/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const messagePartCodePartSchema = z.object({
  kind: z.optional(z.enum(["code"])),
  language: z.string(),
  source: z.string(),
  path: z.string().nullish(),
  startLine: z
    .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
    .nullish(),
})
