/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const messagePartHandoffPartSchema = z.object({
  kind: z.optional(z.enum(["handoff"])),
  query: z.string(),
})
