/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { messagePartCodePartSchema } from "./messagePartCodePartSchema"
import { messagePartDiagramPartSchema } from "./messagePartDiagramPartSchema"
import { messagePartHandoffPartSchema } from "./messagePartHandoffPartSchema"
import { messagePartPlanPartSchema } from "./messagePartPlanPartSchema"
import { messagePartTextPartSchema } from "./messagePartTextPartSchema"
import { messagePartThinkingPartSchema } from "./messagePartThinkingPartSchema"
import { messagePartToolPartSchema } from "./messagePartToolPartSchema"
import { z } from "zod/v4"

export const messagePartSchema = z.union([
  z
    .lazy(() => messagePartTextPartSchema)
    .and(
      z.object({
        kind: z.literal("text"),
      })
    ),
  z
    .lazy(() => messagePartCodePartSchema)
    .and(
      z.object({
        kind: z.literal("code"),
      })
    ),
  z
    .lazy(() => messagePartDiagramPartSchema)
    .and(
      z.object({
        kind: z.literal("diagram"),
      })
    ),
  z
    .lazy(() => messagePartThinkingPartSchema)
    .and(
      z.object({
        kind: z.literal("thinking"),
      })
    ),
  z
    .lazy(() => messagePartToolPartSchema)
    .and(
      z.object({
        kind: z.literal("tool"),
      })
    ),
  z
    .lazy(() => messagePartHandoffPartSchema)
    .and(
      z.object({
        kind: z.literal("handoff"),
      })
    ),
  z
    .lazy(() => messagePartPlanPartSchema)
    .and(
      z.object({
        kind: z.literal("plan"),
      })
    ),
])
