/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { messagePartCodePartSchema } from "./messagePartCodePartSchema"
import { messagePartDiagramPartSchema } from "./messagePartDiagramPartSchema"
import { messagePartHandoffPartSchema } from "./messagePartHandoffPartSchema"
import { messagePartPlanPartSchema } from "./messagePartPlanPartSchema"
import { messagePartTextPartSchema } from "./messagePartTextPartSchema"
import { messagePartThinkingPartSchema } from "./messagePartThinkingPartSchema"
import { messagePartToolPartSchema } from "./messagePartToolPartSchema"
import { z } from "zod/v4"

/**
 * @description             One fragment of a chat message. A message is an ordered list of parts,\r\n            so a single assistant turn can carry prose, three tool calls and a plan\r\n            card without becoming five unrelated transcript rows.\r\n            The union is closed to nested records (private constructor) and\r\ndiscriminated on the wire by kind — the keys live in\r\nMessagePartKinds. New kinds are added here as further\r\nnested records plus a JsonDerivedTypeAttribute line; the\r\nP2 question/decision parts land exactly that way.
 */
export const messagePartSchema = z
  .union([
    z
      .lazy(() => messagePartTextPartSchema)
      .and(
        z.object({
          kind: z.literal("text"),
        })
      ),
    z
      .lazy(() => messagePartCodePartSchema)
      .and(
        z.object({
          kind: z.literal("code"),
        })
      ),
    z
      .lazy(() => messagePartDiagramPartSchema)
      .and(
        z.object({
          kind: z.literal("diagram"),
        })
      ),
    z
      .lazy(() => messagePartThinkingPartSchema)
      .and(
        z.object({
          kind: z.literal("thinking"),
        })
      ),
    z
      .lazy(() => messagePartToolPartSchema)
      .and(
        z.object({
          kind: z.literal("tool"),
        })
      ),
    z
      .lazy(() => messagePartHandoffPartSchema)
      .and(
        z.object({
          kind: z.literal("handoff"),
        })
      ),
    z
      .lazy(() => messagePartPlanPartSchema)
      .and(
        z.object({
          kind: z.literal("plan"),
        })
      ),
  ])
  .describe(
    "            One fragment of a chat message. A message is an ordered list of parts,\r\n            so a single assistant turn can carry prose, three tool calls and a plan\r\n            card without becoming five unrelated transcript rows.\r\n            The union is closed to nested records (private constructor) and\r\ndiscriminated on the wire by kind — the keys live in\r\nMessagePartKinds. New kinds are added here as further\r\nnested records plus a JsonDerivedTypeAttribute line; the\r\nP2 question/decision parts land exactly that way."
  )
