/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Markdown prose — the default shape of a reply.
 */
export const messagePartTextPartSchema = z
  .object({
    kind: z.optional(z.enum(["text"])),
    markdown: z.string().describe("Message text in markdown."),
  })
  .describe("Markdown prose — the default shape of a reply.")
