/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { planEdgeSchema } from "./planEdgeSchema"
import { planNodeSchema } from "./planNodeSchema"
import { z } from "zod/v4"

export const messagePartPlanPartSchema = z.object({
  kind: z.optional(z.enum(["plan"])),
  get nodes() {
    return z.array(planNodeSchema)
  },
  get edges() {
    return z.array(planEdgeSchema)
  },
})
