/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const messagePartToolPartSchema = z.object({
  kind: z.optional(z.enum(["tool"])),
  name: z.string(),
  inputJson: z.string(),
  status: z.string(),
  outputJson: z.string().nullish(),
  durationMs: z
    .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
    .nullish(),
})
