/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { escalationTimeoutSettingsViewSchema } from "./escalationTimeoutSettingsViewSchema"
import { leaseSettingsViewSchema } from "./leaseSettingsViewSchema"
import { z } from "zod/v4"

/**
 * @description Orchestration policy as bound from `Orchestration:*`.
 */
export const orchestrationSettingsViewSchema = z
  .object({
    get lease() {
      return leaseSettingsViewSchema.describe(
        "Claim/lease policy from LeaseOptions."
      )
    },
    get escalationTimeout() {
      return escalationTimeoutSettingsViewSchema.describe(
        "Escalation ratchet from EscalationTimeoutOptions."
      )
    },
  })
  .describe("Orchestration policy as bound from `Orchestration:*`.")
