/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One parameter delta inside a re-parameterized node.
 */
export const parameterChangeDtoSchema = z
  .object({
    name: z.string().describe("Parameter key (kind-declared name)."),
    before: z.nullable(z.string().describe("Old value (null when added).")),
    after: z.nullable(z.string().describe("New value (null when removed).")),
  })
  .describe("One parameter delta inside a re-parameterized node.")
