/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { setUserDisabledRequestSchema } from "./setUserDisabledRequestSchema"
import { userAccountViewSchema } from "./userAccountViewSchema"
import { z } from "zod/v4"

export const patchApiV1UsersUseridPathParamsSchema = z.object({
  userId: z.uuid(),
})

/**
 * @description OK
 */
export const patchApiV1UsersUserid200Schema = z
  .lazy(() => userAccountViewSchema)
  .describe("Read model of a user account — no secrets ride along.")

/**
 * @description Bad Request
 */
export const patchApiV1UsersUserid400Schema = z.lazy(() => problemDetailsSchema)

/**
 * @description Not Found
 */
export const patchApiV1UsersUserid404Schema = z.lazy(() => problemDetailsSchema)

export const patchApiV1UsersUseridMutationRequestSchema = z
  .lazy(() => setUserDisabledRequestSchema)
  .describe("Toggle the disabled flag (PATCH /api/v1/users/{userId}).")

export const patchApiV1UsersUseridMutationResponseSchema = z.lazy(
  () => patchApiV1UsersUserid200Schema
)
