/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateProjectRequestSchema } from "./updateProjectRequestSchema"
import { z } from "zod/v4"

export const patchApiV1ProjectsProjectidPathParamsSchema = z.object({
  projectId: z.uuid(),
})

/**
 * @description OK
 */
export const patchApiV1ProjectsProjectid200Schema = z.any()

export const patchApiV1ProjectsProjectidMutationRequestSchema = z
  .lazy(() => updateProjectRequestSchema)
  .describe(
    "Wire body of PATCH /api/v1/projects/{projectId} — null fields are left untouched."
  )

export const patchApiV1ProjectsProjectidMutationResponseSchema = z.lazy(
  () => patchApiV1ProjectsProjectid200Schema
)
