/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const permissionsViewSchema = z.object({
    "platform": z.array(z.string()),
"projects": z.object({
    
    }).catchall(z.array(z.string()))
    })