/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const postApiV1WorkersWorkeridDrainPathParamsSchema = z.object({
  workerId: z.uuid(),
})

/**
 * @description OK
 */
export const postApiV1WorkersWorkeridDrain200Schema = z.any()

export const postApiV1WorkersWorkeridDrainMutationResponseSchema = z.lazy(
  () => postApiV1WorkersWorkeridDrain200Schema
)
