/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { secretRotationResponseSchema } from "./secretRotationResponseSchema"
import { z } from "zod/v4"

export const postApiV1SourcesSourceidRotateSecretPathParamsSchema = z.object({
  sourceId: z.uuid(),
})

/**
 * @description OK
 */
export const postApiV1SourcesSourceidRotateSecret200Schema = z.lazy(
  () => secretRotationResponseSchema
)

/**
 * @description Not Found
 */
export const postApiV1SourcesSourceidRotateSecret404Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1SourcesSourceidRotateSecretMutationResponseSchema =
  z.lazy(() => postApiV1SourcesSourceidRotateSecret200Schema)
