/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createNativeInboundItemRequestSchema } from "./createNativeInboundItemRequestSchema"
import { inboundItemViewSchema } from "./inboundItemViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

/**
 * @description Created
 */
export const postApiV1IntegrationItems201Schema = z
  .lazy(() => inboundItemViewSchema)
  .describe(
    "Read-model of an intake ticket for the inbox and the API surfaces."
  )

/**
 * @description Bad Request
 */
export const postApiV1IntegrationItems400Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Conflict
 */
export const postApiV1IntegrationItems409Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1IntegrationItemsMutationRequestSchema = z
  .lazy(() => createNativeInboundItemRequestSchema)
  .describe("Native ticket creation body (POST /api/v1/tickets).")

export const postApiV1IntegrationItemsMutationResponseSchema = z.lazy(
  () => postApiV1IntegrationItems201Schema
)
