/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { steerRunRequestSchema } from "./steerRunRequestSchema"
import { steerRunResponseSchema } from "./steerRunResponseSchema"
import { z } from "zod/v4"

export const postApiV1RunsRunidSteerPathParamsSchema = z.object({
  runId: z.uuid().describe("Run to steer."),
})

/**
 * @description Accepted
 */
export const postApiV1RunsRunidSteer202Schema = z
  .lazy(() => steerRunResponseSchema)
  .describe(
    "Response of `POST /api/v1/runs/{runId}/steer`. On the Phase 1a\r\n(no-LiveSession) runtime bool SteerRunResponse.Delivered is always\r\n`true` and Guid? SteerRunResponse.FollowUpWorkItemId carries the id of\r\nthe queued follow-up WorkItem the handler staged. On a future\r\nLiveSession runtime (Phase 1c) bool SteerRunResponse.Delivered reports\r\nwhether the bidi channel accepted the typed turn and\r\nGuid? SteerRunResponse.FollowUpWorkItemId is omitted (the harness, not a\r\nnew work item, carries the authoritative turn)."
  )

/**
 * @description Bad Request
 */
export const postApiV1RunsRunidSteer400Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Forbidden
 */
export const postApiV1RunsRunidSteer403Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Not Found
 */
export const postApiV1RunsRunidSteer404Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Conflict
 */
export const postApiV1RunsRunidSteer409Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1RunsRunidSteerMutationRequestSchema = z
  .lazy(() => steerRunRequestSchema)
  .describe(
    "Body of `POST /api/v1/runs/{runId}/steer` (add-orchestra §1 — Baton).\r\nCarries the operator's steer text — the same text the live\r\n`WorkerCommandHandler` appends to the worker's\r\n`comuki-injected-context.md`, and the same text the Phase 1a\r\nfollow-up WorkItem's `brief` reproduces. The follow-up is the\r\nno-LiveSession runtime's only way to surface the steer to a fresh\r\nworker after the reaper reclaims a dead lease."
  )

export const postApiV1RunsRunidSteerMutationResponseSchema = z.lazy(
  () => postApiV1RunsRunidSteer202Schema
)
