/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description No Content
 */
export const postApiV1AuthLogout204Schema = z.any()

export const postApiV1AuthLogoutMutationResponseSchema = z.lazy(() => postApiV1AuthLogout204Schema)