/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { secretRotationResponseSchema } from "./secretRotationResponseSchema"
import { z } from "zod/v4"

export const postApiV1IntegrationSourcesSourceidRotateSecretPathParamsSchema =
  z.object({
    sourceId: z.uuid(),
  })

/**
 * @description OK
 */
export const postApiV1IntegrationSourcesSourceidRotateSecret200Schema = z
  .lazy(() => secretRotationResponseSchema)
  .describe(
    "Wire shape of a secret-rotation result (issue #46). Carries the\r\nfreshly-generated secret exactly once — the operator needs it to\r\nconfigure the tracker; it does not appear in any other endpoint\r\nresponse (list / get / source-connection-view)."
  )

/**
 * @description Not Found
 */
export const postApiV1IntegrationSourcesSourceidRotateSecret404Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1IntegrationSourcesSourceidRotateSecretMutationResponseSchema =
  z.lazy(() => postApiV1IntegrationSourcesSourceidRotateSecret200Schema)
