/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { linkOidcRequestSchema } from "./linkOidcRequestSchema"
import { oidcLinkViewSchema } from "./oidcLinkViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const postApiV1UsersUseridOidcLinkPathParamsSchema = z.object({
  userId: z.uuid(),
})

/**
 * @description Created
 */
export const postApiV1UsersUseridOidcLink201Schema = z.lazy(
  () => oidcLinkViewSchema
)

/**
 * @description Bad Request
 */
export const postApiV1UsersUseridOidcLink400Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Not Found
 */
export const postApiV1UsersUseridOidcLink404Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Conflict
 */
export const postApiV1UsersUseridOidcLink409Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1UsersUseridOidcLinkMutationRequestSchema = z.lazy(
  () => linkOidcRequestSchema
)

export const postApiV1UsersUseridOidcLinkMutationResponseSchema = z.lazy(
  () => postApiV1UsersUseridOidcLink201Schema
)
