/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createProjectRequestSchema } from "./createProjectRequestSchema"
import { z } from "zod/v4"

/**
 * @description OK
 */
export const postApiV1Projects200Schema = z.any()

export const postApiV1ProjectsMutationRequestSchema = z.lazy(
  () => createProjectRequestSchema
)

export const postApiV1ProjectsMutationResponseSchema = z.lazy(
  () => postApiV1Projects200Schema
)
