/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const postApiV1LearningCandidatesCandidateidApprovePathParamsSchema =
  z.object({
    candidateId: z.uuid().describe("Candidate to approve."),
  })

/**
 * @description No Content
 */
export const postApiV1LearningCandidatesCandidateidApprove204Schema = z.any()

/**
 * @description Not Found
 */
export const postApiV1LearningCandidatesCandidateidApprove404Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Conflict
 */
export const postApiV1LearningCandidatesCandidateidApprove409Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1LearningCandidatesCandidateidApproveMutationResponseSchema =
  z.lazy(() => postApiV1LearningCandidatesCandidateidApprove204Schema)
