/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const postWorkersWorkitemidHeartbeatPathParamsSchema = z.object({
  workItemId: z.uuid(),
})

/**
 * @description OK
 */
export const postWorkersWorkitemidHeartbeat200Schema = z.any()

export const postWorkersWorkitemidHeartbeatMutationResponseSchema = z.lazy(
  () => postWorkersWorkitemidHeartbeat200Schema
)
