/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { proposePatchRequestSchema } from "./proposePatchRequestSchema"
import { proposedPatchResponseSchema } from "./proposedPatchResponseSchema"
import { z } from "zod/v4"

export const postApiV1ProceduresProjectidProcedurekeyProposePatchPathParamsSchema =
  z.object({
    projectId: z.uuid().describe("The project the procedure belongs to."),
    procedureKey: z.string().describe("Stable key identifying the procedure."),
  })

/**
 * @description OK
 */
export const postApiV1ProceduresProjectidProcedurekeyProposePatch200Schema = z
  .lazy(() => proposedPatchResponseSchema)
  .describe(
    "Response DTO for a proposed patch\r\n(`POST /api/v1/procedures/{projectId}/{procedureKey}/propose-patch`).\r\nThe chat surface has no publication path — the human publishes from\r\nStudio after reviewing the rendered diff."
  )

/**
 * @description Bad Request
 */
export const postApiV1ProceduresProjectidProcedurekeyProposePatch400Schema =
  z.lazy(() => problemDetailsSchema)

/**
 * @description Cooperative cancellation.
 */
export const postApiV1ProceduresProjectidProcedurekeyProposePatchMutationRequestSchema =
  z
    .lazy(() => proposePatchRequestSchema)
    .describe(
      "Request DTO for proposing a patch from chat\r\n(`POST /api/v1/procedures/{projectId}/{procedureKey}/propose-patch`).\r\nThe chat surface calls this when an operator asks for a procedure\r\nchange in chat — the brain drafts a `GraphPatch` via the\r\nProposePatchFromChatHandler\r\nand the human publishes it from Studio."
    )

export const postApiV1ProceduresProjectidProcedurekeyProposePatchMutationResponseSchema =
  z.lazy(() => postApiV1ProceduresProjectidProcedurekeyProposePatch200Schema)
