/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { sourceProbeResultSchema } from "./sourceProbeResultSchema"
import { z } from "zod/v4"

export const postApiV1IntegrationSourcesSourceidProbePathParamsSchema =
  z.object({
    sourceId: z.uuid(),
  })

/**
 * @description OK
 */
export const postApiV1IntegrationSourcesSourceidProbe200Schema = z
  .lazy(() => sourceProbeResultSchema)
  .describe(
    "The outcome of a probe — does the upstream answer, how fast, what id\r\nwould the host suggest for a follow-up create. The `latencyMs`\r\nis measured end-to-end (HTTP request to first response byte) and is\r\nonly meaningful when `reachable` is true."
  )

/**
 * @description Not Found
 */
export const postApiV1IntegrationSourcesSourceidProbe404Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1IntegrationSourcesSourceidProbeMutationResponseSchema =
  z.lazy(() => postApiV1IntegrationSourcesSourceidProbe200Schema)
