/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { claimTicketRequestSchema } from "./claimTicketRequestSchema"
import { intakeTicketViewSchema } from "./intakeTicketViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

/**
 * @description OK
 */
export const postApiV1InboxClaim200Schema = z
  .lazy(() => intakeTicketViewSchema)
  .describe(
    "Read-model of an intake ticket for the inbox and the API surfaces."
  )

/**
 * @description Bad Request
 */
export const postApiV1InboxClaim400Schema = z.lazy(() => problemDetailsSchema)

/**
 * @description Not Found
 */
export const postApiV1InboxClaim404Schema = z.lazy(() => problemDetailsSchema)

/**
 * @description Conflict
 */
export const postApiV1InboxClaim409Schema = z.lazy(() => problemDetailsSchema)

export const postApiV1InboxClaimMutationRequestSchema = z
  .lazy(() => claimTicketRequestSchema)
  .describe("Inbox claim body (POST /api/v1/inbox/claim).")

export const postApiV1InboxClaimMutationResponseSchema = z.lazy(
  () => postApiV1InboxClaim200Schema
)
