/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { claimWorkItemRequestSchema } from "./claimWorkItemRequestSchema";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const postWorkersClaim200Schema = z.any()

export const postWorkersClaimMutationRequestSchema = z.lazy(() => claimWorkItemRequestSchema)

export const postWorkersClaimMutationResponseSchema = z.lazy(() => postWorkersClaim200Schema)