/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { publicationRequestDtoSchema } from "./publicationRequestDtoSchema"
import { publicationResponseSchema } from "./publicationResponseSchema"
import { z } from "zod/v4"

export const postApiV1ProceduresProjectidProcedurekeyPublishPathParamsSchema =
  z.object({
    projectId: z.uuid().describe("The project the procedure belongs to."),
    procedureKey: z.string().describe("Stable key identifying the procedure."),
  })

/**
 * @description OK
 */
export const postApiV1ProceduresProjectidProcedurekeyPublish200Schema = z
  .lazy(() => publicationResponseSchema)
  .describe(
    "Response DTO for the publish endpoint — the new compiled\r\n    version the publication produced, surfaced as the canonical\r\n    `ProcedureVersionResponse` so Studio can re-fetch the\r\n    published graph by id."
  )

/**
 * @description Bad Request
 */
export const postApiV1ProceduresProjectidProcedurekeyPublish400Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Cooperative cancellation.
 */
export const postApiV1ProceduresProjectidProcedurekeyPublishMutationRequestSchema =
  z
    .lazy(() => publicationRequestDtoSchema)
    .describe(
      "    Request DTO for the human-publish endpoint\r\n    (`POST /api/v1/procedures/{projectId}/{procedureKey}/publish`).\r\n    Carries the full publication payload — patch, layered procedure,\r\n    policy context, approver — because the wire shape is the only\r\n    stable contract between Studio and the host's publication service.\r\n\r\n    The brain cannot reach this endpoint; the brain drafts patches\r\n(POST /propose-patch) and the human publishes them. The\r\nin-process crown e2e (PHASE 3) calls IPublicationService.PublishAsync\r\ndirectly via DI; this wire endpoint exists for Studio and any future\r\nStudio-driven publishing UI.\r\n\r\n    The patch + layered procedure arrive as JsonElements\r\nbecause the domain types are not directly wire-serializable\r\n(records with private setters, nested record types the kubb\r\ngenerator cannot introspect). The host deserializes each element\r\nvia JsonSerializer on its way to the publication\r\nservice."
    )

export const postApiV1ProceduresProjectidProcedurekeyPublishMutationResponseSchema =
  z.lazy(() => postApiV1ProceduresProjectidProcedurekeyPublish200Schema)
