/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Post-message request body: one chat turn.
 */
export const postChatMessageRequestSchema = z
  .object({
    message: z
      .string()
      .describe("Raw user message (plain text or a /command)."),
  })
  .describe("Post-message request body: one chat turn.")
