/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const postWorkersWorkitemidArtifactsPathParamsSchema = z.object({
  workItemId: z.uuid(),
})

/**
 * @description OK
 */
export const postWorkersWorkitemidArtifacts200Schema = z.any()

export const postWorkersWorkitemidArtifactsMutationResponseSchema = z.lazy(
  () => postWorkersWorkitemidArtifacts200Schema
)
