/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { webhookAcceptedResponseSchema } from "./webhookAcceptedResponseSchema"
import { z } from "zod/v4"

export const postApiHooksProviderKeyPathParamsSchema = z.object({
  provider: z
    .string()
    .describe(
      "Kebab-case source key (github | gitlab | yandex-tracker | jira)."
    ),
  key: z.string().describe("Per-connection webhook routing key."),
})

/**
 * @description OK
 */
export const postApiHooksProviderKey200Schema = z
  .lazy(() => webhookAcceptedResponseSchema)
  .describe("The 200 body of a processed (or deliberately ignored) delivery.")

/**
 * @description Unauthorized
 */
export const postApiHooksProviderKey401Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Not Found
 */
export const postApiHooksProviderKey404Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiHooksProviderKeyMutationResponseSchema = z.lazy(
  () => postApiHooksProviderKey200Schema
)
