/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { chatApproveRequestSchema } from "./chatApproveRequestSchema"
import { chatTurnResultViewSchema } from "./chatTurnResultViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { z } from "zod/v4"

export const postApiV1ChatSessionsSessionidApprovePathParamsSchema = z.object({
  sessionId: z.uuid(),
})

/**
 * @description OK
 */
export const postApiV1ChatSessionsSessionidApprove200Schema = z
  .lazy(() => chatTurnResultViewSchema)
  .describe(
    "Turn outcome: the reply view plus the pending approve card when the\r\nthread interrupted. The card carries the canonical plan JSON the\r\ndashboard renders; approve/reject posts to\r\n`/api/v1/chat/sessions/{id}/approve`."
  )

/**
 * @description Not Found
 */
export const postApiV1ChatSessionsSessionidApprove404Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Conflict
 */
export const postApiV1ChatSessionsSessionidApprove409Schema = z.lazy(
  () => problemDetailsSchema
)

/**
 * @description Service Unavailable
 */
export const postApiV1ChatSessionsSessionidApprove503Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1ChatSessionsSessionidApproveMutationRequestSchema = z
  .lazy(() => chatApproveRequestSchema)
  .describe("Approve-request body: resolves the pending plan interrupt.")

export const postApiV1ChatSessionsSessionidApproveMutationResponseSchema =
  z.lazy(() => postApiV1ChatSessionsSessionidApprove200Schema)
