/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { roleAssignmentViewSchema } from "./roleAssignmentViewSchema"
import { z } from "zod/v4"

export const postApiV1GrantsGrantidRevokePathParamsSchema = z.object({
  grantId: z.uuid(),
})

/**
 * @description OK
 */
export const postApiV1GrantsGrantidRevoke200Schema = z.lazy(
  () => roleAssignmentViewSchema
)

/**
 * @description Not Found
 */
export const postApiV1GrantsGrantidRevoke404Schema = z.lazy(
  () => problemDetailsSchema
)

export const postApiV1GrantsGrantidRevokeMutationResponseSchema = z.lazy(
  () => postApiV1GrantsGrantidRevoke200Schema
)
