/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const probeSourceDraftRequestSchema = z.object({
  provider: z.string(),
  settingsJson: z.string(),
  secretEnvRef: z.string(),
})
