/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One node of the compiled graph (a kind key + parameters).
 */
export const procedureNodeDtoSchema = z
  .object({
    id: z
      .string()
      .describe("Graph-local identifier (edge-anchors point at it)."),
    kindKey: z.string().describe("Catalog kind the node instances."),
    parameters: z
      .object({})
      .catchall(z.string())
      .describe("Per-kind parameter overrides."),
  })
  .describe("One node of the compiled graph (a kind key + parameters).")
