/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Strong-typed identifier of a project — the scope unit for runs, work items,\r\nsettings and role assignments.
 */
export const projectIdSchema = z
  .object({
    value: z.optional(z.uuid()),
  })
  .describe(
    "Strong-typed identifier of a project — the scope unit for runs, work items,\r\nsettings and role assignments."
  )
