/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projectIdSchema } from "./projectIdSchema"
import { z } from "zod/v4"

/**
 * @description Read model of a project — everything the operational UI needs, nothing\r\ninternal. Identity fields arrive display-ready: the colour is lower-case\r\n`#rrggbb`, tags are trimmed/lower-cased/deduplicated, the icon is an\r\nopaque string (emoji or URL) to render verbatim.
 */
export const projectViewSchema = z
  .object({
    get id() {
      return projectIdSchema.describe(
        "Strong-typed identifier of a project — the scope unit for runs, work items,\r\nsettings and role assignments."
      )
    },
    name: z.string(),
    slug: z.string(),
    description: z.nullable(z.string()),
    profilesGitUrl: z.nullable(z.string()),
    profilesGitRef: z.nullable(z.string()),
    sourceGitUrl: z.nullable(z.string()),
    sourceGitRef: z.nullable(z.string()),
    icon: z.nullable(z.string()),
    color: z.nullable(z.string()),
    tags: z.array(z.string()),
    envClass: z.nullable(
      z
        .string()
        .describe(
          'Environment-class id the scalar source repository binds to (catalog id, e.g. `"net10-sdk-bun"`);\r\nnull when the project has no confirmed class. Mirrors the\r\n`Project.EnvClass` stand-in (add-worker-environments task 2.2):\r\nan empty binding means implement work items for the project are not claimable.'
        )
    ),
    archived: z.boolean(),
    archivedAt: z.nullable(z.iso.datetime({ offset: true })),
    createdAt: z.iso.datetime({ offset: true }),
    updatedAt: z.iso.datetime({ offset: true }),
  })
  .describe(
    "Read model of a project — everything the operational UI needs, nothing\r\ninternal. Identity fields arrive display-ready: the colour is lower-case\r\n`#rrggbb`, tags are trimmed/lower-cased/deduplicated, the icon is an\r\nopaque string (emoji or URL) to render verbatim."
  )
