/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { admissionRuleViewSchema } from "./admissionRuleViewSchema"
import { problemDetailsSchema } from "./problemDetailsSchema"
import { updateAdmissionRuleRequestSchema } from "./updateAdmissionRuleRequestSchema"
import { z } from "zod/v4"

export const putApiV1IntegrationAdmissionRulesRuleidPathParamsSchema = z.object(
  {
    ruleId: z.uuid(),
  }
)

/**
 * @description OK
 */
export const putApiV1IntegrationAdmissionRulesRuleid200Schema = z
  .lazy(() => admissionRuleViewSchema)
  .describe("Read-model of an admission rule.")

/**
 * @description Not Found
 */
export const putApiV1IntegrationAdmissionRulesRuleid404Schema = z.lazy(
  () => problemDetailsSchema
)

export const putApiV1IntegrationAdmissionRulesRuleidMutationRequestSchema = z
  .lazy(() => updateAdmissionRuleRequestSchema)
  .describe(
    "Admission rule partial update body (PUT /api/v1/admission-rules/{id})."
  )

export const putApiV1IntegrationAdmissionRulesRuleidMutationResponseSchema =
  z.lazy(() => putApiV1IntegrationAdmissionRulesRuleid200Schema)
