/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { sourceConnectionViewSchema } from "./sourceConnectionViewSchema"
import { updateSourceConnectionRequestSchema } from "./updateSourceConnectionRequestSchema"
import { z } from "zod/v4"

export const putApiV1SourcesSourceidPathParamsSchema = z.object({
  sourceId: z.uuid(),
})

/**
 * @description OK
 */
export const putApiV1SourcesSourceid200Schema = z
  .lazy(() => sourceConnectionViewSchema)
  .describe(
    "Read-model of a source connection. Settings and secret env NAMES are\r\nreturned (never secret values) plus the hook path to paste into the\r\ntracker's webhook settings."
  )

/**
 * @description Not Found
 */
export const putApiV1SourcesSourceid404Schema = z.lazy(
  () => problemDetailsSchema
)

export const putApiV1SourcesSourceidMutationRequestSchema = z
  .lazy(() => updateSourceConnectionRequestSchema)
  .describe("Source connection partial update body (PUT /api/v1/sources/{id}).")

export const putApiV1SourcesSourceidMutationResponseSchema = z.lazy(
  () => putApiV1SourcesSourceid200Schema
)
