/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { artifactPointerSchema } from "./artifactPointerSchema"
import { z } from "zod/v4"

export const runArtifactsPageSchema = z.object({
  get items() {
    return z.array(artifactPointerSchema)
  },
  projectId: z.uuid(),
  runId: z.uuid(),
})
