/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Wire row for one journal event in the run timeline (newest first).
 */
export const runDetailEventSchema = z
  .object({
    id: z.uuid().describe("Event id."),
    workItemId: z.nullable(
      z
        .uuid()
        .describe("Work-item the entry is about, when the payload carries one.")
    ),
    type: z.string().describe("Stable dot.case event type."),
    occurredAt: z.iso
      .datetime({ offset: true })
      .describe("When the entry happened."),
    payloadJson: z.nullable(
      z.string().describe("Raw payload JSON, or null when omitted.")
    ),
  })
  .describe(
    "Wire row for one journal event in the run timeline (newest first)."
  )
