/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const runDetailEventSchema = z.object({
  id: z.uuid(),
  workItemId: z.nullable(z.uuid()),
  type: z.string(),
  occurredAt: z.iso.datetime({ offset: true }),
  payloadJson: z.nullable(z.string()),
})
