/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { runArtifactsPageSchema } from "./runArtifactsPageSchema"
import { z } from "zod/v4"

export const runsArtifactsPathParamsSchema = z.object({
  projectId: z.uuid(),
  runId: z.uuid(),
})

/**
 * @description OK
 */
export const runsArtifacts200Schema = z.lazy(() => runArtifactsPageSchema)

/**
 * @description Not Found
 */
export const runsArtifacts404Schema = z.lazy(() => problemDetailsSchema)

export const runsArtifactsQueryResponseSchema = z.lazy(
  () => runsArtifacts200Schema
)
