/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { runDetailSchema } from "./runDetailSchema"
import { z } from "zod/v4"

export const runsGetByIdPathParamsSchema = z.object({
  runId: z.uuid(),
})

/**
 * @description OK
 */
export const runsGetById200Schema = z.lazy(() => runDetailSchema)

/**
 * @description Not Found
 */
export const runsGetById404Schema = z.lazy(() => problemDetailsSchema)

export const runsGetByIdQueryResponseSchema = z.lazy(() => runsGetById200Schema)
