/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { runViewSchema } from "./runViewSchema"
import { z } from "zod/v4"

export const runsPageSchema = z.object({
  get items() {
    return z.array(runViewSchema)
  },
  page: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  pageSize: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
  total: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
})
