/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { verificationGateViewSchema } from "./verificationGateViewSchema"
import { z } from "zod/v4"

/**
 * @description Run-level wire shape for `GET /api/v1/runs/{runId}/verification`\n(add-orchestra §3 — Coda, `verification/spec.md` Requirement\n\"Verification view is a derived read\"). The two top-level booleans\nsurface the \"verification pending\" annotation the FE renders as a\npill under the run\'s status strip; the per-gate list renders as the\nevidence drill-down beneath it. The semantics are derived from the\nIReadOnlyList&lt;VerificationGateView&gt; RunVerificationView.Gates list alone — a future per-project\n`VerifyEnabled` read is gated on the registry returning at\nleast one record (the project is provably opted in if a provider\nhas stamped anything).
 */
export const runVerificationViewSchema = z
  .object({
    runId: z.uuid().describe("Run the verdicts belong to."),
    verified: z
      .boolean()
      .describe(
        "`true` when every gate in IReadOnlyList&lt;VerificationGateView&gt; RunVerificationView.Gates is\n`passed` AND at least one gate has been evaluated — the run's\nverification axis is fully terminal and positive. A run with no\ngates yet, with mixed `passed`/`pending`, or with any\n`failed` is `false`."
      ),
    verificationPending: z
      .boolean()
      .describe(
        '`true` when at least one gate is still `pending`\nAND the run is not yet fully verified — the "verification pending"\nannotation the spec introduces. Terminal failures do NOT count as\npending: a run with one `pending` and one `failed` gate\nis `pending=true`; a run with only `failed` is\n`pending=false`.'
      ),
    get gates() {
      return z
        .array(
          verificationGateViewSchema.describe(
            "Per-gate wire shape for `GET /api/v1/runs/{runId}/verification`.\nThe verdict string is the lower-case `GateVerdict` smart-type\nname (`pending` / `passed` / `failed`); the evidence URI\nis returned as a plain string so the FE can resolve it through the\nexisting artifact endpoint without the engine re-encoding the URL."
          )
        )
        .describe(
          "One entry per evaluated (work item, gate) pair. Newest first within a work item."
        )
    },
  })
  .describe(
    'Run-level wire shape for `GET /api/v1/runs/{runId}/verification`\n(add-orchestra §3 — Coda, `verification/spec.md` Requirement\n"Verification view is a derived read"). The two top-level booleans\nsurface the "verification pending" annotation the FE renders as a\npill under the run\'s status strip; the per-gate list renders as the\nevidence drill-down beneath it. The semantics are derived from the\nIReadOnlyList&lt;VerificationGateView&gt; RunVerificationView.Gates list alone — a future per-project\n`VerifyEnabled` read is gated on the registry returning at\nleast one record (the project is provably opted in if a provider\nhas stamped anything).'
  )
