/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { scheduledJobViewSchema } from "./scheduledJobViewSchema"
import { z } from "zod/v4"

export const scheduledJobsPageSchema = z.object({
  get items() {
    return z.array(scheduledJobViewSchema)
  },
  total: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
})
