/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One `validate_against` entry shaped like a Context Fabric `SourceRef`:\r\n`kind` (e.g. `knowledge`, `control`) plus the ref id\r\n(e.g. `doc/citation-style@v3`). The catalog never resolves the ref\r\nitself; the brain interprets the kind and id when the skill is selected.
 */
export const skillValidateAgainstTargetSchema = z
  .object({
    kind: z.string().describe("SourceRef kind."),
    id: z.string().describe("SourceRef id, scoped to the kind."),
  })
  .describe(
    "One `validate_against` entry shaped like a Context Fabric `SourceRef`:\r\n`kind` (e.g. `knowledge`, `control`) plus the ref id\r\n(e.g. `doc/citation-style@v3`). The catalog never resolves the ref\r\nitself; the brain interprets the kind and id when the skill is selected."
  )
