/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One trace event in the wire shape.
 */
export const traceEventDtoSchema = z
  .object({
    nodeId: z
      .string()
      .describe(
        "The graph node (or version id for a pin event) the event relates to."
      ),
    eventType: z
      .string()
      .describe(
        "planned / started / completed / failed / gate_opened / gate_resolved / generation_opened / generation_exhausted / late_result / pin_recorded."
      ),
    detail: z.string().describe("Human-readable detail."),
    at: z.iso
      .datetime({ offset: true })
      .describe("When the event was recorded (UTC, ISO 8601)."),
  })
  .describe("One trace event in the wire shape.")
