/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const updateScheduledJobRequestSchema = z.object({
  cronExpression: z.string().nullish(),
  briefJson: z.string().nullish(),
  enabled: z.boolean().nullish(),
})
