/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { runIdSchema } from "./runIdSchema"
import { z } from "zod/v4"

/**
 * @description One usage row in the costs feed.
 */
export const usageEventViewSchema = z
  .object({
    id: z.uuid(),
    get runId() {
      return z.union([runIdSchema, z.null()])
    },
    source: z.string(),
    model: z.string(),
    inputTokens: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
    outputTokens: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
    costUsdMicros: z.union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)]),
    occurredAt: z.iso.datetime({ offset: true }),
  })
  .describe("One usage row in the costs feed.")
