/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { workCapabilityDescriptorSchema } from "./workCapabilityDescriptorSchema"
import { z } from "zod/v4"

/**
 * @description Capability catalogue response — the static WorkCapabilities\nenumerated for the Capability Broker (the umbrella\'s #90 work).\nRead-only, permission work:read.
 */
export const workCapabilitiesViewSchema = z
  .object({
    get capabilities() {
      return z
        .array(
          workCapabilityDescriptorSchema.describe(
            "Stable contract identifier for one capability the Work module\nadvertises. The descriptor is immutable; consumers compare\ninstances by string WorkCapabilityDescriptor.Name (case-sensitive, ordinal)."
          )
        )
        .describe("Stable contract descriptors in declaration order.")
    },
  })
  .describe(
    "Capability catalogue response — the static WorkCapabilities\nenumerated for the Capability Broker (the umbrella's #90 work).\nRead-only, permission work:read."
  )
