/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Stable contract identifier for one capability the Work module\nadvertises. The descriptor is immutable; consumers compare\ninstances by string WorkCapabilityDescriptor.Name (case-sensitive, ordinal).
 */
export const workCapabilityDescriptorSchema = z
  .object({
    name: z
      .string()
      .describe(
        'Stable dot.case identifier — see `add-mission-cowork/design.md` §"Capability naming".'
      ),
    description: z
      .string()
      .describe(
        "Short human-readable description, surfaced verbatim by the Broker probe."
      ),
  })
  .describe(
    "Stable contract identifier for one capability the Work module\nadvertises. The descriptor is immutable; consumers compare\ninstances by string WorkCapabilityDescriptor.Name (case-sensitive, ordinal)."
  )
