/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailsSchema } from "./problemDetailsSchema"
import { workTaskRunViewSchema } from "./workTaskRunViewSchema"
import { z } from "zod/v4"

export const workTasksRunViewPathParamsSchema = z.object({
  taskId: z.uuid().describe("WorkTask id (path)."),
})

/**
 * @description OK
 */
export const workTasksRunView200Schema = z
  .lazy(() => workTaskRunViewSchema)
  .describe(
    'Run-shaped compatibility projection of a WorkTask\'s current attempt —\nthe umbrella\'s `add-work-management` design §"Run-consumer\ncompatibility projection". Shape-compatible with the pre-`WorkTask`\n`GET /api/v1/runs/{runId}` response and includes the\nauthoritative `taskId` field. 404 when the requested attempt\nhas been fenced by a replacement (per the design\'s\n"Superseded attempt returns 404" scenario).'
  )

/**
 * @description Not Found
 */
export const workTasksRunView404Schema = z.lazy(() => problemDetailsSchema)

export const workTasksRunViewQueryResponseSchema = z.lazy(
  () => workTasksRunView200Schema
)
