/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { workTaskSourceRefViewSchema } from "./workTaskSourceRefViewSchema"
import { z } from "zod/v4"

/**
 * @description Per-Task detail projection — the `GET /api/v1/work/tasks/{taskId}`\nresponse shape (the umbrella\'s `add-work-management` design\n§\"Work API\"). Caller-facing fields only — no aggregate internals.
 */
export const workTaskDetailViewSchema = z
  .object({
    id: z.uuid().describe("Strong-typed task id (UUIDv7 string form)."),
    projectId: z.uuid().describe("Owning project id."),
    title: z.string().describe("Task title."),
    brief: z.string().describe("Task brief, current."),
    briefVersion: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Versioned brief counter; bumped on every revision."),
    status: z.string().describe("Wire-form status (PascalCase)."),
    resolutionOutcome: z.nullable(
      z.string().describe("Wire-form outcome if Resolved; null otherwise.")
    ),
    attemptOrdinal: z
      .union([z.int(), z.string().regex(/^-?(?:0|[1-9]\d*)$/)])
      .describe("Current attempt ordinal; 1 before any append."),
    activeAttemptId: z.nullable(
      z
        .uuid()
        .describe("Active attempt's run id; null when no attempt is in flight.")
    ),
    visibility: z.string().describe("Standalone | MissionAttached."),
    missionId: z.nullable(
      z.uuid().describe("Owning mission if MissionAttached; null otherwise.")
    ),
    get sourceRefs() {
      return z
        .array(
          workTaskSourceRefViewSchema.describe(
            "Per-source-ref wire projection."
          )
        )
        .describe("All source refs on the Task (primary first).")
    },
    createdAt: z.iso
      .datetime({ offset: true })
      .describe("When the Task was first admitted."),
    updatedAt: z.iso.datetime({ offset: true }).describe("Last status change."),
  })
  .describe(
    'Per-Task detail projection — the `GET /api/v1/work/tasks/{taskId}`\nresponse shape (the umbrella\'s `add-work-management` design\n§"Work API"). Caller-facing fields only — no aggregate internals.'
  )
