/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InfoResponse = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  version: string
  /**
   * @type string
   */
  phase: string
}
