using System.Reflection;
using System.Text;
using Comuki.Shared.Editions.Tiers;

namespace Comuki.Shared.Editions.Catalog;

/// <summary>
/// Emits the two code-generated artefacts the editions catalogue owns
/// (issue #164, change <c>add-editions-and-licensing</c> WS2):
/// <list type="bullet">
///   <item><see cref="EmitRegistryTs"/> — a TypeScript module the
///     dashboard imports for typed feature/limit keys (the only
///     closed-vocabulary it needs to compile against).</item>
///   <item><see cref="EmitCapabilityMatrix"/> — a Markdown table the
///     operator-facing docs site renders directly, one row per entry of
///     <see cref="Features"/>/<see cref="Limits"/> with the per-tier
///     capability verdict.</item>
/// </list>
/// The emitter reads the <see cref="Features"/> and <see cref="Limits"/>
/// catalogues via reflection, plus <see cref="EditionTiers.All"/> for
/// rank→code resolution — it is the single door through which the
/// derived artefacts see the catalogue, so an edition added by appending
/// a row to either catalogue flows into both artefacts automatically on
/// the next codegen run.
/// <para>
/// Both methods are deterministic: rows are sorted by key (the catalogues
/// guarantee this via <see cref="EditionCatalogGuard"/>) and the TS
/// object-literal entries are emitted in that key order. The CI
/// architecture test (<c>GeneratedEditionsArtifactsMatchRegistryShould</c>)
/// re-emits and compares bytes against the committed artefacts; a casual
/// key reshuffle that changes emitted order fails the test before the
/// diff reaches review.
/// </para>
/// <para>
/// Hand-rolled over reflection rather than a Roslyn source generator
/// because the surface is small (eight features, one limit today) — the
/// cost of a build-time codegen pipeline is not yet justified, mirroring
/// the choice made for <c>RealtimeContractEmitter</c>. When the slice
/// grows past the low-tens of entries, swap the body for an
/// <c>IIncrementalGenerator</c> that reads the same public surface via
/// <c>ForAttributeWithMetadataName</c> and emits to
/// <c>obj/generated/comuki-editions/</c>.
/// </para>
/// </summary>
internal static class RegistryEmitter
{
    /// <summary>
    /// Renders the TypeScript module carrying the typed
    /// <c>Features</c>/<c>FeatureKey</c>/<c>Limits</c>/<c>LimitKey</c>
    /// surface. Property names mirror the C# static-property names on
    /// <see cref="Features"/>/<see cref="Limits"/> (PascalCase) — the
    /// dashboard's call sites stay <c>Features.MultiRepo</c>-shaped,
    /// not <c>Features.Multi_Repo</c>-shaped, and the value side carries
    /// the well-formed registry key (kebab-case).
    /// </summary>
    /// <returns>A self-contained TypeScript string. Deterministic for a given <see cref="Features"/>/<see cref="Limits"/> state.</returns>
    internal static string EmitRegistryTs()
    {
        var featureEntries = RegistryEmitterHelpers.LoadFeatures();
        var limitEntries = RegistryEmitterHelpers.LoadLimits();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Source: platform/src/shared/Comuki.Shared.Editions/Catalog/RegistryEmitter.cs");
        builder.AppendLine("// Regenerate via: dotnet run --project tools/Comuki.Codegen.Editions");
        builder.AppendLine("// The dashboard's typed feature/limit keys live here. Hand-edits are overwritten on the next Debug build.");
        builder.AppendLine();

        builder.AppendLine("export const Features = {");
        foreach (var entry in featureEntries)
        {
            builder.Append("  ").Append(entry.PropertyName).Append(": \"").Append(entry.KeyValue).AppendLine("\",");
        }

        builder.AppendLine("} as const;");
        builder.AppendLine("export type FeatureKey = (typeof Features)[keyof typeof Features];");
        builder.AppendLine();

        builder.AppendLine("export const Limits = {");
        foreach (var entry in limitEntries)
        {
            builder.Append("  ").Append(entry.PropertyName).Append(": \"").Append(entry.KeyValue).AppendLine("\",");
        }

        builder.AppendLine("} as const;");
        builder.AppendLine("export type LimitKey = (typeof Limits)[keyof typeof Limits];");
        builder.AppendLine();

        return builder.ToString();
    }

    /// <summary>
    /// Renders the Markdown capability matrix: one table for features,
    /// one for limits, both with the same four columns
    /// (<c>Key</c> / <c>Description</c> / <c>Community</c> / <c>Paid</c>).
    /// </summary>
    /// <returns>A deterministic Markdown string. Pipe characters in descriptions are escaped so the table never breaks.</returns>
    internal static string EmitCapabilityMatrix()
    {
        var features = RegistryEmitterHelpers.LoadFeatures();
        var limits = RegistryEmitterHelpers.LoadLimits();

        var builder = new StringBuilder();
        builder.AppendLine("# Comuki editions capability matrix");
        builder.AppendLine();
        builder.AppendLine("<!-- <auto-generated />");
        builder.AppendLine("Source: platform/src/shared/Comuki.Shared.Editions/Catalog/RegistryEmitter.cs");
        builder.AppendLine("Regenerate via: dotnet run --project tools/Comuki.Codegen.Editions");
        builder.AppendLine("The committed file matches what the host gates against; a CI architecture test fails the build when the");
        builder.AppendLine("registry drifts from this matrix. Hand-edits are overwritten on the next Debug build. -->");
        builder.AppendLine();

        builder.AppendLine("## Features");
        builder.AppendLine();
        builder.AppendLine("| Key | Description | Community | Paid |");
        builder.AppendLine("| --- | --- | --- | --- |");
        foreach (var feature in features)
        {
            builder.Append("| ").Append(RegistryEmitterHelpers.EscapeMarkdown(feature.KeyValue))
                .Append(" | ").Append(RegistryEmitterHelpers.EscapeMarkdown(feature.Description))
                .Append(" | no | ").Append(RegistryEmitterHelpers.PaidCodeFor(feature.MinimumRank))
                .AppendLine(" |");
        }

        builder.AppendLine();
        builder.AppendLine("## Limits");
        builder.AppendLine();
        builder.AppendLine("| Key | Description | Community | Paid |");
        builder.AppendLine("| --- | --- | --- | --- |");
        foreach (var limit in limits)
        {
            builder.Append("| ").Append(RegistryEmitterHelpers.EscapeMarkdown(limit.KeyValue))
                .Append(" | ").Append(RegistryEmitterHelpers.EscapeMarkdown(limit.Description))
                .Append(" | ").Append(limit.CommunityValue)
                .Append(" | ").Append(RegistryEmitterHelpers.FormatPaidValues(limit.PaidValues))
                .AppendLine(" |");
        }

        builder.AppendLine();
        return builder.ToString();
    }
}

/// <summary>
/// Pure-function helpers and the small row records the emitter reads
/// from <see cref="Features"/>/<see cref="Limits"/>. <c>file static</c>
/// so the emitter itself stays free of <c>private</c> methods (project
/// rule <c>class-layout-and-tooling.md</c> §1a) and the row records stay
/// private to the codegen surface — neither leaks out of this file.
/// </summary>
file static class RegistryEmitterHelpers
{
    /// <summary>
    /// Reflects over every public <c>static</c> instance field on
    /// <see cref="Features"/> whose value is a <see cref="Feature"/>,
    /// excluding <c>All</c> (typed differently). Sorted by the
    /// field's <see cref="Feature.Key"/> value (ordinal) so the
    /// emitted artefact is byte-stable across runs.
    /// </summary>
    public static IReadOnlyList<FeatureRow> LoadFeatures()
    {
        var rows = typeof(Features)
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(static field => field.FieldType == typeof(Feature))
            .Select(static field =>
            {
                var feature = (Feature)field.GetValue(null)!;
                return new FeatureRow(
                    PropertyName: field.Name,
                    KeyValue: feature.Key.Value,
                    Description: feature.Description,
                    MinimumRank: feature.MinimumRank);
            })
            .OrderBy(static row => row.KeyValue, StringComparer.Ordinal);

        return [.. rows];
    }

    /// <summary>Reflects over the <see cref="Limits"/> catalogue the same way as <see cref="LoadFeatures"/>.</summary>
    public static IReadOnlyList<LimitRow> LoadLimits()
    {
        var rows = typeof(Limits)
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(static field => field.FieldType == typeof(Limit))
            .Select(static field =>
            {
                var limit = (Limit)field.GetValue(null)!;
                var paid = limit.PaidValues
                    .OrderBy(static pair => pair.Key)
                    .Select(static pair => new PaidValueRow(pair.Key, pair.Value))
                    .ToArray();
                return new LimitRow(
                    PropertyName: field.Name,
                    KeyValue: limit.Key.Value,
                    Description: limit.Description,
                    CommunityValue: limit.CommunityValue,
                    PaidValues: paid);
            })
            .OrderBy(static row => row.KeyValue, StringComparer.Ordinal);

        return [.. rows];
    }

    /// <summary>Looks up the tier code whose <see cref="EditionTier.Rank"/> matches <paramref name="rank"/>.</summary>
    /// <param name="rank">The minimum rank the feature requires.</param>
    /// <returns>The tier code (e.g. <c>"team"</c>), or <c>"(unknown-tier)"</c> when no tier carries that rank.</returns>
    public static string PaidCodeFor(int rank)
    {
        foreach (var tier in EditionTiers.All)
        {
            if (tier.Rank == rank)
            {
                return tier.Code;
            }
        }

        return "(unknown-tier)";
    }

    /// <summary>Comma-joined <c>"code: value"</c> entries, or <c>"none"</c> when the limit has no paid overrides.</summary>
    /// <param name="paidValues">The pre-sorted (by rank ascending) per-rank paid overrides to render.</param>
    public static string FormatPaidValues(IReadOnlyList<PaidValueRow> paidValues)
    {
        return paidValues.Count == 0
            ? "none"
            : string.Join(", ", paidValues.Select(static pair => $"{PaidCodeFor(pair.Rank)}: {pair.Value}"));
    }

    /// <summary>
    /// Escapes Markdown table-pipe characters (<c>|</c>) so a description
    /// containing one cannot break the column layout. No other escapes
    /// are needed today; the descriptions are hand-curated and review-time
    /// audited for ASCII (the literal pipe character has no culture-sensitive
    /// casing rules, so the default <see cref="string.Replace(string, string)"/>
    /// behaves identically to an ordinal one).
    /// </summary>
    /// <param name="value">The raw cell text.</param>
    public static string EscapeMarkdown(string value)
    {
        return value.Replace("|", "\\|");
    }

    /// <summary>One feature row, shaped for the TS object and the Markdown table.</summary>
    public sealed record FeatureRow(string PropertyName, string KeyValue, string Description, int MinimumRank);

    /// <summary>One limit row, shaped for the TS object and the Markdown table.</summary>
    public sealed record LimitRow(
        string PropertyName,
        string KeyValue,
        string Description,
        int CommunityValue,
        IReadOnlyList<PaidValueRow> PaidValues);

    /// <summary>One paid-tier override on a limit, pre-sorted by rank.</summary>
    public sealed record PaidValueRow(int Rank, int Value);
}
